Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORMBR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORMBR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORMBR (LSAME lsame, ILAENV ilaenv, DORMLQ dormlq, DORMQR dormqr, XERBLA xerbla)
DORMBR ()
void Run (string VECT, string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DORMLQ _dormlq
DORMQR _dormqr
XERBLA _xerbla
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
If VECT = 'Q', DORMBR overwrites the general real M-by-N matrix C with SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
If VECT = 'P', DORMBR overwrites the general real M-by-N matrix C with SIDE = 'L' SIDE = 'R' TRANS = 'N': P * C C * P TRANS = 'T': P**T * C C * P**T
Here Q and P**T are the orthogonal matrices determined by DGEBRD when reducing a real matrix A to bidiagonal form: A = Q * B * P**T. Q and P**T are defined as products of elementary reflectors H(i) and G(i) respectively.
Let nq = m if SIDE = 'L' and nq = n if SIDE = 'R'. Thus nq is the order of the orthogonal matrix Q or P**T that is applied.
If VECT = 'Q', A is assumed to have been an NQ-by-K matrix: if nq .GE. k, Q = H(1) H(2) . . . H(k); if nq .LT. k, Q = H(1) H(2) . . . H(nq-1).
If VECT = 'P', A is assumed to have been a K-by-NQ matrix: if k .LT. nq, P = G(1) G(2) . . . G(k); if k .GE. nq, P = G(1) G(2) . . . G(nq-1).
/summary>
Constructor & Destructor Documentation
DORMBR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORMBR.DORMBR (LSAME lsame, ILAENV ilaenv, DORMLQ dormlq, DORMQR dormqr, XERBLA xerbla) inline
DORMBR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORMBR.DORMBR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run (string VECT, string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
If VECT = 'Q', DORMBR overwrites the general real M-by-N matrix C with SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
If VECT = 'P', DORMBR overwrites the general real M-by-N matrix C with SIDE = 'L' SIDE = 'R' TRANS = 'N': P * C C * P TRANS = 'T': P**T * C C * P**T
Here Q and P**T are the orthogonal matrices determined by DGEBRD when reducing a real matrix A to bidiagonal form: A = Q * B * P**T. Q and P**T are defined as products of elementary reflectors H(i) and G(i) respectively.
Let nq = m if SIDE = 'L' and nq = n if SIDE = 'R'. Thus nq is the order of the orthogonal matrix Q or P**T that is applied.
If VECT = 'Q', A is assumed to have been an NQ-by-K matrix: if nq .GE. k, Q = H(1) H(2) . . . H(k); if nq .LT. k, Q = H(1) H(2) . . . H(nq-1).
If VECT = 'P', A is assumed to have been a K-by-NQ matrix: if k .LT. nq, P = G(1) G(2) . . . G(k); if k .GE. nq, P = G(1) G(2) . . . G(nq-1).
/summary>
Parameters
VECT (input) CHARACTER*1 = 'Q': apply Q or Q**T; = 'P': apply P or P**T. /param>
Parameters
SIDE (input) CHARACTER*1 = 'L': apply Q, Q**T, P or P**T from the Left; = 'R': apply Q, Q**T, P or P**T from the Right. /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': No transpose, apply Q or P; = 'T': Transpose, apply Q**T or P**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. N .GE. 0. /param>
Parameters
K (input) INTEGER If VECT = 'Q', the number of columns in the original matrix reduced by DGEBRD. If VECT = 'P', the number of rows in the original matrix reduced by DGEBRD. K .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,min(nq,K)) if VECT = 'Q' (LDA,nq) if VECT = 'P' The vectors which define the elementary reflectors H(i) and G(i), whose products determine the matrices Q and P, as returned by DGEBRD. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. If VECT = 'Q', LDA .GE. max(1,nq); if VECT = 'P', LDA .GE. max(1,min(nq,K)). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (min(nq,K)) TAU(i) must contain the scalar factor of the elementary reflector H(i) or G(i) which determines Q or P, as returned by DGEBRD in the array argument TAUQ or TAUP. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by Q*C or Q**T*C or C*Q**T or C*Q or P*C or P**T*C or C*P or C*P**T. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If SIDE = 'L', LWORK .GE. max(1,N); if SIDE = 'R', LWORK .GE. max(1,M). For optimum performance LWORK .GE. N*NB if SIDE = 'L', and LWORK .GE. M*NB if SIDE = 'R', where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORMBR._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORMBR._ilaenv private
_dormlq
DORMLQ DotNumerics.LinearAlgebra.CSLapack.DORMBR._dormlq private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DORMBR._dormqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORMBR._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dormbr.cs