Doc: IGLib EXTENDED: AForge.Video Namespace Reference
AForge.Video Namespace Reference
Namespaces
namespace DirectShow
namespace Kinect
namespace VFW
namespace Ximea
Classes
class AsyncVideoSource
Proxy video source for asynchronous processing of another nested video source.
class ByteArrayUtils
Some internal utilities for handling arrays.
interface IVideoSource
Video source interface.
class JPEGStream
JPEG video source.
class MJPEGStream
MJPEG video source.
class NewFrameEventArgs
Arguments for new frame event from video source.
class VideoException
Video related exception.
class VideoSourceErrorEventArgs
Arguments for video source error event from video source.
Enumerations
enum ReasonToFinishPlaying { ReasonToFinishPlaying.EndOfStreamReached, ReasonToFinishPlaying.StoppedByUser, ReasonToFinishPlaying.DeviceLost, ReasonToFinishPlaying.VideoSourceError }
Reason of finishing video playing.
Functions
delegate void NewFrameEventHandler (object sender, NewFrameEventArgs eventArgs)
Delegate for new frame event handler.
delegate void VideoSourceErrorEventHandler (object sender, VideoSourceErrorEventArgs eventArgs)
Delegate for video source error event handler.
delegate void PlayingFinishedEventHandler (object sender, ReasonToFinishPlaying reason)
Delegate for playing finished event handler.
Enumeration Type Documentation
ReasonToFinishPlaying
enum AForge.Video.ReasonToFinishPlaying strong
Reason of finishing video playing.
When video source class fire the IVideoSource.PlayingFinished event, they need to specify reason of finishing video playing. For example, it may be end of stream reached.
Enumerator
EndOfStreamReached
Video playing has finished because it end was reached.
StoppedByUser
Video playing has finished because it was stopped by user.
DeviceLost
Video playing has finished because the device was lost (unplugged).
VideoSourceError
Video playing has finished because of some error happened the video source (camera, stream, file, etc.). A error reporting event usually is fired to provide error information.
Function Documentation
NewFrameEventHandler()
delegate void AForge.Video.NewFrameEventHandler (object sender, NewFrameEventArgs eventArgs)
Delegate for new frame event handler.
Parameters
sender Sender object.
eventArgs Event arguments.
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.Disconnect(), AForge.Video.AsyncVideoSource.Free(), and AForge.Video.AsyncVideoSource.Start().
VideoSourceErrorEventHandler()
delegate void AForge.Video.VideoSourceErrorEventHandler (object sender, VideoSourceErrorEventArgs eventArgs)
Delegate for video source error event handler.
Parameters
sender Sender object.
eventArgs Event arguments.
PlayingFinishedEventHandler()
delegate void AForge.Video.PlayingFinishedEventHandler (object sender, ReasonToFinishPlaying reason)
Delegate for playing finished event handler.
Parameters
sender Sender object.
reason Reason of finishing video playing.