Doc: IGLib EXTENDED: IG.Test.Json Class Reference
IG.Test.Json Class Reference
Testing various JSON utilities - parsing, serialization/deserialization (either to statically or dynamically typed objects), etc.
Public Member Functions
void Main_ ()
Static Public Member Functions
static void Run ()
Testing of JSON utilities.
static void Main_DynamicWrapperExamples ()
Runs some examples form the DynamicWrapper class.
static void Main_Dynamic ()
Playing with dynamic objects and dynamic declarations.
static T DeserializeJson< T > (string json)
take JSON and convert it to a strongly typed class of which you specify (T):
static string SerializeJson< T > (T obj)
static void Main_SystemWebHelpers ()
JSON objects by use of System.Web.Helpers.
static void Main_JsonBasic ()
static void Main_JsonBasic (string jsonString)
Detailed Description
Testing various JSON utilities - parsing, serialization/deserialization (either to statically or dynamically typed objects), etc.
See Also:
How can I parse JSON with C#? http://stackoverflow.com/questions/6620165/how-can-i-parse-json-with-c
Deserialize JSON into C# dynamic object? http://stackoverflow.com/questions/3142495/deserialize-json-into-c-sharp-dynamic-object
Where can I find System.Web.Helpers, System.Web.WebPages, and System.Web.Razor? http://stackoverflow.com/questions/8037895/where-can-i-find-system-web-helpers-system-web-webpages-and-system-web-razor
Member Function Documentation
Run()
static void IG.Test.Json.Run () inline static
Testing of JSON utilities.
References IG.Test.Json.Main_DynamicWrapperExamples().
Referenced by IG.Test.Program_IGTestQuick.Main().
Main_DynamicWrapperExamples()
static void IG.Test.Json.Main_DynamicWrapperExamples () inline static
Runs some examples form the DynamicWrapper class.
References IG.Lib.DynamicWrapper.ExampleElementReferencing().
Referenced by IG.Test.Json.Run().
Main_Dynamic()
static void IG.Test.Json.Main_Dynamic () inline static
Playing with dynamic objects and dynamic declarations.
DeserializeJson< T >()
static T IG.Test.Json.DeserializeJson< T > (string json) inline static
take JSON and convert it to a strongly typed class of which you specify (T):
Template Parameters
T Type of object to be returned:
Parameters
json
Returns
SerializeJson< T >()
static string IG.Test.Json.SerializeJson< T > (T obj) inline static
Main_SystemWebHelpers()
static void IG.Test.Json.Main_SystemWebHelpers () inline static
JSON objects by use of System.Web.Helpers.
Main_JsonBasic() [1/2]
static void IG.Test.Json.Main_JsonBasic () inline static
Main_JsonBasic() [2/2]
static void IG.Test.Json.Main_JsonBasic (string jsonString) inline static
References IG.Lib.DynamicWrapperBase.GetReadableJsonStringS().
Main_()
void IG.Test.Json.Main_ () inline
The documentation for this class was generated from the following file:
unittests/Guest_IGTestQuick/Json/Json.cs