Doc: IGLib EXTENDED: NUnit.Framework.Assertions.LessEqualFixture Class Reference
NUnit.Framework.Assertions.LessEqualFixture Class Reference
Public Member Functions
void LessOrEqual ()
void MixedTypes ()
void NotLessOrEqual ()
void NotLessEqualIComparable ()
void FailureMessage ()
Private Attributes
readonly int i1 = 5
readonly int i2 = 8
readonly uint u1 = 12345678
readonly uint u2 = 12345879
readonly long l1 = 12345678
readonly long l2 = 12345879
readonly ulong ul1 = 12345678
readonly ulong ul2 = 12345879
readonly float f1 = 3.543F
readonly float f2 = 8.543F
readonly decimal de1 = 53.4M
readonly decimal de2 = 83.4M
readonly double d1 = 4.85948654
readonly double d2 = 8.0
readonly System.Enum e1 = RunState.Explicit
readonly System.Enum e2 = RunState.Ignored
Member Function Documentation
LessOrEqual()
void NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual () inline
References NUnit.Framework.Assertions.LessEqualFixture.d1, NUnit.Framework.Assertions.LessEqualFixture.d2, NUnit.Framework.Assertions.LessEqualFixture.de1, NUnit.Framework.Assertions.LessEqualFixture.de2, NUnit.Framework.Assertions.LessEqualFixture.f1, NUnit.Framework.Assertions.LessEqualFixture.f2, NUnit.Framework.Assertions.LessEqualFixture.i1, NUnit.Framework.Assertions.LessEqualFixture.i2, NUnit.Framework.Assertions.LessEqualFixture.l1, NUnit.Framework.Assertions.LessEqualFixture.l2, NUnit.Framework.Assert.LessOrEqual(), NUnit.Framework.Assertions.LessEqualFixture.u1, NUnit.Framework.Assertions.LessEqualFixture.u2, NUnit.Framework.Assertions.LessEqualFixture.ul1, and NUnit.Framework.Assertions.LessEqualFixture.ul2.
MixedTypes()
void NUnit.Framework.Assertions.LessEqualFixture.MixedTypes () inline
References NUnit.Framework.Assert.LessOrEqual().
NotLessOrEqual()
void NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assertions.LessEqualFixture.i1, NUnit.Framework.Assertions.LessEqualFixture.i2, NUnit.Framework.Assert.LessOrEqual(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotLessEqualIComparable()
void NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable () inline
References NUnit.Framework.Assertions.LessEqualFixture.e1, NUnit.Framework.Assertions.LessEqualFixture.e2, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.LessOrEqual(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
FailureMessage()
void NUnit.Framework.Assertions.LessEqualFixture.FailureMessage () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.LessOrEqual(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
i1
readonly int NUnit.Framework.Assertions.LessEqualFixture.i1 = 5 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual(), and NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual().
i2
readonly int NUnit.Framework.Assertions.LessEqualFixture.i2 = 8 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual(), and NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual().
u1
readonly uint NUnit.Framework.Assertions.LessEqualFixture.u1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
u2
readonly uint NUnit.Framework.Assertions.LessEqualFixture.u2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
l1
readonly long NUnit.Framework.Assertions.LessEqualFixture.l1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
l2
readonly long NUnit.Framework.Assertions.LessEqualFixture.l2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
ul1
readonly ulong NUnit.Framework.Assertions.LessEqualFixture.ul1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
ul2
readonly ulong NUnit.Framework.Assertions.LessEqualFixture.ul2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
f1
readonly float NUnit.Framework.Assertions.LessEqualFixture.f1 = 3.543F private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
f2
readonly float NUnit.Framework.Assertions.LessEqualFixture.f2 = 8.543F private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
de1
readonly decimal NUnit.Framework.Assertions.LessEqualFixture.de1 = 53.4M private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
de2
readonly decimal NUnit.Framework.Assertions.LessEqualFixture.de2 = 83.4M private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
d1
readonly double NUnit.Framework.Assertions.LessEqualFixture.d1 = 4.85948654 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
d2
readonly double NUnit.Framework.Assertions.LessEqualFixture.d2 = 8.0 private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual().
e1
readonly System.Enum NUnit.Framework.Assertions.LessEqualFixture.e1 = RunState.Explicit private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable().
e2
readonly System.Enum NUnit.Framework.Assertions.LessEqualFixture.e2 = RunState.Ignored private
Referenced by NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/LessEqualFixture.cs