Doc: IGLib EXTENDED: AForge.Neuro.Learning.ResilientBackpropagationLearning Class Reference
AForge.Neuro.Learning.ResilientBackpropagationLearning Class Reference
Resilient Backpropagation learning algorithm.
Public Member Functions
ResilientBackpropagationLearning (ActivationNetwork network)
Initializes a new instance of the ResilientBackpropagationLearning class.
double Run (double[] input, double[] output)
Runs learning iteration.
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch.
Properties
double LearningRate [get, set]
Learning rate.
Private Member Functions
void ResetGradient ()
Resets current weight and threshold derivatives.
void ResetUpdates (double rate)
Resets the current update steps using the given learning rate.
void UpdateNetwork ()
Update network's weights.
double CalculateError (double[] desiredOutput)
Calculates error values for all neurons of the network.
void CalculateGradient (double[] input)
Calculate weights updates
Private Attributes
ActivationNetwork network
double learningRate = 0.0125
double deltaMax = 50.0
double deltaMin = 1e-6
double etaPlus = 1.2
double[][] neuronErrors = null
double[][][] weightsUpdates = null
double[][] thresholdsUpdates = null
double[][][] weightsDerivatives = null
double[][] thresholdsDerivatives = null
double[][][] weightsPreviousDerivatives = null
double[][] thresholdsPreviousDerivatives = null
Static Private Attributes
const double etaMinus = 0.5
Detailed Description
Resilient Backpropagation learning algorithm.
This class implements the resilient backpropagation (RProp) learning algorithm. The RProp learning algorithm is one of the fastest learning algorithms for feed-forward learning networks which use only first-order information.
Sample usage (training network to calculate XOR function):
// initialize input and output values
double[][] input = new double[4][] {
    new double[] {0, 0}, new double[] {0, 1},
    new double[] {1, 0}, new double[] {1, 1}
};
double[][] output = new double[4][] {
    new double[] {0}, new double[] {1},
    new double[] {1}, new double[] {0}
};
// create neural network
ActivationNetwork   network = new ActivationNetwork(
    SigmoidFunction( 2 ),
    2, // two inputs in the network
    2, // two neurons in the first layer
    1 ); // one neuron in the second layer
// create teacher
ResilientBackpropagationLearning teacher = new ResilientBackpropagationLearning(network);
// loop
while (!needToStop)
{
    // run epoch of learning procedure
    double error = teacher.RunEpoch( input, output );
    // check error value to see if we need to stop
    // ...
}
Constructor & Destructor Documentation
ResilientBackpropagationLearning()
AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning (ActivationNetwork network) inline
Initializes a new instance of the ResilientBackpropagationLearning class.
Parameters
network Network to teach.
References AForge.Neuro.Layer.InputsCount, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ResilientBackpropagationLearning.learningRate, AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Learning.ResilientBackpropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetUpdates(), AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsPreviousDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsUpdates, AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsPreviousDerivatives, and AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsUpdates.
Member Function Documentation
Run()
double AForge.Neuro.Learning.ResilientBackpropagationLearning.Run (double[] input, double[] output) inline
Runs learning iteration.
Parameters
input Input vector.
output Desired output vector.
Returns
Returns squared error (difference between current network's output and desired output) divided by 2.
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetGradient(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
RunEpoch()
double AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch.
Parameters
input Array of input vectors.
output Array of output vectors.
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
The method runs one learning epoch, by calling Run method for each vector provided in the input array.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetGradient(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
ResetGradient()
void AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetGradient () inline private
Resets current weight and threshold derivatives.
References AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsDerivatives, and AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsDerivatives.
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch().
ResetUpdates()
void AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetUpdates (double rate) inline private
Resets the current update steps using the given learning rate.
References AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsUpdates.
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning().
UpdateNetwork()
void AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork () inline private
Update network's weights.
References AForge.Neuro.Learning.ResilientBackpropagationLearning.deltaMax, AForge.Neuro.Learning.ResilientBackpropagationLearning.deltaMin, AForge.Neuro.Learning.ResilientBackpropagationLearning.etaMinus, AForge.Neuro.Learning.ResilientBackpropagationLearning.etaPlus, AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Layer.Neurons, AForge.Neuro.ActivationNeuron.Threshold, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsPreviousDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsUpdates, AForge.Neuro.Neuron.Weights, AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsDerivatives, AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsPreviousDerivatives, and AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsUpdates.
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch().
CalculateError()
double AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError (double[] desiredOutput) inline private
Calculates error values for all neurons of the network.
Parameters
desiredOutput Desired output vector.
Returns
Returns summary squared error of the last layer divided by 2.
References AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Learning.ResilientBackpropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Neuron.Output, and AForge.Neuro.Neuron.Weights.
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch().
CalculateGradient()
void AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient (double[] input) inline private
Calculate weights updates
Parameters
input Network's input vector.
References AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ResilientBackpropagationLearning.network, AForge.Neuro.Learning.ResilientBackpropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Neuron.Output, AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsDerivatives, and AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsDerivatives.
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch().
Member Data Documentation
network
ActivationNetwork AForge.Neuro.Learning.ResilientBackpropagationLearning.network private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
learningRate
double AForge.Neuro.Learning.ResilientBackpropagationLearning.learningRate = 0.0125 private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning().
deltaMax
double AForge.Neuro.Learning.ResilientBackpropagationLearning.deltaMax = 50.0 private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
deltaMin
double AForge.Neuro.Learning.ResilientBackpropagationLearning.deltaMin = 1e-6 private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
etaMinus
const double AForge.Neuro.Learning.ResilientBackpropagationLearning.etaMinus = 0.5 static private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
etaPlus
double AForge.Neuro.Learning.ResilientBackpropagationLearning.etaPlus = 1.2 private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
neuronErrors
double [][] AForge.Neuro.Learning.ResilientBackpropagationLearning.neuronErrors = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning().
weightsUpdates
double [][][] AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsUpdates = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetUpdates(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
thresholdsUpdates
double [][] AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsUpdates = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetUpdates(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
weightsDerivatives
double [][][] AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsDerivatives = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetGradient(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
thresholdsDerivatives
double [][] AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsDerivatives = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResetGradient(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
weightsPreviousDerivatives
double [][][] AForge.Neuro.Learning.ResilientBackpropagationLearning.weightsPreviousDerivatives = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
thresholdsPreviousDerivatives
double [][] AForge.Neuro.Learning.ResilientBackpropagationLearning.thresholdsPreviousDerivatives = null private
Referenced by AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), and AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork().
Property Documentation
LearningRate
double AForge.Neuro.Learning.ResilientBackpropagationLearning.LearningRate get set
Learning rate.
The value determines speed of learning.
Default value equals to 0.0125.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Neuro/Learning/ResilientBackPropagationLearning.cs