Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD3 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD3 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLASCL dlascl, DLASD4 dlasd4, XERBLA xerbla)
DLASD3 ()
void Run (int NL, int NR, int SQRE, int K, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref double[] DSIGMA, int offset_dsigma, ref double[] U, int offset_u, int LDU, double[] U2, int offset_u2, int LDU2, ref double[] VT, int offset_vt, int LDVT, ref double[] VT2, int offset_vt2, int LDVT2, int[] IDXC, int offset_idxc, int[] CTOT, int offset_ctot, ref double[] Z, int offset_z, ref int INFO)
Private Attributes
DLAMC3 _dlamc3
DNRM2 _dnrm2
DCOPY _dcopy
DGEMM _dgemm
DLACPY _dlacpy
DLASCL _dlascl
DLASD4 _dlasd4
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
const double NEGONE = - 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASD3 finds all the square roots of the roots of the secular equation, as defined by the values in D and Z. It makes the appropriate calls to DLASD4 and then updates the singular vectors by matrix multiplication.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
DLASD3 is called from DLASD1.
/summary>
Constructor & Destructor Documentation
DLASD3() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD3.DLASD3 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLASCL dlascl, DLASD4 dlasd4, XERBLA xerbla) inline
DLASD3() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD3.DLASD3 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run (int NL, int NR, int SQRE, int K, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref double[] DSIGMA, int offset_dsigma, ref double[] U, int offset_u, int LDU, double[] U2, int offset_u2, int LDU2, ref double[] VT, int offset_vt, int LDVT, ref double[] VT2, int offset_vt2, int LDVT2, int[] IDXC, int offset_idxc, int[] CTOT, int offset_ctot, ref double[] Z, int offset_z, ref int INFO) inline
Purpose
DLASD3 finds all the square roots of the roots of the secular equation, as defined by the values in D and Z. It makes the appropriate calls to DLASD4 and then updates the singular vectors by matrix multiplication.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
DLASD3 is called from DLASD1.
/summary>
Parameters
NL (input) INTEGER The row dimension of the upper block. NL .GE. 1. /param>
Parameters
NR (input) INTEGER The row dimension of the lower block. NR .GE. 1. /param>
Parameters
SQRE (input) INTEGER = 0: the lower block is an NR-by-NR square matrix. = 1: the lower block is an NR-by-(NR+1) rectangular matrix.
The bidiagonal matrix has N = NL + NR + 1 rows and M = N + SQRE .GE. N columns. /param>
Parameters
K (input) INTEGER The size of the secular equation, 1 =.LT. K = .LT. N. /param>
Parameters
D (output) DOUBLE PRECISION array, dimension(K) On exit the square roots of the roots of the secular equation, in ascending order. /param>
Parameters
Q (workspace) DOUBLE PRECISION array, dimension at least (LDQ,K). /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. K. /param>
Parameters
DSIGMA (input) DOUBLE PRECISION array, dimension(K) The first K elements of this array contain the old roots of the deflated updating problem. These are the poles of the secular equation. /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU, N) The last N - K columns of this matrix contain the deflated left singular vectors. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. N. /param>
Parameters
U2 (input/output) DOUBLE PRECISION array, dimension (LDU2, N) The first K columns of this matrix contain the non-deflated left singular vectors for the split problem. /param>
Parameters
LDU2 (input) INTEGER The leading dimension of the array U2. LDU2 .GE. N. /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension (LDVT, M) The last M - K columns of VT' contain the deflated right singular vectors. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. N. /param>
Parameters
VT2 (input/output) DOUBLE PRECISION array, dimension (LDVT2, N) The first K columns of VT2' contain the non-deflated right singular vectors for the split problem. /param>
Parameters
LDVT2 (input) INTEGER The leading dimension of the array VT2. LDVT2 .GE. N. /param>
Parameters
IDXC (input) INTEGER array, dimension (N) The permutation used to arrange the columns of U (and rows of VT) into three groups: the first group contains non-zero entries only at and above (or before) NL +1; the second contains non-zero entries only at and below (or after) NL+2; and the third is dense. The first column of U and the row of VT are treated separately, however.
The rows of the singular vectors found by DLASD4 must be likewise permuted before the matrix multiplies can take place. /param>
Parameters
CTOT (input) INTEGER array, dimension (4) A count of the total number of the various types of columns in U (or rows in VT), as described in IDXC. The fourth column type is any column which has been deflated. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the components of the deflation-adjusted updating row vector. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an singular value did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD3.NEGONE, DotNumerics.LinearAlgebra.CSLapack.DLASD3.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), and DotNumerics.LinearAlgebra.CSLapack.DLASD3.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run().
Member Data Documentation
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLASD3._dlamc3 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLASD3._dnrm2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASD3._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLASD3._dgemm private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLASD3._dlacpy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLASD3._dlascl private
_dlasd4
DLASD4 DotNumerics.LinearAlgebra.CSLapack.DLASD3._dlasd4 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD3._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD3.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD3.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run().
NEGONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD3.NEGONE = - 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd3.cs