Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLALSD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLALSD Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLALSD (IDAMAX idamax, DLAMCH dlamch, DLANST dlanst, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLALSA dlalsa, DLARTG dlartg, DLASCL dlascl, DLASDA dlasda, DLASDQ dlasdq, DLASET dlaset, DLASRT dlasrt, DROT drot, XERBLA xerbla)
DLALSD ()
void Run (string UPLO, int SMLSIZ, int N, int NRHS, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] B, int offset_b, int LDB, double RCOND, ref int RANK, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
IDAMAX _idamax
DLAMCH _dlamch
DLANST _dlanst
DCOPY _dcopy
DGEMM _dgemm
DLACPY _dlacpy
DLALSA _dlalsa
DLARTG _dlartg
DLASCL _dlascl
DLASDA _dlasda
DLASDQ _dlasdq
DLASET _dlaset
DLASRT _dlasrt
DROT _drot
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLALSD uses the singular value decomposition of A to solve the least squares problem of finding X to minimize the Euclidean norm of each column of A*X-B, where A is N-by-N upper bidiagonal, and X and B are N-by-NRHS. The solution X overwrites B.
The singular values of A smaller than RCOND times the largest singular value are treated as zero in solving the least squares problem; in this case a minimum norm solution is returned. The actual singular values are returned in D in ascending order.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Constructor & Destructor Documentation
DLALSD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLALSD.DLALSD (IDAMAX idamax, DLAMCH dlamch, DLANST dlanst, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLALSA dlalsa, DLARTG dlartg, DLASCL dlascl, DLASDA dlasda, DLASDQ dlasdq, DLASET dlaset, DLASRT dlasrt, DROT drot, XERBLA xerbla) inline
DLALSD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLALSD.DLALSD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run (string UPLO, int SMLSIZ, int N, int NRHS, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] B, int offset_b, int LDB, double RCOND, ref int RANK, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLALSD uses the singular value decomposition of A to solve the least squares problem of finding X to minimize the Euclidean norm of each column of A*X-B, where A is N-by-N upper bidiagonal, and X and B are N-by-NRHS. The solution X overwrites B.
The singular values of A smaller than RCOND times the largest singular value are treated as zero in solving the least squares problem; in this case a minimum norm solution is returned. The actual singular values are returned in D in ascending order.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray XMP, Cray YMP, Cray C 90, or Cray 2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': D and E define an upper bidiagonal matrix. = 'L': D and E define a lower bidiagonal matrix. /param>
Parameters
SMLSIZ (input) INTEGER The maximum size of the subproblems at the bottom of the computation tree. /param>
Parameters
N (input) INTEGER The dimension of the bidiagonal matrix. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of columns of B. NRHS must be at least 1. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry D contains the main diagonal of the bidiagonal matrix. On exit, if INFO = 0, D contains its singular values. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) Contains the super-diagonal entries of the bidiagonal matrix. On exit, E has been destroyed. /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On input, B contains the right hand sides of the least squares problem. On output, B contains the solution X. /param>
Parameters
LDB (input) INTEGER The leading dimension of B in the calling subprogram. LDB must be at least max(1,N). /param>
Parameters
RCOND (input) DOUBLE PRECISION The singular values of A less than or equal to RCOND times the largest singular value are treated as zero in solving the least squares problem. If RCOND is negative, machine precision is used instead. For example, if diag(S)*X=B were the least squares problem, where diag(S) is a diagonal matrix of singular values, the solution would be X(i) = B(i) / S(i) if S(i) is greater than RCOND*max(S), and X(i) = 0 if S(i) is less than or equal to RCOND*max(S). /param>
Parameters
RANK (output) INTEGER The number of singular values of A greater than RCOND times the largest singular value. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension at least (9*N + 2*N*SMLSIZ + 8*N*NLVL + N*NRHS + (SMLSIZ+1)**2), where NLVL = max(0, INT(log_2 (N/(SMLSIZ+1))) + 1). /param>
Parameters
IWORK (workspace) INTEGER array, dimension at least (3*N*NLVL + 11*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: The algorithm failed to compute an singular value while working on the submatrix lying in rows and columns INFO/(N+1) through MOD(INFO,N+1). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLALSD.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLALSD.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
Member Data Documentation
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLALSD._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlamch private
_dlanst
DLANST DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlanst private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLALSD._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLALSD._dgemm private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlacpy private
_dlalsa
DLALSA DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlalsa private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlartg private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlascl private
_dlasda
DLASDA DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlasda private
_dlasdq
DLASDQ DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlasdq private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlaset private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DLALSD._dlasrt private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLALSD._drot private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLALSD._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLALSD.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLALSD.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLALSD.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlalsd.cs