Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.BinomialDistribution Class Reference
Meta.Numerics.Statistics.Distributions.BinomialDistribution Class Reference
Represents a discrete binomial distribution.
Public Member Functions
BinomialDistribution (double p, int n)
Initializes a new binomial distribution.
override double ProbabilityMass (int k)
Returns the probability of the obtaining the given value.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
override double LeftExclusiveProbability (int k)
Computes the probability of obtaining a value less than the given value.
override double RightExclusiveProbability (int k)
Computes the probability of obtaining a value greater than the given value.
override int InverseLeftProbability (double P)
Computes the value corresponding to the given percentile.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
virtual double LeftInclusiveProbability (int k)
Computes the probability of obtaining a value less than or equal to the given value.
virtual double ExpectationValue (Func< int, double > f)
Computes the expectation value of an artibrary function.
override double Moment (int r)
Gets a raw moment of the distribution.
override double MomentAboutMean (int r)
Gets a central moment of the distribution.
virtual int GetRandomValue (Random rng)
Produces a random integer drawn from the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override int Minimum [get]
override int Maximum [get]
override double Mean [get]
override double Variance [get]
override double Skewness [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
abstract int Minimum [get]
Gets the smallest value in the distribution.
abstract int Maximum [get]
Gets the largest value in the distribution.
override double Mean [get]
Gets the mean of the distribution.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
readonly int n
readonly double p
readonly double q
Detailed Description
Represents a discrete binomial distribution.
The binomial distribution gives the probability of obtaining k successes in n independent Bernoulli trials in which the probability of success in each trial is p.
For a single trial, the binomial distribution reduces to a Bernoulli distribution (BernoulliDistribution).
The test statistic for a sign test (Sample.SignTest) is distributed according to the Bernoulli distribution.
Constructor & Destructor Documentation
BinomialDistribution()
Meta.Numerics.Statistics.Distributions.BinomialDistribution.BinomialDistribution (double p, int n) inline
Initializes a new binomial distribution.
Parameters
p The probability of the success in a single trial, which must lie between zero and one.
n The number of trials, which must be positive.
References Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, Meta.Numerics.Statistics.Distributions.BinomialDistribution.p, and Meta.Numerics.Statistics.Distributions.BinomialDistribution.q.
Member Function Documentation
ProbabilityMass()
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.ProbabilityMass (int k) inline virtual
Returns the probability of the obtaining the given value.
Implements Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, Meta.Numerics.Statistics.Distributions.BinomialDistribution.p, Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.BinomialDistribution.q.
Moment()
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Implements Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), and Meta.Numerics.MoreMath.Pow().
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, Meta.Numerics.Statistics.Distributions.BinomialDistribution.p, and Meta.Numerics.Statistics.Distributions.BinomialDistribution.q.
LeftExclusiveProbability()
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.LeftExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than the given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, and Meta.Numerics.Statistics.Distributions.BinomialDistribution.q.
RightExclusiveProbability()
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.RightExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value greater than the given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedMath.Beta(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, and Meta.Numerics.Statistics.Distributions.BinomialDistribution.p.
InverseLeftProbability()
override int Meta.Numerics.Statistics.Distributions.BinomialDistribution.InverseLeftProbability (double P) inline virtual
Computes the value corresponding to the given percentile.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficients(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.n, Meta.Numerics.Statistics.Distributions.BinomialDistribution.p, Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.BinomialDistribution.q.
Member Data Documentation
n
readonly int Meta.Numerics.Statistics.Distributions.BinomialDistribution.n private
Referenced by Meta.Numerics.Statistics.Distributions.BinomialDistribution.BinomialDistribution(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.ProbabilityMass(), and Meta.Numerics.Statistics.Distributions.BinomialDistribution.RightExclusiveProbability().
p
readonly double Meta.Numerics.Statistics.Distributions.BinomialDistribution.p private
Referenced by Meta.Numerics.Statistics.Distributions.BinomialDistribution.BinomialDistribution(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.ProbabilityMass(), and Meta.Numerics.Statistics.Distributions.BinomialDistribution.RightExclusiveProbability().
q
readonly double Meta.Numerics.Statistics.Distributions.BinomialDistribution.q private
Referenced by Meta.Numerics.Statistics.Distributions.BinomialDistribution.BinomialDistribution(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.MomentAboutMean(), and Meta.Numerics.Statistics.Distributions.BinomialDistribution.ProbabilityMass().
Property Documentation
Minimum
override int Meta.Numerics.Statistics.Distributions.BinomialDistribution.Minimum get
Maximum
override int Meta.Numerics.Statistics.Distributions.BinomialDistribution.Maximum get
Mean
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.Mean get
Variance
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.Variance get
Skewness
override double Meta.Numerics.Statistics.Distributions.BinomialDistribution.Skewness get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/BinomialDistribution.cs