Doc: IGLib EXTENDED: AForge.Imaging.Formats.FITSCodec Class Reference
AForge.Imaging.Formats.FITSCodec Class Reference
FITS image format decoder.
Public Member Functions
Bitmap DecodeSingleFrame (Stream stream)
Decode first frame of FITS image.
int Open (Stream stream)
Open specified stream.
Bitmap DecodeFrame (int frameIndex, out ImageInfo imageInfo)
Decode specified frame.
void Close ()
Close decoding of previously opened stream.
Private Member Functions
FITSImageInfo ReadHeader (Stream stream)
unsafe Bitmap ReadImageFrame (Stream stream, FITSImageInfo imageInfo)
int ExtractIntegerValue (string strValue)
string ExtractStringValue (string strValue)
Private Attributes
Stream stream = null
FITSImageInfo imageInfo = null
long dataPosition = 0
Detailed Description
FITS image format decoder.
The FITS (an acronym derived from "Flexible Image Transport System") format is an astronomical image and table format created and supported by NASA. FITS is the most commonly used in astronomy and is designed specifically for scientific data. Different astronomical organizations keep their images acquired using telescopes and other equipment in FITS format.
<note>The class extracts image frames only from the main data section of FITS file. 2D (single frame) and 3D (series of frames) data structures are supported.</note>
<note>During image reading/parsing, its data are scaled using minimum and maximum values of the source image data. FITS tags are not used for this purpose - data are scaled from the [min, max] range found to the range of supported image format ([0, 255] for 8 bpp grayscale or [0, 65535] for 16 bpp grayscale image).</note>
Member Function Documentation
DecodeSingleFrame()
Bitmap AForge.Imaging.Formats.FITSCodec.DecodeSingleFrame (Stream stream) inline
Decode first frame of FITS image.
Parameters
stream Source stream, which contains encoded image.
Returns
Returns decoded image frame.
Exceptions
FormatException Not a FITS image format.
NotSupportedException Format of the FITS image is not supported.
ArgumentException The stream contains invalid (broken) FITS image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.FITSCodec.imageInfo, AForge.Imaging.Formats.FITSCodec.ReadHeader(), AForge.Imaging.Formats.FITSCodec.ReadImageFrame(), AForge.Imaging.Formats.FITSCodec.stream, and AForge.Imaging.Formats.ImageInfo.TotalFrames.
Open()
int AForge.Imaging.Formats.FITSCodec.Open (Stream stream) inline
Open specified stream.
Parameters
stream Stream to open.
Returns
Returns number of images found in the specified stream.
Exceptions
FormatException Not a FITS image format.
NotSupportedException Format of the FITS image is not supported.
ArgumentException The stream contains invalid (broken) FITS image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.FITSCodec.Close(), AForge.Imaging.Formats.FITSCodec.imageInfo, AForge.Imaging.Formats.FITSCodec.ReadHeader(), AForge.Imaging.Formats.FITSCodec.stream, and AForge.Imaging.Formats.ImageInfo.TotalFrames.
DecodeFrame()
Bitmap AForge.Imaging.Formats.FITSCodec.DecodeFrame (int frameIndex, out ImageInfo imageInfo) inline
Decode specified frame.
Parameters
frameIndex Image frame to decode.
imageInfo Receives information about decoded frame.
Returns
Returns decoded frame.
Exceptions
NullReferenceException No image stream was opened previously.
ArgumentOutOfRangeException Stream does not contain frame with specified index.
ArgumentException The stream contains invalid (broken) FITS image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.FITSImageInfo.Clone(), AForge.Imaging.Formats.FITSCodec.dataPosition, AForge.Imaging.Formats.ImageInfo.FrameIndex, AForge.Imaging.Formats.FITSCodec.imageInfo, AForge.Imaging.Formats.FITSCodec.ReadImageFrame(), and AForge.Imaging.Formats.FITSCodec.stream.
Close()
void AForge.Imaging.Formats.FITSCodec.Close () inline
Close decoding of previously opened stream.
The method does not close stream itself, but just closes decoding cleaning all associated data with it.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.FITSCodec.imageInfo, and AForge.Imaging.Formats.FITSCodec.stream.
Referenced by AForge.Imaging.Formats.FITSCodec.Open().
ReadHeader()
FITSImageInfo AForge.Imaging.Formats.FITSCodec.ReadHeader (Stream stream) inline private
References AForge.Imaging.Formats.ImageInfo.BitsPerPixel, AForge.Imaging.Formats.FITSCodec.ExtractIntegerValue(), AForge.Imaging.Formats.FITSCodec.ExtractStringValue(), AForge.Imaging.Formats.ImageInfo.Height, AForge.Imaging.Formats.FITSCodec.imageInfo, AForge.Imaging.Formats.FITSImageInfo.Instrument, AForge.Imaging.Formats.FITSImageInfo.MaxDataValue, AForge.Imaging.Formats.FITSImageInfo.MinDataValue, AForge.Imaging.Formats.FITSImageInfo.Object, AForge.Imaging.Formats.FITSImageInfo.Observer, AForge.Imaging.Formats.FITSImageInfo.OriginalBitsPerPixl, AForge.Imaging.Formats.FITSCodec.stream, AForge.Imaging.Formats.FITSImageInfo.Telescope, AForge.Imaging.Formats.ImageInfo.TotalFrames, and AForge.Imaging.Formats.ImageInfo.Width.
Referenced by AForge.Imaging.Formats.FITSCodec.DecodeSingleFrame(), and AForge.Imaging.Formats.FITSCodec.Open().
ReadImageFrame()
unsafe Bitmap AForge.Imaging.Formats.FITSCodec.ReadImageFrame (Stream stream, FITSImageInfo imageInfo) inline private
References AForge.Imaging.Formats.ImageInfo.BitsPerPixel, AForge.Imaging.Formats.ImageInfo.Height, AForge.Imaging.Formats.FITSCodec.imageInfo, AForge.Imaging.Formats.FITSImageInfo.MaxDataValue, AForge.Imaging.Formats.FITSImageInfo.MinDataValue, AForge.Imaging.Formats.FITSImageInfo.OriginalBitsPerPixl, AForge.Math.Geometry.Rectangle, AForge.Imaging.Formats.FITSCodec.stream, and AForge.Imaging.Formats.ImageInfo.Width.
Referenced by AForge.Imaging.Formats.FITSCodec.DecodeFrame(), and AForge.Imaging.Formats.FITSCodec.DecodeSingleFrame().
ExtractIntegerValue()
int AForge.Imaging.Formats.FITSCodec.ExtractIntegerValue (string strValue) inline private
Referenced by AForge.Imaging.Formats.FITSCodec.ReadHeader().
ExtractStringValue()
string AForge.Imaging.Formats.FITSCodec.ExtractStringValue (string strValue) inline private
Referenced by AForge.Imaging.Formats.FITSCodec.ReadHeader().
Member Data Documentation
stream
Stream AForge.Imaging.Formats.FITSCodec.stream = null private
Referenced by AForge.Imaging.Formats.FITSCodec.Close(), AForge.Imaging.Formats.FITSCodec.DecodeFrame(), AForge.Imaging.Formats.FITSCodec.DecodeSingleFrame(), AForge.Imaging.Formats.FITSCodec.Open(), AForge.Imaging.Formats.FITSCodec.ReadHeader(), and AForge.Imaging.Formats.FITSCodec.ReadImageFrame().
imageInfo
FITSImageInfo AForge.Imaging.Formats.FITSCodec.imageInfo = null private
Referenced by AForge.Imaging.Formats.FITSCodec.Close(), AForge.Imaging.Formats.FITSCodec.DecodeFrame(), AForge.Imaging.Formats.FITSCodec.DecodeSingleFrame(), AForge.Imaging.Formats.FITSCodec.Open(), AForge.Imaging.Formats.FITSCodec.ReadHeader(), and AForge.Imaging.Formats.FITSCodec.ReadImageFrame().
dataPosition
long AForge.Imaging.Formats.FITSCodec.dataPosition = 0 private
Referenced by AForge.Imaging.Formats.FITSCodec.DecodeFrame().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging.Formats/FITSCodec.cs