Doc: IGLib EXTENDED: NUnit.Framework.Attributes.CategoryAttributeTests Class Reference
NUnit.Framework.Attributes.CategoryAttributeTests Class Reference
Summary description for CategoryAttributeTests.
Public Member Functions
void CreateFixture ()
void CategoryOnFixture ()
void CategoryOnTestMethod ()
void CanDeriveFromCategoryAttribute ()
void DerivedCategoryMayBeInherited ()
void CanSpecifyOnMethodAndTestCase ()
void TestWithInvalidCategoryNameIsNotRunnable ()
Private Attributes
TestSuite fixture
Detailed Description
Summary description for CategoryAttributeTests.
Member Function Documentation
CreateFixture()
void NUnit.Framework.Attributes.CategoryAttributeTests.CreateFixture () inline
References NUnit.Framework.Attributes.CategoryAttributeTests.fixture, and NUnit.TestUtilities.TestBuilder.MakeFixture().
CategoryOnFixture()
void NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnFixture () inline
References NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Contains.Item(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Assert.That().
CategoryOnTestMethod()
void NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnTestMethod () inline
References NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Contains.Item(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
CanDeriveFromCategoryAttribute()
void NUnit.Framework.Attributes.CategoryAttributeTests.CanDeriveFromCategoryAttribute () inline
References NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Contains.Item(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
DerivedCategoryMayBeInherited()
void NUnit.Framework.Attributes.CategoryAttributeTests.DerivedCategoryMayBeInherited () inline
References NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Contains.Item(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Assert.That().
CanSpecifyOnMethodAndTestCase()
void NUnit.Framework.Attributes.CategoryAttributeTests.CanSpecifyOnMethodAndTestCase () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Contains.Item(), NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
TestWithInvalidCategoryNameIsNotRunnable()
void NUnit.Framework.Attributes.CategoryAttributeTests.TestWithInvalidCategoryNameIsNotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.CategoryAttributeTests.fixture, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
Member Data Documentation
fixture
TestSuite NUnit.Framework.Attributes.CategoryAttributeTests.fixture private
Referenced by NUnit.Framework.Attributes.CategoryAttributeTests.CanDeriveFromCategoryAttribute(), NUnit.Framework.Attributes.CategoryAttributeTests.CanSpecifyOnMethodAndTestCase(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnFixture(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnTestMethod(), NUnit.Framework.Attributes.CategoryAttributeTests.CreateFixture(), NUnit.Framework.Attributes.CategoryAttributeTests.DerivedCategoryMayBeInherited(), and NUnit.Framework.Attributes.CategoryAttributeTests.TestWithInvalidCategoryNameIsNotRunnable().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/CategoryAttributeTests.cs