Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLABRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLABRD Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLABRD (DGEMV dgemv, DLARFG dlarfg, DSCAL dscal)
DLABRD ()
void Run (int M, int N, int NB, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] X, int offset_x, int LDX, ref double[] Y, int offset_y, int LDY)
Private Attributes
DGEMV _dgemv
DLARFG _dlarfg
DSCAL _dscal
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLABRD reduces the first NB rows and columns of a real general m by n matrix A to upper or lower bidiagonal form by an orthogonal transformation Q' * A * P, and returns the matrices X and Y which are needed to apply the transformation to the unreduced part of A.
If m .GE. n, A is reduced to upper bidiagonal form; if m .LT. n, to lower bidiagonal form.
This is an auxiliary routine called by DGEBRD
/summary>
Constructor & Destructor Documentation
DLABRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLABRD.DLABRD (DGEMV dgemv, DLARFG dlarfg, DSCAL dscal) inline
DLABRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLABRD.DLABRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run (int M, int N, int NB, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] X, int offset_x, int LDX, ref double[] Y, int offset_y, int LDY) inline
Purpose
DLABRD reduces the first NB rows and columns of a real general m by n matrix A to upper or lower bidiagonal form by an orthogonal transformation Q' * A * P, and returns the matrices X and Y which are needed to apply the transformation to the unreduced part of A.
If m .GE. n, A is reduced to upper bidiagonal form; if m .LT. n, to lower bidiagonal form.
This is an auxiliary routine called by DGEBRD
/summary>
Parameters
M (input) INTEGER The number of rows in the matrix A. /param>
Parameters
N (input) INTEGER The number of columns in the matrix A. /param>
Parameters
NB (input) INTEGER The number of leading rows and columns of A to be reduced. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the m by n general matrix to be reduced. On exit, the first NB rows and columns of the matrix are overwritten; the rest of the array is unchanged. If m .GE. n, elements on and below the diagonal in the first NB columns, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors; and elements above the diagonal in the first NB rows, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors. If m .LT. n, elements below the diagonal in the first NB columns, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors, and elements on and above the diagonal in the first NB rows, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (NB) The diagonal elements of the first NB rows and columns of the reduced matrix. D(i) = A(i,i). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (NB) The off-diagonal elements of the first NB rows and columns of the reduced matrix. /param>
Parameters
TAUQ (output) DOUBLE PRECISION array dimension (NB) The scalar factors of the elementary reflectors which represent the orthogonal matrix Q. See Further Details. /param>
Parameters
TAUP (output) DOUBLE PRECISION array, dimension (NB) The scalar factors of the elementary reflectors which represent the orthogonal matrix P. See Further Details. /param>
Parameters
X (output) DOUBLE PRECISION array, dimension (LDX,NB) The m-by-nb matrix X required to update the unreduced part of A. /param>
Parameters
LDX (input) INTEGER The leading dimension of the array X. LDX .GE. M. /param>
Parameters
Y (output) DOUBLE PRECISION array, dimension (LDY,NB) The n-by-nb matrix Y required to update the unreduced part of A. /param>
Parameters
LDY (input) INTEGER The leading dimension of the array Y. LDY .GE. N. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLABRD.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLABRD.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run().
Member Data Documentation
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLABRD._dgemv private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLABRD._dlarfg private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLABRD._dscal private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLABRD.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLABRD.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlabrd.cs