Doc: IGLib EXTENDED: IG.Forms.InputParameterSelectorMinMax Class Reference
IG.Forms.InputParameterSelectorMinMax Class Reference
Selection of parameter to be varied, together with bounds - for parametric tests.
Public Member Functions
InputParameterSelectorMinMax ()
void UpdateDataDefinition ()
Updates data with accordance to data definitions in DataDefinition.
void SetSelectedParameterId (int id)
Replacement for the SelectedParameterId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
InputParameterSelectorMinMax ()
void UpdateDataDefinition ()
Updates data with accordance to data definitions in DataDefinition.
void SetSelectedParameterId (int id)
Replacement for the SelectedParameterId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
InputParameterSelectorMinMax ()
void UpdateDataDefinition ()
Updates data with accordance to data definitions in DataDefinition.
void SetSelectedParameterId (int id)
Replacement for the SelectedParameterId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
Protected Member Functions
void OnSelectedParameterIdChanged (int oldId, int newId)
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMinChanged (double oldValue, double newValue)
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMaxChanged (double oldValue, double newValue)
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnSelectedParameterIdChanged (int oldId, int newId)
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMinChanged (double oldValue, double newValue)
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMaxChanged (double oldValue, double newValue)
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnSelectedParameterIdChanged (int oldId, int newId)
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMinChanged (double oldValue, double newValue)
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
void OnSelectedParameterMaxChanged (double oldValue, double newValue)
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
double[] _minValues
double[] _maxValues
int _selectedParameterId = 0
Properties
InputOutputDataDefiniton DataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
string TitleParameterSelection [get, set]
String that appears in the label above parameter selector (title of parameter selection).
int NumInputParameters [get, set]
Gets number of input parameters.
int NumOutputValues [get, set]
Gets number of output values.
double[] MinValues [get, protected set]
Minimal values of input parameters, obtained from DataDefinition.
double[] MaxValues [get, protected set]
int SelectedParameterId [get, protected set]
Sequential number of the selected parameter as specified by the user (usually through GUI).
double SelectedParameterMin [get]
Minimal value of the selected parameter.
double SelectedParameterMax [get]
Maximal value of the selected parameter as specified by the user.
Events
System.EventHandler< IndexChangeEventArgs > SelectedParameterIdChanged
Occurs when selected input parameter ID is changed.
System.EventHandler< ValueChangeEventArgs > SelectedParameterMinChanged
Occurs when selected input parameter's minimal value is changed by the user (but only when it is changed through GUI).
System.EventHandler< ValueChangeEventArgs > SelectedParameterMaxChanged
Occurs when selected input parameter's maximal value is changed by the user (but only when it is changed through GUI).
Private Member Functions
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void txtMinValue_TextChanged (object sender, EventArgs e)
void txtMaxValue_TextChanged (object sender, EventArgs e)
void txtMinValue_Validated (object sender, EventArgs e)
void txtMaxValue_Validated (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void txtMinValue_TextChanged (object sender, EventArgs e)
void txtMaxValue_TextChanged (object sender, EventArgs e)
void txtMinValue_Validated (object sender, EventArgs e)
void txtMaxValue_Validated (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void txtMinValue_TextChanged (object sender, EventArgs e)
void txtMaxValue_TextChanged (object sender, EventArgs e)
void txtMinValue_Validated (object sender, EventArgs e)
void txtMaxValue_Validated (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _dataDefinition
int _numInputParameters = 2
int _numOutputValues = 2
double _previousMinValue
double _newMinvalue
double _previousMaxValue
double _newMaxValue
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.NumericUpDown txtParamNum
System.Windows.Forms.TextBox txtMaxValue
System.Windows.Forms.TextBox txtMinValue
System.Windows.Forms.ComboBox comboBoxSelection
System.Windows.Forms.Label lblMax
System.Windows.Forms.Label lblParamNum
System.Windows.Forms.Label lblFrom
System.Windows.Forms.Label lblSelectParameter
System.Windows.Forms.Panel pnlMain
System.Windows.Forms.Button btnIncrease
System.Windows.Forms.Button btnDecrease
System.Windows.Forms.ContextMenuStrip contextMenuStrip1
System.Windows.Forms.ToolStripMenuItem menuSummary
Detailed Description
Selection of parameter to be varied, together with bounds - for parametric tests.
$A Igor Apr13 March16;
Constructor & Destructor Documentation
InputParameterSelectorMinMax() [1/3]
IG.Forms.InputParameterSelectorMinMax.InputParameterSelectorMinMax () inline
References IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
InputParameterSelectorMinMax() [2/3]
IG.Forms.InputParameterSelectorMinMax.InputParameterSelectorMinMax () inline
References IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
InputParameterSelectorMinMax() [3/3]
IG.Forms.InputParameterSelectorMinMax.InputParameterSelectorMinMax () inline
References IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
Member Function Documentation
UpdateDataDefinition() [1/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition () inline
Updates data with accordance to data definitions in DataDefinition.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
OnSelectedParameterIdChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterIdChanged (int oldId, int newId) inline protected
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old parameter Id.
newId New parameter Id.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged.
OnSelectedParameterMinChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old minimal parameter value.
newValue New minimal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated().
OnSelectedParameterMaxChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old maximal parameter value.
newValue New maximal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged.
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated().
SetSelectedParameterId() [1/3]
void IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId (int id) inline
Replacement for the SelectedParameterId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
Referenced by IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged().
UpdateSelectedParameterIdDependencies() [1/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMax, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMin, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
Referenced by IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition().
comboBoxSelection_SelectedIndexChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtParamNum_ValueChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtMinValue_TextChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtMaxValue_TextChanged() [1/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtMinValue_Validated() [1/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMinvalue, IG.Forms.InputParameterSelectorMinMax._previousMinValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMinValue.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtMaxValue_Validated() [1/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMaxValue, IG.Forms.InputParameterSelectorMinMax._previousMaxValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMaxValue.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
btnDecrease_Click() [1/3]
void IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
btnIncrease_Click() [1/3]
void IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
menuSummary_Click() [1/3]
void IG.Forms.InputParameterSelectorMinMax.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
Dispose() [1/3]
override void IG.Forms.InputParameterSelectorMinMax.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParameterSelectorMinMax.components.
InitializeComponent() [1/3]
void IG.Forms.InputParameterSelectorMinMax.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParameterSelectorMinMax.btnDecrease, IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click(), IG.Forms.InputParameterSelectorMinMax.btnIncrease, IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click(), IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged(), IG.Forms.InputParameterSelectorMinMax.components, IG.Forms.InputParameterSelectorMinMax.contextMenuStrip1, IG.Forms.InputParameterSelectorMinMax.lblFrom, IG.Forms.InputParameterSelectorMinMax.lblMax, IG.Forms.InputParameterSelectorMinMax.lblParamNum, IG.Forms.InputParameterSelectorMinMax.lblSelectParameter, IG.Forms.InputParameterSelectorMinMax.menuSummary, IG.Forms.InputParameterSelectorMinMax.pnlMain, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtMinValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtParamNum, and IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged().
Referenced by IG.Forms.InputParameterSelectorMinMax.InputParameterSelectorMinMax().
UpdateDataDefinition() [2/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition () inline
Updates data with accordance to data definitions in DataDefinition.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
OnSelectedParameterIdChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterIdChanged (int oldId, int newId) inline protected
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old parameter Id.
newId New parameter Id.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged.
OnSelectedParameterMinChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old minimal parameter value.
newValue New minimal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
OnSelectedParameterMaxChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old maximal parameter value.
newValue New maximal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged.
SetSelectedParameterId() [2/3]
void IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId (int id) inline
Replacement for the SelectedParameterId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
UpdateSelectedParameterIdDependencies() [2/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMax, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMin, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
comboBoxSelection_SelectedIndexChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
txtParamNum_ValueChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
txtMinValue_TextChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged (object sender, EventArgs e) inline private
txtMaxValue_TextChanged() [2/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged (object sender, EventArgs e) inline private
txtMinValue_Validated() [2/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMinvalue, IG.Forms.InputParameterSelectorMinMax._previousMinValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMinValue.
txtMaxValue_Validated() [2/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMaxValue, IG.Forms.InputParameterSelectorMinMax._previousMaxValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMaxValue.
btnDecrease_Click() [2/3]
void IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
btnIncrease_Click() [2/3]
void IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
menuSummary_Click() [2/3]
void IG.Forms.InputParameterSelectorMinMax.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
Dispose() [2/3]
override void IG.Forms.InputParameterSelectorMinMax.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParameterSelectorMinMax.components.
InitializeComponent() [2/3]
void IG.Forms.InputParameterSelectorMinMax.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParameterSelectorMinMax.btnDecrease, IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click(), IG.Forms.InputParameterSelectorMinMax.btnIncrease, IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click(), IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged(), IG.Forms.InputParameterSelectorMinMax.components, IG.Forms.InputParameterSelectorMinMax.contextMenuStrip1, IG.Forms.InputParameterSelectorMinMax.lblFrom, IG.Forms.InputParameterSelectorMinMax.lblMax, IG.Forms.InputParameterSelectorMinMax.lblParamNum, IG.Forms.InputParameterSelectorMinMax.lblSelectParameter, IG.Forms.InputParameterSelectorMinMax.menuSummary, IG.Forms.InputParameterSelectorMinMax.pnlMain, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtMinValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtParamNum, and IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged().
UpdateDataDefinition() [3/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition () inline
Updates data with accordance to data definitions in DataDefinition.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
OnSelectedParameterIdChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterIdChanged (int oldId, int newId) inline protected
Raises the SelectedParameterIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old parameter Id.
newId New parameter Id.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged.
OnSelectedParameterMinChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMinChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old minimal parameter value.
newValue New minimal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
OnSelectedParameterMaxChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged (double oldValue, double newValue) inline protected
Raises the SelectedParameterMaxChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldValue Old maximal parameter value.
newValue New maximal parameter value.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged.
SetSelectedParameterId() [3/3]
void IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId (int id) inline
Replacement for the SelectedParameterId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
UpdateSelectedParameterIdDependencies() [3/3]
void IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMax, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMin, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
comboBoxSelection_SelectedIndexChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
txtParamNum_ValueChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtParamNum.
txtMinValue_TextChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged (object sender, EventArgs e) inline private
txtMaxValue_TextChanged() [3/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged (object sender, EventArgs e) inline private
txtMinValue_Validated() [3/3]
void IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMinvalue, IG.Forms.InputParameterSelectorMinMax._previousMinValue, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMinValue.
txtMaxValue_Validated() [3/3]
void IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax._newMaxValue, IG.Forms.InputParameterSelectorMinMax._previousMaxValue, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, and IG.Forms.InputParameterSelectorMinMax.txtMaxValue.
btnDecrease_Click() [3/3]
void IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
btnIncrease_Click() [3/3]
void IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.SelectedParameterId.
menuSummary_Click() [3/3]
void IG.Forms.InputParameterSelectorMinMax.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.InputParameterSelectorMinMax.MaxValues, IG.Forms.InputParameterSelectorMinMax.MinValues, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, and IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged.
Dispose() [3/3]
override void IG.Forms.InputParameterSelectorMinMax.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParameterSelectorMinMax.components.
InitializeComponent() [3/3]
void IG.Forms.InputParameterSelectorMinMax.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParameterSelectorMinMax.btnDecrease, IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click(), IG.Forms.InputParameterSelectorMinMax.btnIncrease, IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click(), IG.Forms.InputParameterSelectorMinMax.comboBoxSelection, IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged(), IG.Forms.InputParameterSelectorMinMax.components, IG.Forms.InputParameterSelectorMinMax.contextMenuStrip1, IG.Forms.InputParameterSelectorMinMax.lblFrom, IG.Forms.InputParameterSelectorMinMax.lblMax, IG.Forms.InputParameterSelectorMinMax.lblParamNum, IG.Forms.InputParameterSelectorMinMax.lblSelectParameter, IG.Forms.InputParameterSelectorMinMax.menuSummary, IG.Forms.InputParameterSelectorMinMax.pnlMain, IG.Forms.InputParameterSelectorMinMax.txtMaxValue, IG.Forms.InputParameterSelectorMinMax.txtMaxValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtMinValue, IG.Forms.InputParameterSelectorMinMax.txtMinValue_TextChanged(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtParamNum, and IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged().
Member Data Documentation
_dataDefinition
InputOutputDataDefiniton IG.Forms.InputParameterSelectorMinMax._dataDefinition private
_numInputParameters
int IG.Forms.InputParameterSelectorMinMax._numInputParameters = 2 private
_numOutputValues
int IG.Forms.InputParameterSelectorMinMax._numOutputValues = 2 private
_minValues
double [] IG.Forms.InputParameterSelectorMinMax._minValues protected
_maxValues
double [] IG.Forms.InputParameterSelectorMinMax._maxValues protected
_selectedParameterId
int IG.Forms.InputParameterSelectorMinMax._selectedParameterId = 0 protected
_previousMinValue
double IG.Forms.InputParameterSelectorMinMax._previousMinValue private
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated().
_newMinvalue
double IG.Forms.InputParameterSelectorMinMax._newMinvalue private
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated().
_previousMaxValue
double IG.Forms.InputParameterSelectorMinMax._previousMaxValue private
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated().
_newMaxValue
double IG.Forms.InputParameterSelectorMinMax._newMaxValue private
Referenced by IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated().
components
System ComponentModel IContainer IG.Forms.InputParameterSelectorMinMax.components = null private
Required designer variable.
Referenced by IG.Forms.InputParameterSelectorMinMax.Dispose(), and IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
txtParamNum
System Windows Forms NumericUpDown IG.Forms.InputParameterSelectorMinMax.txtParamNum private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
txtMaxValue
System Windows Forms TextBox IG.Forms.InputParameterSelectorMinMax.txtMaxValue private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
txtMinValue
System Windows Forms TextBox IG.Forms.InputParameterSelectorMinMax.txtMinValue private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
comboBoxSelection
System Windows Forms ComboBox IG.Forms.InputParameterSelectorMinMax.comboBoxSelection private
Referenced by IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged(), IG.Forms.InputParameterSelectorMinMax.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
lblMax
System Windows Forms Label IG.Forms.InputParameterSelectorMinMax.lblMax private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
lblParamNum
System Windows Forms Label IG.Forms.InputParameterSelectorMinMax.lblParamNum private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
lblFrom
System Windows Forms Label IG.Forms.InputParameterSelectorMinMax.lblFrom private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
lblSelectParameter
System Windows Forms Label IG.Forms.InputParameterSelectorMinMax.lblSelectParameter private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
pnlMain
System Windows Forms Panel IG.Forms.InputParameterSelectorMinMax.pnlMain private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
btnIncrease
System Windows Forms Button IG.Forms.InputParameterSelectorMinMax.btnIncrease private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
btnDecrease
System Windows Forms Button IG.Forms.InputParameterSelectorMinMax.btnDecrease private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
contextMenuStrip1
System Windows Forms ContextMenuStrip IG.Forms.InputParameterSelectorMinMax.contextMenuStrip1 private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
menuSummary
System Windows Forms ToolStripMenuItem IG.Forms.InputParameterSelectorMinMax.menuSummary private
Referenced by IG.Forms.InputParameterSelectorMinMax.InitializeComponent().
Property Documentation
DataDefinition
InputOutputDataDefiniton IG.Forms.InputParameterSelectorMinMax.DataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition().
TitleParameterSelection
string IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection get set
String that appears in the label above parameter selector (title of parameter selection).
This can be used to change the title in the case there are more than one input parameters selected, or a customized title is desired.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
NumInputParameters
int IG.Forms.InputParameterSelectorMinMax.NumInputParameters get set
Gets number of input parameters.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition().
NumOutputValues
int IG.Forms.InputParameterSelectorMinMax.NumOutputValues get set
Gets number of output values.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition().
MinValues
double [] IG.Forms.InputParameterSelectorMinMax.MinValues get protected set
Minimal values of input parameters, obtained from DataDefinition.
Referenced by IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
MaxValues
double [] IG.Forms.InputParameterSelectorMinMax.MaxValues get protected set
Referenced by IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), IG.Forms.InputParameterSelectorMinMax.UpdateDataDefinition(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
SelectedParameterId
int IG.Forms.InputParameterSelectorMinMax.SelectedParameterId get protected set
Sequential number of the selected parameter as specified by the user (usually through GUI).
Referenced by IG.Forms.InputParameterSelectorMinMax.btnDecrease_Click(), IG.Forms.InputParameterSelectorMinMax.btnIncrease_Click(), IG.Forms.InputParameterSelectorMinMax.comboBoxSelection_SelectedIndexChanged(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), IG.Forms.InputParameterSelectorMinMax.txtMaxValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtMinValue_Validated(), IG.Forms.InputParameterSelectorMinMax.txtParamNum_ValueChanged(), and IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
SelectedParameterMin
double IG.Forms.InputParameterSelectorMinMax.SelectedParameterMin get
Minimal value of the selected parameter.
Referenced by IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
SelectedParameterMax
double IG.Forms.InputParameterSelectorMinMax.SelectedParameterMax get
Maximal value of the selected parameter as specified by the user.
Referenced by IG.Forms.InputParameterSelectorMinMax.UpdateSelectedParameterIdDependencies().
Event Documentation
SelectedParameterIdChanged
System EventHandler< IndexChangeEventArgs > IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged
Occurs when selected input parameter ID is changed.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterIdChanged().
SelectedParameterMinChanged
System EventHandler< ValueChangeEventArgs > IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged
Occurs when selected input parameter's minimal value is changed by the user (but only when it is changed through GUI).
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMinChanged().
SelectedParameterMaxChanged
System EventHandler< ValueChangeEventArgs > IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged
Occurs when selected input parameter's maximal value is changed by the user (but only when it is changed through GUI).
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), and IG.Forms.InputParameterSelectorMinMax.OnSelectedParameterMaxChanged().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/ParametricInputParameterSelectorMinMax.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/ParametricInputParameterSelectorMinMax.Designer.cs