Doc: IGLib EXTENDED: CShell.Modules.Editors.Views.EditorView Class Reference
CShell.Modules.Editors.Views.EditorView Class Reference
Interaction logic for EditorView.xaml
Public Member Functions
EditorView ()
void Comment ()
void Uncomment ()
Private Member Functions
bool IsLineCommented (DocumentLine line)
Private Attributes
CompletionWindow completionWindow
OverloadInsightWindow insightWindow
Detailed Description
Interaction logic for EditorView.xaml
Constructor & Destructor Documentation
EditorView()
CShell.Modules.Editors.Views.EditorView.EditorView () inline
Member Function Documentation
Comment()
void CShell.Modules.Editors.Views.EditorView.Comment () inline
References CShell.Modules.Editors.Views.EditorView.IsLineCommented().
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Comment().
Uncomment()
void CShell.Modules.Editors.Views.EditorView.Uncomment () inline
References CShell.Modules.Editors.Views.EditorView.IsLineCommented().
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment().
IsLineCommented()
bool CShell.Modules.Editors.Views.EditorView.IsLineCommented (DocumentLine line) inline private
Referenced by CShell.Modules.Editors.Views.EditorView.Comment(), and CShell.Modules.Editors.Views.EditorView.Uncomment().
Member Data Documentation
completionWindow
CompletionWindow CShell.Modules.Editors.Views.EditorView.completionWindow private
insightWindow
OverloadInsightWindow CShell.Modules.Editors.Views.EditorView.insightWindow private
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Editors/Views/EditorView.xaml.cs