Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack Class Reference
NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack Class Reference
ConstraintStack is a type-safe stack for holding Constraints
Public Member Functions
ConstraintStack (ConstraintBuilder builder)
Initializes a new instance of the ConstraintStack class.
void Push (IConstraint constraint)
Pushes the specified constraint. As a side effect, the constraint's Builder field is set to the ConstraintBuilder owning this stack.
IConstraint Pop ()
Pops this topmost constraint from the stack. As a side effect, the constraint's Builder field is set to null.
Properties
bool Empty [get]
Gets a value indicating whether this ConstraintStack is empty.
Private Attributes
readonly Stack< IConstraint > stack = new Stack<IConstraint>()
readonly ConstraintBuilder builder
Detailed Description
ConstraintStack is a type-safe stack for holding Constraints
Constructor & Destructor Documentation
ConstraintStack()
NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.ConstraintStack (ConstraintBuilder builder) inline
Initializes a new instance of the ConstraintStack class.
Parameters
builder The ConstraintBuilder using this stack.
References NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.builder.
Member Function Documentation
Push()
void NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Push (IConstraint constraint) inline
Pushes the specified constraint. As a side effect, the constraint's Builder field is set to the ConstraintBuilder owning this stack.
Parameters
constraint The constraint to put onto the stack
References NUnit.Framework.Constraints.IConstraint.Builder, NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.builder, and NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.stack.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append().
Pop()
IConstraint NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Pop () inline
Pops this topmost constraint from the stack. As a side effect, the constraint's Builder field is set to null.
Returns
The topmost contraint on the stack
References NUnit.Framework.Constraints.IConstraint.Builder, and NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.stack.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Resolve().
Member Data Documentation
stack
readonly Stack<IConstraint> NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.stack = new Stack<IConstraint>() private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Pop(), and NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Push().
builder
readonly ConstraintBuilder NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.builder private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.ConstraintStack(), and NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Push().
Property Documentation
Empty
bool NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Empty get
Gets a value indicating whether this ConstraintStack is empty.
true if empty; otherwise, false.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintBuilder.cs