Doc: IGLib EXTENDED: IG.Forms.HashDirControl Class Reference
IG.Forms.HashDirControl Class Reference
Public Member Functions
HashDirControl ()
HashDirControl ()
HashDirControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void ShowNotification (string title, string message, ReportType type=ReportType.Info)
void txtTitle_TextChanged (object sender, EventArgs e)
void btnLaunchNotification_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void ShowNotification (string title, string message, ReportType type=ReportType.Info)
void txtTitle_TextChanged (object sender, EventArgs e)
void btnLaunchNotification_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void ShowNotification (string title, string message, ReportType type=ReportType.Info)
void txtTitle_TextChanged (object sender, EventArgs e)
void btnLaunchNotification_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ReportType _reportType = ReportType.Info
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
IG.Forms.NotificationFrame notificationFrame
System.Windows.Forms.TextBox txtTitle
System.Windows.Forms.TextBox txtMessage
System.Windows.Forms.Button btnLaunchNotification
Constructor & Destructor Documentation
HashDirControl() [1/3]
IG.Forms.HashDirControl.HashDirControl () inline
References IG.Forms.HashDirControl.InitializeComponent().
HashDirControl() [2/3]
IG.Forms.HashDirControl.HashDirControl () inline
References IG.Forms.HashDirControl.InitializeComponent().
HashDirControl() [3/3]
IG.Forms.HashDirControl.HashDirControl () inline
References IG.Forms.HashDirControl.InitializeComponent().
Member Function Documentation
ShowNotification() [1/3]
void IG.Forms.HashDirControl.ShowNotification (string title, string message, ReportType type = ReportType.Info) inline private
References IG.Forms.HashDirControl.notificationFrame, and IG.Forms.NotificationFrame.ShowNotification().
Referenced by IG.Forms.HashDirControl.btnLaunchNotification_Click().
txtTitle_TextChanged() [1/3]
void IG.Forms.HashDirControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.HashDirControl.InitializeComponent().
btnLaunchNotification_Click() [1/3]
void IG.Forms.HashDirControl.btnLaunchNotification_Click (object sender, EventArgs e) inline private
References IG.Forms.HashDirControl._reportType, IG.Forms.HashDirControl.ShowNotification(), IG.Forms.HashDirControl.txtMessage, and IG.Forms.HashDirControl.txtTitle.
Referenced by IG.Forms.HashDirControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.HashDirControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirControl.components.
InitializeComponent() [1/3]
void IG.Forms.HashDirControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirControl.btnLaunchNotification, IG.Forms.HashDirControl.btnLaunchNotification_Click(), IG.Forms.HashDirControl.lblTitle, IG.Forms.HashDirControl.notificationFrame, IG.Forms.HashDirControl.txtMessage, IG.Forms.HashDirControl.txtTitle, and IG.Forms.HashDirControl.txtTitle_TextChanged().
Referenced by IG.Forms.HashDirControl.HashDirControl().
ShowNotification() [2/3]
void IG.Forms.HashDirControl.ShowNotification (string title, string message, ReportType type = ReportType.Info) inline private
References IG.Forms.HashDirControl.notificationFrame, and IG.Forms.NotificationFrame.ShowNotification().
txtTitle_TextChanged() [2/3]
void IG.Forms.HashDirControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
btnLaunchNotification_Click() [2/3]
void IG.Forms.HashDirControl.btnLaunchNotification_Click (object sender, EventArgs e) inline private
References IG.Forms.HashDirControl._reportType, IG.Forms.HashDirControl.ShowNotification(), IG.Forms.HashDirControl.txtMessage, and IG.Forms.HashDirControl.txtTitle.
Dispose() [2/3]
override void IG.Forms.HashDirControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirControl.components.
InitializeComponent() [2/3]
void IG.Forms.HashDirControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirControl.btnLaunchNotification, IG.Forms.HashDirControl.btnLaunchNotification_Click(), IG.Forms.HashDirControl.lblTitle, IG.Forms.HashDirControl.notificationFrame, IG.Forms.HashDirControl.txtMessage, IG.Forms.HashDirControl.txtTitle, and IG.Forms.HashDirControl.txtTitle_TextChanged().
ShowNotification() [3/3]
void IG.Forms.HashDirControl.ShowNotification (string title, string message, ReportType type = ReportType.Info) inline private
References IG.Forms.HashDirControl.notificationFrame, and IG.Forms.NotificationFrame.ShowNotification().
txtTitle_TextChanged() [3/3]
void IG.Forms.HashDirControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
btnLaunchNotification_Click() [3/3]
void IG.Forms.HashDirControl.btnLaunchNotification_Click (object sender, EventArgs e) inline private
References IG.Forms.HashDirControl._reportType, IG.Forms.HashDirControl.ShowNotification(), IG.Forms.HashDirControl.txtMessage, and IG.Forms.HashDirControl.txtTitle.
Dispose() [3/3]
override void IG.Forms.HashDirControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirControl.components.
InitializeComponent() [3/3]
void IG.Forms.HashDirControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirControl.btnLaunchNotification, IG.Forms.HashDirControl.btnLaunchNotification_Click(), IG.Forms.HashDirControl.lblTitle, IG.Forms.HashDirControl.notificationFrame, IG.Forms.HashDirControl.txtMessage, IG.Forms.HashDirControl.txtTitle, and IG.Forms.HashDirControl.txtTitle_TextChanged().
Member Data Documentation
_reportType
ReportType IG.Forms.HashDirControl._reportType = ReportType.Info private
Referenced by IG.Forms.HashDirControl.btnLaunchNotification_Click().
components
System ComponentModel IContainer IG.Forms.HashDirControl.components = null private
Required designer variable.
Referenced by IG.Forms.HashDirControl.Dispose().
lblTitle
System Windows Forms Label IG.Forms.HashDirControl.lblTitle private
Referenced by IG.Forms.HashDirControl.InitializeComponent().
notificationFrame
IG Forms NotificationFrame IG.Forms.HashDirControl.notificationFrame private
Referenced by IG.Forms.HashDirControl.InitializeComponent(), and IG.Forms.HashDirControl.ShowNotification().
txtTitle
System Windows Forms TextBox IG.Forms.HashDirControl.txtTitle private
Referenced by IG.Forms.HashDirControl.btnLaunchNotification_Click(), and IG.Forms.HashDirControl.InitializeComponent().
txtMessage
System Windows Forms TextBox IG.Forms.HashDirControl.txtMessage private
Referenced by IG.Forms.HashDirControl.btnLaunchNotification_Click(), and IG.Forms.HashDirControl.InitializeComponent().
btnLaunchNotification
System Windows Forms Button IG.Forms.HashDirControl.btnLaunchNotification private
Referenced by IG.Forms.HashDirControl.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashDirControl.cs
iglib/igforms/Utilities/Cryptography/HashDirControl.Designer.cs