Doc: IGLib EXTENDED: AForge.Imaging.Filters.EuclideanColorFiltering Class Reference
AForge.Imaging.Filters.EuclideanColorFiltering Class Reference
Euclidean color filtering.
Public Member Functions
EuclideanColorFiltering ()
Initializes a new instance of the EuclideanColorFiltering class.
EuclideanColorFiltering (RGB center, short radius)
Initializes a new instance of the EuclideanColorFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
short Radius [get, set]
RGB sphere's radius, [0, 450].
RGB CenterColor [get, set]
RGB sphere's center.
RGB FillColor [get, set]
Fill color used to fill filtered pixels.
bool FillOutside [get, set]
Determines, if pixels should be filled inside or outside specified RGB sphere.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
short radius = 100
RGB center = new RGB(255, 255, 255)
RGB fill = new RGB(0, 0, 0)
bool fillOutside = true
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Euclidean color filtering.
The filter filters pixels, which color is inside/outside of RGB sphere with specified center and radius - it keeps pixels with colors inside/outside of the specified sphere and fills the rest with specified color.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
EuclideanColorFiltering filter = new EuclideanColorFiltering();
// set center colol and radius
filter.CenterColor = new RGB(215, 30, 30);
filter.Radius = 100;
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
ColorFiltering
Constructor & Destructor Documentation
EuclideanColorFiltering() [1/2]
AForge.Imaging.Filters.EuclideanColorFiltering.EuclideanColorFiltering () inline
Initializes a new instance of the EuclideanColorFiltering class.
References AForge.Imaging.Filters.EuclideanColorFiltering.formatTranslations.
EuclideanColorFiltering() [2/2]
AForge.Imaging.Filters.EuclideanColorFiltering.EuclideanColorFiltering (RGB center, short radius) inline
Initializes a new instance of the EuclideanColorFiltering class.
Parameters
center RGB sphere's center.
radius RGB sphere's radius.
References AForge.Imaging.Filters.EuclideanColorFiltering.center, and AForge.Imaging.Filters.EuclideanColorFiltering.radius.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.EuclideanColorFiltering.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.Filters.EuclideanColorFiltering.center, AForge.Imaging.Filters.EuclideanColorFiltering.fill, AForge.Imaging.Filters.EuclideanColorFiltering.fillOutside, AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.EuclideanColorFiltering.radius, AForge.Imaging.RGB.Red, and AForge.Imaging.UnmanagedImage.Stride.
Member Data Documentation
radius
short AForge.Imaging.Filters.EuclideanColorFiltering.radius = 100 private
Referenced by AForge.Imaging.Filters.EuclideanColorFiltering.EuclideanColorFiltering(), and AForge.Imaging.Filters.EuclideanColorFiltering.ProcessFilter().
center
RGB AForge.Imaging.Filters.EuclideanColorFiltering.center = new RGB(255, 255, 255) private
Referenced by AForge.Imaging.Filters.EuclideanColorFiltering.EuclideanColorFiltering(), and AForge.Imaging.Filters.EuclideanColorFiltering.ProcessFilter().
fill
RGB AForge.Imaging.Filters.EuclideanColorFiltering.fill = new RGB(0, 0, 0) private
Referenced by AForge.Imaging.Filters.EuclideanColorFiltering.ProcessFilter().
fillOutside
bool AForge.Imaging.Filters.EuclideanColorFiltering.fillOutside = true private
Referenced by AForge.Imaging.Filters.EuclideanColorFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.EuclideanColorFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.EuclideanColorFiltering.EuclideanColorFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.EuclideanColorFiltering.FormatTranslations get
Format translations dictionary.
Radius
short AForge.Imaging.Filters.EuclideanColorFiltering.Radius get set
RGB sphere's radius, [0, 450].
Default value is 100.
CenterColor
RGB AForge.Imaging.Filters.EuclideanColorFiltering.CenterColor get set
RGB sphere's center.
Default value is (255, 255, 255) - white color.
FillColor
RGB AForge.Imaging.Filters.EuclideanColorFiltering.FillColor get set
Fill color used to fill filtered pixels.
FillOutside
bool AForge.Imaging.Filters.EuclideanColorFiltering.FillOutside get set
Determines, if pixels should be filled inside or outside specified RGB sphere.
Default value is set to true, which means the filter removes colors outside of the specified range.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/EuclideanColorFiltering.cs