Doc: IGLib EXTENDED: NUnit.TestData.AssertFailFixture.AssertFailFixture Class Reference
NUnit.TestData.AssertFailFixture.AssertFailFixture Class Reference
Public Member Functions
void CallAssertFail ()
void CallAssertFailWithMessage ()
void CallAssertFailWithMessageAndArgs ()
Member Function Documentation
CallAssertFail()
void NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFail () inline
References NUnit.Framework.Assert.Fail().
CallAssertFailWithMessage()
void NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFailWithMessage () inline
References NUnit.Framework.Assert.Fail().
CallAssertFailWithMessageAndArgs()
void NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFailWithMessageAndArgs () inline
References NUnit.Framework.Assert.Fail().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/AssertFailFixture.cs