Doc: IGLib EXTENDED: CShell.Framework.Menus.StandardMenuItem Class Reference
CShell.Framework.Menus.StandardMenuItem Class Reference
Public Member Functions
StandardMenuItem (string text)
StandardMenuItem (string text, Func< bool > canExecute)
StandardMenuItem WithGlobalShortcut (ModifierKeys modifier, Key key)
StandardMenuItem WithIcon ()
StandardMenuItem WithIcon (string path)
StandardMenuItem WithIcon (Assembly source, string path)
StandardMenuItem WithActivator (IActivate activator)
StandardMenuItem WithActivator (IActivate activator, bool inverse)
Public Member Functions inherited from CShell.Framework.Menus.MenuItemBase
void Add (params MenuItemBase[] menuItems)
IEnumerator< MenuItemBase > GetEnumerator ()
Properties
string Text [get, set]
Image Icon [get, private set]
Uri IconSource [get, private set]
string ActionText [get]
bool CanExecute [get]
override string? Name [get]
string? InputGestureText [get]
Properties inherited from CShell.Framework.Menus.MenuItemBase
static MenuItemBase Separator [get]
IObservableCollection< MenuItemBase > Children [get, private set]
virtual string Name [get]
Private Attributes
Func< bool > _canExecute = () => true
KeyGesture _keyGesture
string _text
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Menus.MenuItemBase
MenuItemBase ()
Constructor & Destructor Documentation
StandardMenuItem() [1/2]
CShell.Framework.Menus.StandardMenuItem.StandardMenuItem (string text) inline
References CShell.Framework.Menus.StandardMenuItem.Text.
StandardMenuItem() [2/2]
CShell.Framework.Menus.StandardMenuItem.StandardMenuItem (string text, Func< bool > canExecute) inline
References CShell.Framework.Menus.StandardMenuItem._canExecute.
Member Function Documentation
WithGlobalShortcut()
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithGlobalShortcut (ModifierKeys modifier, Key key) inline
References CShell.Framework.Menus.StandardMenuItem._keyGesture.
WithIcon() [1/3]
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithIcon () inline
References CShell.Framework.Menus.StandardMenuItem.Name.
Referenced by CShell.Framework.Menus.StandardMenuItem.WithIcon().
WithIcon() [2/3]
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithIcon (string path) inline
References CShell.Framework.Menus.StandardMenuItem.WithIcon().
WithIcon() [3/3]
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithIcon (Assembly source, string path) inline
References CShell.Framework.Services.IResourceManager.GetBitmap(), CShell.Framework.Menus.StandardMenuItem.Icon, and CShell.Framework.Menus.StandardMenuItem.IconSource.
WithActivator() [1/2]
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithActivator (IActivate activator) inline
WithActivator() [2/2]
StandardMenuItem CShell.Framework.Menus.StandardMenuItem.WithActivator (IActivate activator, bool inverse) inline
References CShell.Framework.Menus.StandardMenuItem._canExecute, and CShell.Framework.Menus.StandardMenuItem.CanExecute.
Member Data Documentation
_canExecute
Func<bool> CShell.Framework.Menus.StandardMenuItem._canExecute = () => true private
Referenced by CShell.Framework.Menus.StandardMenuItem.StandardMenuItem(), and CShell.Framework.Menus.StandardMenuItem.WithActivator().
_keyGesture
KeyGesture CShell.Framework.Menus.StandardMenuItem._keyGesture private
Referenced by CShell.Framework.Menus.StandardMenuItem.WithGlobalShortcut().
_text
string CShell.Framework.Menus.StandardMenuItem._text private
Property Documentation
Text
string CShell.Framework.Menus.StandardMenuItem.Text get set
Referenced by CShell.Framework.Menus.StandardMenuItem.StandardMenuItem().
Icon
Image CShell.Framework.Menus.StandardMenuItem.Icon get private set
Referenced by CShell.Framework.Menus.StandardMenuItem.WithIcon().
IconSource
Uri CShell.Framework.Menus.StandardMenuItem.IconSource get private set
Referenced by CShell.Framework.Menus.StandardMenuItem.WithIcon().
ActionText
string CShell.Framework.Menus.StandardMenuItem.ActionText get
CanExecute
bool CShell.Framework.Menus.StandardMenuItem.CanExecute get
Referenced by CShell.Framework.Menus.StandardMenuItem.WithActivator().
Name
override string? CShell.Framework.Menus.StandardMenuItem.Name get
Referenced by CShell.Framework.Menus.StandardMenuItem.WithIcon().
InputGestureText
string? CShell.Framework.Menus.StandardMenuItem.InputGestureText get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Menus/StandardMenuItem.cs