Doc: IGLib EXTENDED: NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests Class Reference
NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests Class Reference
Public Member Functions
void SucceedsWhenKeyIsPresent ()
void FailsWhenKeyIsMissing ()
void FailsWhenNotUsedAgainstADictionary ()
void WorksWithNonGenericDictionary ()
void IgnoreCaseIsHonored ()
void UsingIsHonored ()
Member Function Documentation
SucceedsWhenKeyIsPresent()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.SucceedsWhenKeyIsPresent () inline
References NUnit.Framework.Assert.That().
FailsWhenKeyIsMissing()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenKeyIsMissing () inline
References NUnit.Framework.Throws.Exception, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.ConstraintExpression.TypeOf().
FailsWhenNotUsedAgainstADictionary()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary () inline
References NUnit.Framework.Throws.ArgumentException, NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.Constraint.With.
WorksWithNonGenericDictionary()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.WorksWithNonGenericDictionary () inline
References NUnit.Framework.Assert.That().
IgnoreCaseIsHonored()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.IgnoreCaseIsHonored () inline
References NUnit.Framework.Assert.That().
UsingIsHonored()
void NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.UsingIsHonored () inline
References NUnit.Framework.Internal.StringUtil.Compare(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/DictionaryContainsKeyConstraintTests.cs