Doc: IGLib EXTENDED: NUnit.Engine.Internal.Tests.SettingsGroupTests Class Reference
NUnit.Engine.Internal.Tests.SettingsGroupTests Class Reference
Public Member Functions
void BeforeEachTest ()
void WhenSettingIsNotInitialized_NullIsReturned ()
void WhenSettingIsInitialized_ValueIsReturned (string name, object expected)
void WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected ()
void WhenSettingIsNotInitialized_DefaultValueIsReturned ()
void WhenSettingIsNotValid_DefaultSettingIsReturned ()
Private Types
enum PriorityValue { PriorityValue.A, PriorityValue.B, PriorityValue.C }
Private Attributes
SettingsGroup settings
Member Enumeration Documentation
PriorityValue
enum NUnit.Engine.Internal.Tests.SettingsGroupTests.PriorityValue strong private
Enumerator
A
B
C
Member Function Documentation
BeforeEachTest()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.BeforeEachTest () inline
References NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
WhenSettingIsNotInitialized_NullIsReturned()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_NullIsReturned () inline
References NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Framework.Assert.IsNull(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
WhenSettingIsInitialized_ValueIsReturned()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsInitialized_ValueIsReturned (string name, object expected) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Framework.Assert.IsInstanceOf(), NUnit.Engine.Internal.SettingsGroup.SaveSetting(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Framework.Assert.IsNull(), NUnit.Engine.Internal.SettingsGroup.RemoveSetting(), NUnit.Engine.Internal.SettingsGroup.SaveSetting(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
WhenSettingIsNotInitialized_DefaultValueIsReturned()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_DefaultValueIsReturned () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Internal.SettingsGroup.GetSetting(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
WhenSettingIsNotValid_DefaultSettingIsReturned()
void NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotValid_DefaultSettingIsReturned () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Engine.Internal.SettingsGroup.SaveSetting(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.settings.
Member Data Documentation
settings
SettingsGroup NUnit.Engine.Internal.Tests.SettingsGroupTests.settings private
Referenced by NUnit.Engine.Internal.Tests.SettingsGroupTests.BeforeEachTest(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsInitialized_ValueIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_DefaultValueIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_NullIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotValid_DefaultSettingIsReturned(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Internal/SettingsGroupTests.cs