Doc: IGLib EXTENDED: Test.IntervalTest Class Reference
Test.IntervalTest Class Reference
This is a test class for IntervalTest and is intended to contain all IntervalTest Unit Tests /summary>
Public Member Functions
void IntervalZeroWidth ()
void IntervalWidth ()
void IntervalEndpoints ()
void ToTest ()
void IntervalMidpoint ()
void FromTest ()
A test for From /summary>
void IntervalOpenContains ()
void IntervalFromMidpointAndWidth ()
void IntervalFromEndpoints ()
void IntervalClosedContains ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Private Attributes
TestContext testContextInstance
double a = -3.1
double b = -2.0
double c = 2.7
double d = 5.1
Detailed Description
This is a test class for IntervalTest and is intended to contain all IntervalTest Unit Tests /summary>
Member Function Documentation
IntervalZeroWidth()
void Test.IntervalTest.IntervalZeroWidth () inline
References Test.IntervalTest.a, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Interval.Midpoint, Meta.Numerics.Interval.RightEndpoint, and Meta.Numerics.Interval.Width.
IntervalWidth()
void Test.IntervalTest.IntervalWidth () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.Width.
IntervalEndpoints()
void Test.IntervalTest.IntervalEndpoints () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.LeftEndpoint, and Meta.Numerics.Interval.RightEndpoint.
ToTest()
void Test.IntervalTest.ToTest () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.RightEndpoint.
IntervalMidpoint()
void Test.IntervalTest.IntervalMidpoint () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.Midpoint.
FromTest()
void Test.IntervalTest.FromTest () inline
A test for From /summary>
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.LeftEndpoint.
IntervalOpenContains()
void Test.IntervalTest.IntervalOpenContains () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Test.IntervalTest.c, Test.IntervalTest.d, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.OpenContains().
IntervalFromMidpointAndWidth()
void Test.IntervalTest.IntervalFromMidpointAndWidth () inline
References Meta.Numerics.Interval.FromMidpointAndWidth(), Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Interval.Midpoint, Meta.Numerics.Interval.RightEndpoint, and Meta.Numerics.Interval.Width.
IntervalFromEndpoints()
void Test.IntervalTest.IntervalFromEndpoints () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.GetHashCode(), Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Interval.RightEndpoint, and Meta.Numerics.Interval.Width.
IntervalClosedContains()
void Test.IntervalTest.IntervalClosedContains () inline
References Test.IntervalTest.a, Test.IntervalTest.b, Test.IntervalTest.c, Meta.Numerics.Interval.ClosedContains(), Test.IntervalTest.d, and Meta.Numerics.Interval.FromEndpoints().
Member Data Documentation
testContextInstance
TestContext Test.IntervalTest.testContextInstance private
a
double Test.IntervalTest.a = -3.1 private
Referenced by Test.IntervalTest.FromTest(), Test.IntervalTest.IntervalClosedContains(), Test.IntervalTest.IntervalEndpoints(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalMidpoint(), Test.IntervalTest.IntervalOpenContains(), Test.IntervalTest.IntervalWidth(), Test.IntervalTest.IntervalZeroWidth(), and Test.IntervalTest.ToTest().
b
double Test.IntervalTest.b = -2.0 private
Referenced by Test.IntervalTest.FromTest(), Test.IntervalTest.IntervalClosedContains(), Test.IntervalTest.IntervalEndpoints(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalMidpoint(), Test.IntervalTest.IntervalOpenContains(), Test.IntervalTest.IntervalWidth(), and Test.IntervalTest.ToTest().
c
double Test.IntervalTest.c = 2.7 private
Referenced by Test.IntervalTest.IntervalClosedContains(), and Test.IntervalTest.IntervalOpenContains().
d
double Test.IntervalTest.d = 5.1 private
Referenced by Test.IntervalTest.IntervalClosedContains(), and Test.IntervalTest.IntervalOpenContains().
Property Documentation
TestContext
TestContext Test.IntervalTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/IntervalTest.cs