Doc: IGLib EXTENDED: NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests Class Reference
NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests Class Reference
Public Member Functions
void InitializeValidator ()
void TestSchemaValidatorInvariantCulture ()
void TestSchemaValidatorUnitedStatesCulture ()
void TestSchemaValidatorFrenchCulture ()
Public Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
void InitializeTestEngineResult ()
Private Member Functions
void runSchemaValidatorTest ()
Private Attributes
SchemaValidator validator
Static Private Attributes
static readonly string schemaFile = "NUnit2TestResult.xsd"
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
string GetLocalPath (string fileName)
Static Protected Attributes inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
const string AssemblyName = "mock-nunit-assembly.exe"
Properties inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
TestEngineResult EngineResult [get, private set]
string AssemblyPath [get, private set]
Member Function Documentation
InitializeValidator()
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.InitializeValidator () inline
References NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.GetLocalPath(), and NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.schemaFile.
TestSchemaValidatorInvariantCulture()
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorInvariantCulture () inline
References NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
TestSchemaValidatorUnitedStatesCulture()
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorUnitedStatesCulture () inline
References NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
TestSchemaValidatorFrenchCulture()
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorFrenchCulture () inline
References NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
runSchemaValidatorTest()
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest () inline private
References NUnit.Engine.ServiceContext.Add(), NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.EngineResult, NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Errors, NUnit.Framework.Assert.Fail(), NUnit.Engine.Services.ResultService.GetResultWriter(), NUnit.Framework.Assert.NotNull(), NUnit.Engine.ServiceContext.ServiceManager, NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Validate(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.validator, and NUnit.Engine.TestEngineResult.Xml.
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorFrenchCulture(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorInvariantCulture(), and NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.TestSchemaValidatorUnitedStatesCulture().
Member Data Documentation
validator
SchemaValidator NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.validator private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
schemaFile
readonly string NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.schemaFile = "NUnit2TestResult.xsd" static private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.InitializeValidator().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultWriters/NUnit2XmlValidationTests.cs