Doc: IGLib EXTENDED: NUnit.Engine.Extensibility.IResultWriter Interface Reference
NUnit.Engine.Extensibility.IResultWriter Interface Reference
Common interface for objects that process and write out test results
Public Member Functions
void CheckWritability (string outputPath)
Checks if the output path is writable. If the output is not writable, this method should throw an exception.
void WriteResultFile (XmlNode resultNode, string outputPath)
Writes result to the specified output path.
void WriteResultFile (XmlNode resultNode, TextWriter writer)
Writes result to a TextWriter.
Detailed Description
Common interface for objects that process and write out test results
Member Function Documentation
CheckWritability()
void NUnit.Engine.Extensibility.IResultWriter.CheckWritability (string outputPath)
Checks if the output path is writable. If the output is not writable, this method should throw an exception.
Parameters
outputPath
Implemented in NUnit.Engine.Services.XmlTransformResultWriter, NUnit.Engine.Addins.NUnit2XmlResultWriter, NUnit.Engine.Services.NUnit3XmlResultWriter, and NUnit.Engine.Services.TestCaseResultWriter.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RunTests().
WriteResultFile() [1/2]
void NUnit.Engine.Extensibility.IResultWriter.WriteResultFile (XmlNode resultNode, string outputPath)
Writes result to the specified output path.
Parameters
resultNode XmlNode for the result
outputPath Path to which it should be written
Implemented in NUnit.Engine.Services.NUnit3XmlResultWriter, NUnit.Engine.Services.TestCaseResultWriter, NUnit.Engine.Services.XmlTransformResultWriter, and NUnit.Engine.Addins.NUnit2XmlResultWriter.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
WriteResultFile() [2/2]
void NUnit.Engine.Extensibility.IResultWriter.WriteResultFile (XmlNode resultNode, TextWriter writer)
Writes result to a TextWriter.
Parameters
resultNode XmlNode for the result
writer TextWriter to which it should be written
Implemented in NUnit.Engine.Services.NUnit3XmlResultWriter, NUnit.Engine.Services.TestCaseResultWriter, NUnit.Engine.Services.XmlTransformResultWriter, and NUnit.Engine.Addins.NUnit2XmlResultWriter.
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/Extensibility/IResultWriter.cs