Doc: IGLib EXTENDED: CShell.Sinks.Plotting Class Reference
CShell.Sinks.Plotting Class Reference
Extension methods to help with plotting and access the plotting sinks.
Static Public Member Functions
static IPlotSink GetPlotSink (string sinkName)
Gets a plot sink. If the plot exists or can be created the plot is opened.
static IPlotSink GetPlotSink (string sinkName, bool suppressOpen)
Gets a plot sink.
static void Plot (this Series series, string sinkName=null)
Plots the specified series.
static void Plot (this Chart chart, string sinkName=null)
Plots the specified chart.
static void Plot (this IEnumerable ys, string seriesName=null, string chartType="Line", string sinkName=null)
Plots the specified Y values.
static void Plot (this IEnumerable ys, IEnumerable xs, string seriesName=null, string chartType="Line", string sinkName=null)
Plots the specified Y values at the corresponding X points.
static void PlotFunction (this Func< double, double > f, string seriesName=null, string chartType="Line", double from=-3.0, double to=3.0, int points=100, string sinkName=null)
Plots a function that produces Y values.
static void PlotHistogram (this IEnumerable ys, string seriesName=null, string histogramName=null, string sinkName=null)
Plots the Y values as a histogram.
Properties
static string[] PlotChartTypes [get]
Gets the available plot chart types.
Detailed Description
Extension methods to help with plotting and access the plotting sinks.
Member Function Documentation
GetPlotSink() [1/2]
static IPlotSink CShell.Sinks.Plotting.GetPlotSink (string sinkName) inline static
Gets a plot sink. If the plot exists or can be created the plot is opened.
Parameters
sinkName Name of the sink.
Referenced by CShell.Sinks.Plotting.Plot(), CShell.Sinks.Plotting.PlotFunction(), and CShell.Sinks.Plotting.PlotHistogram().
GetPlotSink() [2/2]
static IPlotSink CShell.Sinks.Plotting.GetPlotSink (string sinkName, bool suppressOpen) inline static
Gets a plot sink.
Parameters
sinkName Name of the sink.
suppressOpen If set to true the plot is not opened.
References CShell.Shell.GetSink(), and CShell.Constants.SinkPlot.
Plot() [1/4]
static void CShell.Sinks.Plotting.Plot (this Series series, string sinkName = null) inline static
Plots the specified series.
Parameters
series The series.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
Plot() [2/4]
static void CShell.Sinks.Plotting.Plot (this Chart chart, string sinkName = null) inline static
Plots the specified chart.
Parameters
chart The chart.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
Plot() [3/4]
static void CShell.Sinks.Plotting.Plot (this IEnumerable ys, string seriesName = null, string chartType = "Line", string sinkName = null) inline static
Plots the specified Y values.
Parameters
ys The Y values.
seriesName Name of the series.
chartType The chart type to be used for the points, see the PlotChartTypes property for all available types.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
Plot() [4/4]
static void CShell.Sinks.Plotting.Plot (this IEnumerable ys, IEnumerable xs, string seriesName = null, string chartType = "Line", string sinkName = null) inline static
Plots the specified Y values at the corresponding X points.
Parameters
ys The Y values.
xs The X values.
seriesName Name of the series.
chartType The chart type to be used for the points, see the PlotChartTypes property for all available types.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
PlotFunction()
static void CShell.Sinks.Plotting.PlotFunction (this Func< double, double > f, string seriesName = null, string chartType = "Line", double from = -3.0, double to = 3.0, int points = 100, string sinkName = null) inline static
Plots a function that produces Y values.
Parameters
f The function to plot.
seriesName Name of the resulting series.
chartType The chart type to be used for the points, see the PlotChartTypes property for all available types.
from At what X value to start the plot.
to At what X value to end the plot.
points How many points to plot between start and end.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
PlotHistogram()
static void CShell.Sinks.Plotting.PlotHistogram (this IEnumerable ys, string seriesName = null, string histogramName = null, string sinkName = null) inline static
Plots the Y values as a histogram.
Parameters
ys The Y values to plot.
seriesName Name of the series.
histogramName Name of the resulting histogram.
sinkName Name of the sink.
References CShell.Sinks.Plotting.GetPlotSink().
Property Documentation
PlotChartTypes
string [] CShell.Sinks.Plotting.PlotChartTypes static get
Gets the available plot chart types.
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Sinks/Plotting.cs