Doc: IGLib EXTENDED: NeuronDotNet.Core.Backpropagation.BackpropagationConnector Class Reference
NeuronDotNet.Core.Backpropagation.BackpropagationConnector Class Reference
A Backpropagation Connector is an IConnector which consists of a collection of backpropagation synapses connecting two activation layers.
Public Member Functions
BackpropagationConnector (ActivationLayer sourceLayer, ActivationLayer targetLayer)
Creates a new complete backpropagation connector between given layers.
BackpropagationConnector (ActivationLayer sourceLayer, ActivationLayer targetLayer, ConnectionMode connectionMode)
Creates a new Backpropagation connector between the given layers using the specified connection mode.
BackpropagationConnector (SerializationInfo info, StreamingContext context)
Deserialization Constructor
override void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the connector
override void Initialize ()
Initializes all synapses in the connector and makes them ready to undergo training freshly. (Adjusts the weights of synapses using the initializer)
Public Member Functions inherited from NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >
void Jitter (double jitterNoiseLimit)
Adds small random noise to weights of synapses so that the network deviates from its local optimum position (a local equilibrium state where further learning is of no use)
IEnumerable< TSynapse > GetSourceSynapses (INeuron neuron)
Gets a enumerator to a collection of source synapses of the neuron which belong to this connector
IEnumerable< TSynapse > GetTargetSynapses (INeuron neuron)
Gets a enumerator to a collection of target synapses of the neuron which belong to this connector
Properties
double Momentum [get, set]
Gets or sets the momentum (the tendency of synapses to retain their previous deltas)
Properties inherited from NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >
TSourceLayer SourceLayer [get]
Gets the source layer
ILayer IConnector. SourceLayer [get]
TTargetLayer TargetLayer [get]
Gets the target layer
ILayer IConnector. TargetLayer [get]
int SynapseCount [get]
Gets the number of synapses in the connector.
IEnumerable< TSynapse > Synapses [get]
Exposes an enumerator to iterate over all synapses in the connector.
IEnumerable< ISynapse > IConnector. Synapses [get]
ConnectionMode ConnectionMode [get]
Gets the connection mode
IInitializer Initializer [get, set]
Gets or sets the Initializer used to initialize the connector
Private Member Functions
void ConstructSynapses ()
Private helper to construct synapses between layers
Additional Inherited Members
Protected Member Functions inherited from NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >
Connector (TSourceLayer sourceLayer, TTargetLayer targetLayer, ConnectionMode connectionMode)
Creates a new connector between given layers using the connection mode specified.
Connector (SerializationInfo info, StreamingContext context)
Deserialization constructor
Protected Attributes inherited from NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >
readonly TSourceLayer sourceLayer
The source layer. It is initialized in constructor and is never changed later. It is never null.
readonly TTargetLayer targetLayer
The target layer. It is initialized in constructor and is never changed later. It is never null.
readonly TSynapse[] synapses
Array of synapses in the connector. It is never null.
readonly ConnectionMode connectionMode
The mode of connection (One-one or Complete). It is initialized in the constructor and is immutable.
IInitializer initializer
Initializer used to initialize the connector
Detailed Description
A Backpropagation Connector is an IConnector which consists of a collection of backpropagation synapses connecting two activation layers.
Constructor & Destructor Documentation
BackpropagationConnector() [1/3]
NeuronDotNet.Core.Backpropagation.BackpropagationConnector.BackpropagationConnector (ActivationLayer sourceLayer, ActivationLayer targetLayer) inline
Creates a new complete backpropagation connector between given layers.
Parameters
sourceLayer The source layer
targetLayer The target layer
Exceptions
ArgumentNullException If sourceLayer or targetLayer is null
References NeuronDotNet.Core.Complete.
BackpropagationConnector() [2/3]
NeuronDotNet.Core.Backpropagation.BackpropagationConnector.BackpropagationConnector (ActivationLayer sourceLayer, ActivationLayer targetLayer, ConnectionMode connectionMode) inline
Creates a new Backpropagation connector between the given layers using the specified connection mode.
Parameters
sourceLayer The source layer
targetLayer The target layer
connectionMode Connection mode to use
Exceptions
ArgumentNullException If sourceLayer or targetLayer is null
References NeuronDotNet.Core.Backpropagation.BackpropagationConnector.ConstructSynapses().
BackpropagationConnector() [3/3]
NeuronDotNet.Core.Backpropagation.BackpropagationConnector.BackpropagationConnector (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Backpropagation.BackpropagationConnector.ConstructSynapses(), and NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.synapses.
Member Function Documentation
GetObjectData()
override void NeuronDotNet.Core.Backpropagation.BackpropagationConnector.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Populates the serialization info with the data needed to serialize the connector
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
Reimplemented from NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.
References NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.synapses.
Initialize()
override void NeuronDotNet.Core.Backpropagation.BackpropagationConnector.Initialize () inline virtual
Initializes all synapses in the connector and makes them ready to undergo training freshly. (Adjusts the weights of synapses using the initializer)
Implements NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.
References NeuronDotNet.Core.IInitializer.Initialize(), and NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.initializer.
ConstructSynapses()
void NeuronDotNet.Core.Backpropagation.BackpropagationConnector.ConstructSynapses () inline private
Private helper to construct synapses between layers
References NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.connectionMode, NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.sourceLayer, NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.synapses, and NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.targetLayer.
Referenced by NeuronDotNet.Core.Backpropagation.BackpropagationConnector.BackpropagationConnector().
Property Documentation
Momentum
double NeuronDotNet.Core.Backpropagation.BackpropagationConnector.Momentum get set
Gets or sets the momentum (the tendency of synapses to retain their previous deltas)
The tendency of synapses to retain their previous weight change.
Referenced by IG.Neural.NeuralApproximatorNeuron.CreateNetwork().
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Backpropagation/BackpropagationConnector.cs