Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARTG Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARTG Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARTG (DLAMCH dlamch)
DLARTG ()
void Run (double F, double G, ref double CS, ref double SN, ref double R)
Private Attributes
DLAMCH _dlamch
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARTG generate a plane rotation so that
[ CS SN ] . [ F ] = [ R ] where CS**2 + SN**2 = 1. [ -SN CS ] [ G ] [ 0 ]
This is a slower, more accurate version of the BLAS1 routine DROTG, with the following other differences: F and G are unchanged on return. If G=0, then CS=1 and SN=0. If F=0 and (G .ne. 0), then CS=0 and SN=1 without doing any floating point operations (saves work in DBDSQR when there are zeros on the diagonal).
If F exceeds G in magnitude, CS will be positive.
/summary>
Constructor & Destructor Documentation
DLARTG() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARTG.DLARTG (DLAMCH dlamch) inline
DLARTG() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARTG.DLARTG () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run (double F, double G, ref double CS, ref double SN, ref double R) inline
Purpose
DLARTG generate a plane rotation so that
[ CS SN ] . [ F ] = [ R ] where CS**2 + SN**2 = 1. [ -SN CS ] [ G ] [ 0 ]
This is a slower, more accurate version of the BLAS1 routine DROTG, with the following other differences: F and G are unchanged on return. If G=0, then CS=1 and SN=0. If F=0 and (G .ne. 0), then CS=0 and SN=1 without doing any floating point operations (saves work in DBDSQR when there are zeros on the diagonal).
If F exceeds G in magnitude, CS will be positive.
/summary>
Parameters
F (input) DOUBLE PRECISION The first component of vector to be rotated. /param>
Parameters
G (input) DOUBLE PRECISION The second component of vector to be rotated. /param>
Parameters
CS (output) DOUBLE PRECISION The cosine of the rotation. /param>
Parameters
SN (output) DOUBLE PRECISION The sine of the rotation. /param>
Parameters
R (output) DOUBLE PRECISION The nonzero component of the rotated vector. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARTG.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLARTG.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAGS2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLARTG._dlamch private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARTG.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARTG.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLARTG.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlartg.cs