Doc: IGLib EXTENDED: Test.VectorTest Class Reference
Test.VectorTest Class Reference
Public Member Functions
void ColumnVectorCopy ()
void RowVectorCopy ()
void ColumnVectorArithmetic ()
void RowVectorArithmetic ()
void MixedVectorArithmetic ()
void VectorNorm ()
void VectorAsCollection ()
void ExtendedVectorNorm ()
Private Attributes
RowVector R = new RowVector(new double[] { 1, 1 })
ColumnVector C = new ColumnVector(new double[] { 1, -1, 1 })
RectangularMatrix M = new RectangularMatrix(new double[,] { { 1, 2, 3 }, { 4, 5, 6 } })
Member Function Documentation
ColumnVectorCopy()
void Test.VectorTest.ColumnVectorCopy () inline
References Meta.Numerics.Matrices.ColumnVector.Copy().
RowVectorCopy()
void Test.VectorTest.RowVectorCopy () inline
References Meta.Numerics.Matrices.RowVector.Copy().
ColumnVectorArithmetic()
void Test.VectorTest.ColumnVectorArithmetic () inline
References Test.VectorTest.C, Meta.Numerics.Matrices.VectorBase.Dimension, and Meta.Numerics.Matrices.ColumnVector.Transpose().
RowVectorArithmetic()
void Test.VectorTest.RowVectorArithmetic () inline
References Meta.Numerics.Matrices.VectorBase.Dimension, Test.VectorTest.M, Test.VectorTest.R, and Meta.Numerics.Matrices.RowVector.Transpose().
MixedVectorArithmetic()
void Test.VectorTest.MixedVectorArithmetic () inline
References Test.VectorTest.C, Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Meta.Numerics.Matrices.VectorBase.Dimension, Test.VectorTest.R, and Meta.Numerics.Matrices.RectangularMatrix.RowCount.
VectorNorm()
void Test.VectorTest.VectorNorm () inline
References Test.VectorTest.C, Meta.Numerics.Matrices.VectorBase.Norm(), and Test.VectorTest.R.
VectorAsCollection()
void Test.VectorTest.VectorAsCollection () inline
References Meta.Numerics.Matrices.VectorBase.Dimension.
ExtendedVectorNorm()
void Test.VectorTest.ExtendedVectorNorm () inline
References Meta.Numerics.Matrices.VectorBase.Norm().
Member Data Documentation
R
RowVector Test.VectorTest.R = new RowVector(new double[] { 1, 1 }) private
Referenced by Test.VectorTest.MixedVectorArithmetic(), Test.VectorTest.RowVectorArithmetic(), and Test.VectorTest.VectorNorm().
C
ColumnVector Test.VectorTest.C = new ColumnVector(new double[] { 1, -1, 1 }) private
Referenced by Test.VectorTest.ColumnVectorArithmetic(), Test.VectorTest.MixedVectorArithmetic(), and Test.VectorTest.VectorNorm().
M
RectangularMatrix Test.VectorTest.M = new RectangularMatrix(new double[,] { { 1, 2, 3 }, { 4, 5, 6 } }) private
Referenced by Test.VectorTest.RowVectorArithmetic().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/VectorTest.cs