Doc: IGLib EXTENDED: alglib.testbdssunit Class Reference
alglib.testbdssunit Class Reference
Static Public Member Functions
static bool testbdss (bool silent)
static bool testbdss (bool silent)
static bool _pexec_testbdss (bool silent)
Static Private Member Functions
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void unset1di (ref int[] a)
static void testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors)
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void unset1di (ref int[] a)
static void testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors)
Member Function Documentation
testbdss() [1/2]
static bool alglib.testbdssunit.testbdss (bool silent) inline static
References alglib.bdss.dsoptimalsplit2(), alglib.bdss.dsoptimalsplit2fast(), alglib.bdss.dsoptimalsplitk(), alglib.bdss.dssplitk(), alglib.bdss.dstie(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.tsort.tagsort(), alglib.tsort.tagsortfastr(), and alglib.testbdssunit.unset1di().
Referenced by alglib.testbdssunit._pexec_testbdss(), and _Test.Main().
unset2d() [1/2]
static void alglib.testbdssunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
unset1d() [1/2]
static void alglib.testbdssunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
unset1di() [1/2]
static void alglib.testbdssunit.unset1di (ref int[] a) inline static private
References alglib.math.randominteger().
Referenced by alglib.testbdssunit.testbdss().
testsortresults() [1/2]
static void alglib.testbdssunit.testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors) inline static private
testbdss() [2/2]
static bool alglib.testbdssunit.testbdss (bool silent) inline static
References alglib.bdss.dsoptimalsplit2(), alglib.bdss.dsoptimalsplit2fast(), alglib.bdss.dsoptimalsplitk(), alglib.bdss.dssplitk(), alglib.bdss.dstie(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.tsort.tagsort(), alglib.tsort.tagsortfastr(), and alglib.testbdssunit.unset1di().
_pexec_testbdss()
static bool alglib.testbdssunit._pexec_testbdss (bool silent) inline static
References alglib.testbdssunit.testbdss().
Referenced by _Test.Main().
unset2d() [2/2]
static void alglib.testbdssunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
unset1d() [2/2]
static void alglib.testbdssunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
unset1di() [2/2]
static void alglib.testbdssunit.unset1di (ref int[] a) inline static private
References alglib.math.randominteger().
testsortresults() [2/2]
static void alglib.testbdssunit.testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs