Doc: IGLib EXTENDED: IG.Forms.NeuralInputControl Class Reference
IG.Forms.NeuralInputControl Class Reference
Control for editing input parameter values.
Public Member Functions
NeuralInputControl ()
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _colNumValue = 2
Vector _values
Properties
InputOutputDataDefiniton NeuralDataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
int ColNumValue [get, protected set]
Number of DataGrid Column that contains the value.
int NumValues [get]
Current number of values, otained form the DataGridView.
IVector Values [get, protected set]
Vector of current values of input parameters as defined by the DadaGridView.
Private Member Functions
void NeuralInputControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _neuralDataDefinition
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.DataGridView dGridInputParam
System.Windows.Forms.Button btnResetDefault
System.Windows.Forms.Button btnResetCenter
System.Windows.Forms.ContextMenuStrip contextMenuControl
System.Windows.Forms.ToolStripMenuItem resetToDefaultToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem resetToCenterToolStripMenuItem
System.Windows.Forms.DataGridViewTextBoxColumn columnID
System.Windows.Forms.DataGridViewTextBoxColumn columnName
System.Windows.Forms.DataGridViewTextBoxColumn columnValue
Detailed Description
Control for editing input parameter values.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralInputControl()
IG.Forms.NeuralInputControl.NeuralInputControl () inline
References IG.Forms.NeuralInputControl.InitializeComponent().
Member Function Documentation
GetGridControl()
DataGridView IG.Forms.NeuralInputControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.NeuralInputControl.dGridInputParam.
InitializeCells()
void IG.Forms.NeuralInputControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Forms.NeuralInputControl.NeuralDataDefinition, and IG.Num.InputOutputElementDefinition.Title.
Referenced by IG.Forms.NeuralInputControl.ResetToCenter(), and IG.Forms.NeuralInputControl.ResetToDefault().
ClearCells()
void IG.Forms.NeuralInputControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputLength, and IG.Forms.NeuralInputControl.NeuralDataDefinition.
ClearDataGrid()
void IG.Forms.NeuralInputControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.NeuralInputControl.dGridInputParam.
ResetToDefault()
void IG.Forms.NeuralInputControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.NeuralInputControl.dGridInputParam, IG.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Forms.NeuralInputControl.NeuralDataDefinition.
Referenced by IG.Forms.NeuralInputControl.btnResetDefault_Click(), and IG.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click().
ResetToCenter()
void IG.Forms.NeuralInputControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.NeuralInputControl.dGridInputParam, IG.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Forms.NeuralInputControl.NeuralDataDefinition.
Referenced by IG.Forms.NeuralInputControl.btnResetCenter_Click(), and IG.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click().
SetValues()
void IG.Forms.NeuralInputControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Forms.NeuralInputControl.Values.
ShowContextMenuControl()
void IG.Forms.NeuralInputControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.NeuralInputControl.contextMenuControl.
Referenced by IG.Forms.NeuralInputControl.dGridInputParam_MouseClick(), and IG.Forms.NeuralInputControl.NeuralInputControl_MouseClick().
NeuralInputControl_MouseClick()
void IG.Forms.NeuralInputControl.NeuralInputControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.NeuralInputControl.ShowContextMenuControl().
dGridInputParam_MouseClick()
void IG.Forms.NeuralInputControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.NeuralInputControl.ShowContextMenuControl().
btnResetDefault_Click()
void IG.Forms.NeuralInputControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralInputControl.ResetToDefault().
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
btnResetCenter_Click()
void IG.Forms.NeuralInputControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralInputControl.ResetToCenter().
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
resetToDefaultToolStripMenuItem_Click()
void IG.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralInputControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click()
void IG.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralInputControl.ResetToCenter().
dGridInputParam_CellValueChanged()
void IG.Forms.NeuralInputControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.NeuralInputControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose()
override void IG.Forms.NeuralInputControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.NeuralInputControl.components.
InitializeComponent()
void IG.Forms.NeuralInputControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NeuralInputControl.btnResetCenter, IG.Forms.NeuralInputControl.btnResetCenter_Click(), IG.Forms.NeuralInputControl.btnResetDefault, IG.Forms.NeuralInputControl.btnResetDefault_Click(), IG.Forms.NeuralInputControl.columnID, IG.Forms.NeuralInputControl.columnName, IG.Forms.NeuralInputControl.columnValue, IG.Forms.NeuralInputControl.components, IG.Forms.NeuralInputControl.contextMenuControl, IG.Forms.NeuralInputControl.dGridInputParam, IG.Forms.NeuralInputControl.groupBox1, IG.Forms.NeuralInputControl.resetToCenterToolStripMenuItem, and IG.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem.
Referenced by IG.Forms.NeuralInputControl.NeuralInputControl().
Member Data Documentation
_neuralDataDefinition
InputOutputDataDefiniton IG.Forms.NeuralInputControl._neuralDataDefinition private
_colNumValue
int IG.Forms.NeuralInputControl._colNumValue = 2 protected
_values
Vector IG.Forms.NeuralInputControl._values protected
components
System.ComponentModel.IContainer IG.Forms.NeuralInputControl.components = null private
Required designer variable.
Referenced by IG.Forms.NeuralInputControl.Dispose(), and IG.Forms.NeuralInputControl.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox IG.Forms.NeuralInputControl.groupBox1 private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
dGridInputParam
System.Windows.Forms.DataGridView IG.Forms.NeuralInputControl.dGridInputParam private
Referenced by IG.Forms.NeuralInputControl.ClearCells(), IG.Forms.NeuralInputControl.ClearDataGrid(), IG.Forms.NeuralInputControl.GetGridControl(), IG.Forms.NeuralInputControl.InitializeCells(), IG.Forms.NeuralInputControl.InitializeComponent(), IG.Forms.NeuralInputControl.ResetToCenter(), and IG.Forms.NeuralInputControl.ResetToDefault().
btnResetDefault
System.Windows.Forms.Button IG.Forms.NeuralInputControl.btnResetDefault private
Referenced by IG.Forms.NeuralInputControl.dGridInputParam_CellValueChanged(), and IG.Forms.NeuralInputControl.InitializeComponent().
btnResetCenter
System.Windows.Forms.Button IG.Forms.NeuralInputControl.btnResetCenter private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
contextMenuControl
System.Windows.Forms.ContextMenuStrip IG.Forms.NeuralInputControl.contextMenuControl private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent(), and IG.Forms.NeuralInputControl.ShowContextMenuControl().
resetToDefaultToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
resetToCenterToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.NeuralInputControl.resetToCenterToolStripMenuItem private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
columnID
System.Windows.Forms.DataGridViewTextBoxColumn IG.Forms.NeuralInputControl.columnID private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
columnName
System.Windows.Forms.DataGridViewTextBoxColumn IG.Forms.NeuralInputControl.columnName private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
columnValue
System.Windows.Forms.DataGridViewTextBoxColumn IG.Forms.NeuralInputControl.columnValue private
Referenced by IG.Forms.NeuralInputControl.InitializeComponent().
Property Documentation
NeuralDataDefinition
InputOutputDataDefiniton IG.Forms.NeuralInputControl.NeuralDataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.NeuralInputControl.ClearCells(), IG.Forms.NeuralInputControl.InitializeCells(), IG.Forms.NeuralInputControl.ResetToCenter(), and IG.Forms.NeuralInputControl.ResetToDefault().
ColNumValue
int IG.Forms.NeuralInputControl.ColNumValue get protected set
Number of DataGrid Column that contains the value.
Referenced by IG.Forms.NeuralInputControl.ResetToCenter(), and IG.Forms.NeuralInputControl.ResetToDefault().
NumValues
int IG.Forms.NeuralInputControl.NumValues get
Current number of values, otained form the DataGridView.
Values
IVector IG.Forms.NeuralInputControl.Values get protected set
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Forms.NeuralInputControl.SetValues().
The documentation for this class was generated from the following files:
unittests/Guest_IGTestCopy/Copy_Forms/11/Numeric/FromNeural/Basic/ParametricInputControl.cs
unittests/Guest_IGTestCopy/Copy_Forms/11/Numeric/FromNeural/Basic/ParametricInputControl.Designer.cs