Doc: IGLib EXTENDED: NUnit.Framework.Assertions.LessFixture Class Reference
NUnit.Framework.Assertions.LessFixture Class Reference
Public Member Functions
void Less ()
void MixedTypes ()
void NotLessWhenEqual ()
void NotLess ()
void NotLessIComparable ()
void FailureMessage ()
Private Attributes
readonly int i1 = 5
readonly int i2 = 8
readonly uint u1 = 12345678
readonly uint u2 = 12345879
readonly long l1 = 12345678
readonly long l2 = 12345879
readonly ulong ul1 = 12345678
readonly ulong ul2 = 12345879
readonly float f1 = 3.543F
readonly float f2 = 8.543F
readonly decimal de1 = 53.4M
readonly decimal de2 = 83.4M
readonly double d1 = 4.85948654
readonly double d2 = 8.0
readonly System.Enum e1 = RunState.Explicit
readonly System.Enum e2 = RunState.Ignored
Member Function Documentation
Less()
void NUnit.Framework.Assertions.LessFixture.Less () inline
References NUnit.Framework.Assertions.LessFixture.d1, NUnit.Framework.Assertions.LessFixture.d2, NUnit.Framework.Assertions.LessFixture.de1, NUnit.Framework.Assertions.LessFixture.de2, NUnit.Framework.Assertions.LessFixture.f1, NUnit.Framework.Assertions.LessFixture.f2, NUnit.Framework.Assertions.LessFixture.i1, NUnit.Framework.Assertions.LessFixture.i2, NUnit.Framework.Assertions.LessFixture.l1, NUnit.Framework.Assertions.LessFixture.l2, NUnit.Framework.Assert.Less(), NUnit.Framework.Assertions.LessFixture.u1, NUnit.Framework.Assertions.LessFixture.u2, NUnit.Framework.Assertions.LessFixture.ul1, and NUnit.Framework.Assertions.LessFixture.ul2.
MixedTypes()
void NUnit.Framework.Assertions.LessFixture.MixedTypes () inline
References NUnit.Framework.Assert.Less().
NotLessWhenEqual()
void NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assertions.LessFixture.i1, NUnit.Framework.Assert.Less(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotLess()
void NUnit.Framework.Assertions.LessFixture.NotLess () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assertions.LessFixture.i1, NUnit.Framework.Assertions.LessFixture.i2, NUnit.Framework.Assert.Less(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotLessIComparable()
void NUnit.Framework.Assertions.LessFixture.NotLessIComparable () inline
References NUnit.Framework.Assertions.LessFixture.e1, NUnit.Framework.Assertions.LessFixture.e2, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.Less(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
FailureMessage()
void NUnit.Framework.Assertions.LessFixture.FailureMessage () inline
References NUnit.Framework.StringAssert.Contains(), NUnit.Framework.Assert.Less(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, and NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected.
Member Data Documentation
i1
readonly int NUnit.Framework.Assertions.LessFixture.i1 = 5 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less(), NUnit.Framework.Assertions.LessFixture.NotLess(), and NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual().
i2
readonly int NUnit.Framework.Assertions.LessFixture.i2 = 8 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less(), and NUnit.Framework.Assertions.LessFixture.NotLess().
u1
readonly uint NUnit.Framework.Assertions.LessFixture.u1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
u2
readonly uint NUnit.Framework.Assertions.LessFixture.u2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
l1
readonly long NUnit.Framework.Assertions.LessFixture.l1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
l2
readonly long NUnit.Framework.Assertions.LessFixture.l2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
ul1
readonly ulong NUnit.Framework.Assertions.LessFixture.ul1 = 12345678 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
ul2
readonly ulong NUnit.Framework.Assertions.LessFixture.ul2 = 12345879 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
f1
readonly float NUnit.Framework.Assertions.LessFixture.f1 = 3.543F private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
f2
readonly float NUnit.Framework.Assertions.LessFixture.f2 = 8.543F private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
de1
readonly decimal NUnit.Framework.Assertions.LessFixture.de1 = 53.4M private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
de2
readonly decimal NUnit.Framework.Assertions.LessFixture.de2 = 83.4M private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
d1
readonly double NUnit.Framework.Assertions.LessFixture.d1 = 4.85948654 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
d2
readonly double NUnit.Framework.Assertions.LessFixture.d2 = 8.0 private
Referenced by NUnit.Framework.Assertions.LessFixture.Less().
e1
readonly System.Enum NUnit.Framework.Assertions.LessFixture.e1 = RunState.Explicit private
Referenced by NUnit.Framework.Assertions.LessFixture.NotLessIComparable().
e2
readonly System.Enum NUnit.Framework.Assertions.LessFixture.e2 = RunState.Ignored private
Referenced by NUnit.Framework.Assertions.LessFixture.NotLessIComparable().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/LessFixture.cs