Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualityAdapter.GenericEqualityAdapter< T > Class Template Reference
NUnit.Framework.Constraints.EqualityAdapter.GenericEqualityAdapter< T > Class Template Reference
Public Member Functions
override bool CanCompare (object x, object y)
Returns true if the two objects can be compared by this adapter. Generic adapter requires objects of the specified type.
Public Member Functions inherited from NUnit.Framework.Constraints.EqualityAdapter
abstract bool AreEqual (object x, object y)
Compares two objects, returning true if they are equal
Protected Member Functions
void ThrowIfNotCompatible (object x, object y)
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Constraints.EqualityAdapter
static EqualityAdapter For (IComparer comparer)
Returns an EqualityAdapter that wraps an IComparer.
static EqualityAdapter For (IEqualityComparer comparer)
Returns an EqualityAdapter that wraps an IEqualityComparer.
static EqualityAdapter For< T > (IEqualityComparer< T > comparer)
Returns an EqualityAdapter that wraps an IEqualityComparer<T>.
static EqualityAdapter For< T > (IComparer< T > comparer)
Returns an EqualityAdapter that wraps an IComparer<T>.
static EqualityAdapter For< T > (Comparison< T > comparer)
Returns an EqualityAdapter that wraps a Comparison<T>.
Member Function Documentation
CanCompare()
override bool NUnit.Framework.Constraints.EqualityAdapter.GenericEqualityAdapter< T >.CanCompare (object x, object y) inline virtual
Returns true if the two objects can be compared by this adapter. Generic adapter requires objects of the specified type.
Reimplemented from NUnit.Framework.Constraints.EqualityAdapter.
ThrowIfNotCompatible()
void NUnit.Framework.Constraints.EqualityAdapter.GenericEqualityAdapter< T >.ThrowIfNotCompatible (object x, object y) inline protected
Referenced by NUnit.Framework.Constraints.EqualityAdapter.EqualityComparerAdapter< T >.AreEqual(), NUnit.Framework.Constraints.EqualityAdapter.ComparerAdapter< T >.AreEqual(), and NUnit.Framework.Constraints.EqualityAdapter.ComparisonAdapter< T >.AreEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/EqualityAdapter.cs