Doc: IGLib EXTENDED: NUnit.Framework.Attributes.PairwiseTest.LiveTest Class Reference
NUnit.Framework.Attributes.PairwiseTest.LiveTest Class Reference
Public Member Functions
void TestFixtureSetUp ()
void TestFixtureTearDown ()
void Test ([Values("a", "b", "c")] string a, [Values("+", "-")] string b, [Values("x", "y")] string c)
Private Attributes
PairCounter pairsTested = new PairCounter()
Member Function Documentation
TestFixtureSetUp()
void NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureSetUp () inline
References NUnit.Framework.Attributes.PairwiseTest.LiveTest.pairsTested.
TestFixtureTearDown()
void NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureTearDown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.PairwiseTest.LiveTest.pairsTested, and NUnit.Framework.Assert.That().
Test()
void NUnit.Framework.Attributes.PairwiseTest.LiveTest.Test ([Values("a", "b", "c")] string a, [Values("+", "-")] string b, [Values("x", "y")] string c) inline
References NUnit.Framework.Attributes.PairwiseTest.LiveTest.pairsTested.
Member Data Documentation
pairsTested
PairCounter NUnit.Framework.Attributes.PairwiseTest.LiveTest.pairsTested = new PairCounter() private
Referenced by NUnit.Framework.Attributes.PairwiseTest.LiveTest.Test(), NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureSetUp(), and NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureTearDown().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/PairwiseTests.cs