Doc: IGLib EXTENDED: NUnit.Framework.Tests.Compatibility.AttributeHelperTests Class Reference
NUnit.Framework.Tests.Compatibility.AttributeHelperTests Class Reference
Classes
class A
class B
Public Member Functions
void CanGetAttributesOnAssemblies ()
void CanGetAttributesOnClasses ()
void CanGetAttributesOnDerivedClasses ()
void DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse ()
void CanGetAttributesOnMethods ()
void CanGetAttributesOnProperties ()
void CanGetAttributesOnFields ()
void CanGetAttributesOnParameters ()
Member Function Documentation
CanGetAttributesOnAssemblies()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnAssemblies () inline
References NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnClasses()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnClasses () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnDerivedClasses()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnDerivedClasses () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnMethods()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnMethods () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnProperties()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnProperties () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnFields()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnFields () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetAttributesOnParameters()
void NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnParameters () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Compatibility/AttributeHelperTests.cs