Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLABAD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLABAD Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLABAD ()
void Run (ref double SMALL, ref double LARGE)
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLABAD takes as input the values computed by DLAMCH for underflow and overflow, and returns the square root of each of these values if the log of LARGE is sufficiently large. This subroutine is intended to identify machines with a large exponent range, such as the Crays, and redefine the underflow and overflow limits to be the square roots of the values computed by DLAMCH. This subroutine is needed because DLAMCH does not compensate for poor arithmetic in the upper half of the exponent range, as is found on a Cray.
/summary>
Constructor & Destructor Documentation
DLABAD()
DotNumerics.LinearAlgebra.CSLapack.DLABAD.DLABAD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run (ref double SMALL, ref double LARGE) inline
Purpose
DLABAD takes as input the values computed by DLAMCH for underflow and overflow, and returns the square root of each of these values if the log of LARGE is sufficiently large. This subroutine is intended to identify machines with a large exponent range, such as the Crays, and redefine the underflow and overflow limits to be the square roots of the values computed by DLAMCH. This subroutine is needed because DLAMCH does not compensate for poor arithmetic in the upper half of the exponent range, as is found on a Cray.
/summary>
Parameters
SMALL (input/output) DOUBLE PRECISION On entry, the underflow threshold as computed by DLAMCH. On exit, if LOG10(LARGE) is sufficiently large, the square root of SMALL, otherwise unchanged. /param>
Parameters
LARGE (input/output) DOUBLE PRECISION On entry, the overflow threshold as computed by DLAMCH. On exit, if LOG10(LARGE) is sufficiently large, the square root of LARGE, otherwise unchanged. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlabad.cs