Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGESV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGESV Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGESV (DGETRF dgetrf, DGETRS dgetrs, XERBLA xerbla)
DGESV ()
void Run (int N, int NRHS, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO)
Private Attributes
DGETRF _dgetrf
DGETRS _dgetrs
XERBLA _xerbla
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGESV computes the solution to a real system of linear equations A * X = B, where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
The LU decomposition with partial pivoting and row interchanges is used to factor A as A = P * L * U, where P is a permutation matrix, L is unit lower triangular, and U is upper triangular. The factored form of A is then used to solve the system of equations A * X = B.
/summary>
Constructor & Destructor Documentation
DGESV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGESV.DGESV (DGETRF dgetrf, DGETRS dgetrs, XERBLA xerbla) inline
DGESV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGESV.DGESV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGESV.Run (int N, int NRHS, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO) inline
Purpose
DGESV computes the solution to a real system of linear equations A * X = B, where A is an N-by-N matrix and X and B are N-by-NRHS matrices.
The LU decomposition with partial pivoting and row interchanges is used to factor A as A = P * L * U, where P is a permutation matrix, L is unit lower triangular, and U is upper triangular. The factored form of A is then used to solve the system of equations A * X = B.
/summary>
Parameters
N (input) INTEGER The number of linear equations, i.e., the order of the matrix A. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrix B. NRHS .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the N-by-N coefficient matrix A. On exit, the factors L and U from the factorization A = P*L*U; the unit diagonal elements of L are not stored. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
IPIV (output) INTEGER array, dimension (N) The pivot indices that define the permutation matrix P; row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the N-by-NRHS matrix of right hand side matrix B. On exit, if INFO = 0, the N-by-NRHS solution matrix X. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, so the solution could not be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRS.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run().
Member Data Documentation
_dgetrf
DGETRF DotNumerics.LinearAlgebra.CSLapack.DGESV._dgetrf private
_dgetrs
DGETRS DotNumerics.LinearAlgebra.CSLapack.DGESV._dgetrs private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGESV._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgesv.cs