Doc: IGLib EXTENDED: NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher Class Reference
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher Class Reference
SimpleWorkItemDispatcher handles execution of WorkItems by directly executing them. It is provided so that a dispatcher is always available in the context, thereby simplifying the code needed to run child tests.
Public Member Functions
void Dispatch (WorkItem work)
Dispatch a single work item for execution. The first work item dispatched is saved as the top-level work item and a thread is created on which to run it. Subsequent calls come from the top level item or its descendants on the proper thread.
void CancelRun ()
Cancel the ongoing run completely. If no run is in process, the call has no effect.
Private Member Functions
void RunnerThreadProc ()
Private Attributes
WorkItem _topLevelWorkItem
Thread _runnerThread
Detailed Description
SimpleWorkItemDispatcher handles execution of WorkItems by directly executing them. It is provided so that a dispatcher is always available in the context, thereby simplifying the code needed to run child tests.
Member Function Documentation
Dispatch()
void NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch (WorkItem work) inline
Dispatch a single work item for execution. The first work item dispatched is saved as the top-level work item and a thread is created on which to run it. Subsequent calls come from the top level item or its descendants on the proper thread.
Parameters
work The item to dispatch
Implements NUnit.Framework.Internal.Execution.IWorkItemDispatcher.
References NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._runnerThread, NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._topLevelWorkItem, NUnit.Framework.Internal.Execution.WorkItem.Execute(), and NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.RunnerThreadProc().
RunnerThreadProc()
void NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.RunnerThreadProc () inline private
References NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._topLevelWorkItem, and NUnit.Framework.Internal.Execution.WorkItem.Execute().
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch().
CancelRun()
void NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.CancelRun () inline
Cancel the ongoing run completely. If no run is in process, the call has no effect.
Implements NUnit.Framework.Internal.Execution.IWorkItemDispatcher.
References NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._runnerThread, and NUnit.Framework.Internal.ThreadUtility.Kill().
Member Data Documentation
_topLevelWorkItem
WorkItem NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._topLevelWorkItem private
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(), and NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.RunnerThreadProc().
_runnerThread
Thread NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher._runnerThread private
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.CancelRun(), and NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItemDispatcher.cs