Doc: IGLib EXTENDED: IG.Neural.AnalysisFileServerNeuralStoreBase Class Reference
IG.Neural.AnalysisFileServerNeuralStoreBase Class Reference
Analysis server based on neural approximations for IJS, for Robert's data.
Public Member Functions
AnalysisFileServerNeuralStoreBase (string workingDirectory)
Public Member Functions inherited from IG.Neural.AnalysisFileServerNeural
AnalysisFileServerNeural (string workingDirectoryPath)
Constructor, sets object's working directory to the specified path.
virtual void Analyse (IAnalysisResults analysisData)
Performs analysis - calculates requested results and writes them to the provided data structure.
override void ClearMessages ()
Clears all messages in the neural network approximator's file client/server directory.
virtual void ServerAnalyse ()
Performs server-side direct analysis. Reads analysis input from standard location, calculates output and writes it to the standard location.
virtual void ClientCalculateAnalysisResults (AnalysisResults anRes)
Calculates analysis results by using the analysis server.
virtual void ClientTestCalculateAnalysisResults (string inputFilePath, bool reqObjective, bool reqConstraints, bool reqObjectiveGradient, bool reqConstraintGradients, string outputFilePath)
Performs client-side test calculation of analysis response.
Public Member Functions inherited from IG.Neural.ApproximationFileServerNeural
ApproximationFileServerNeural (string workingDirectoryPath)
virtual void ServerCalculateApproximation ()
Performs server-side calculation of the approximation. Reads input from standard location, calculates output and writes it to the standard location.
virtual void ClientCalculateApproximation (IVector input, ref IVector output)
Calculates the neural network based approximated values.
virtual void ClientTestCalculateApproximation (string inputFilePath, string outputFilePath)
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified JSON file, and calculated output values are written to the specified file.
Static Public Member Functions
static void InstallCommands_ijs_11_05 (ICommandLineApplicationInterpreter app)
Installs Tadejcommands for neural networks on the applications's command interpreter.
static string CmdAnalyseServer_ijs_11_05 (CommandThread thread, string cmdName, string[] args)
Command. Calculates approximation according to input parameters written in a file, and outputs resulting approximated values to a file.
static string CmdAnalyseClient_ijs_11_05 (CommandThread thread, string cmdName, string[] args)
Command. Sends request to a server to calculate an approximation.
Protected Member Functions
override void AnalysisToApproximationInput (IVector anInput, ref IVector approximationInput)
Converts analysis input parameters to approximation input parameters.
override void ApproximationToAnalysisOutput (IVector approxOutput, IAnalysisResults anResults)
Converts approximation output to direct analysis results.
Sets objective function to sum of squares of approximated values.
WARNING:
This method should be overridden in derived classes.
Additional Inherited Members
Properties inherited from IG.Neural.AnalysisFileServerNeural
OptFileManager OptimizationFileManager [get, set]
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Properties inherited from IG.Neural.ApproximationFileServerNeural
virtual string Directory [get, protected set]
Gets or sets working directory of the current object.
NeuraApproximationFileManager NeuralFileManager [get, set]
Properties inherited from IG.Num.IAnalysis
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Detailed Description
Analysis server based on neural approximations for IJS, for Robert's data.
Constructor & Destructor Documentation
AnalysisFileServerNeuralStoreBase()
IG.Neural.AnalysisFileServerNeuralStoreBase.AnalysisFileServerNeuralStoreBase (string workingDirectory) inline
Referenced by IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseClient_ijs_11_05(), and IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseServer_ijs_11_05().
Member Function Documentation
AnalysisToApproximationInput()
override void IG.Neural.AnalysisFileServerNeuralStoreBase.AnalysisToApproximationInput (IVector anInput, ref IVector approximationInput) inline protected virtual
Converts analysis input parameters to approximation input parameters.
Parameters
anInput Input parameters for direct analysis.
approximationInput Input parameters for response approximation.
Reimplemented from IG.Neural.AnalysisFileServerNeural.
References IG.Num.VectorBase.Copy().
ApproximationToAnalysisOutput()
override void IG.Neural.AnalysisFileServerNeuralStoreBase.ApproximationToAnalysisOutput (IVector approxOutput, IAnalysisResults anResults) inline protected virtual
Converts approximation output to direct analysis results.
Sets objective function to sum of squares of approximated values.
WARNING:
This method should be overridden in derived classes.
Parameters
approxOutput Vector of approximated output values.
anResults Direct analysis results.
Reimplemented from IG.Neural.AnalysisFileServerNeural.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.IAnalysisResults.Calculated, IG.Num.IAnalysisResults.CalculatedObjective, IG.Num.IVector< T >.Length, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath, IG.Neural.ApproximationFileServerNeural.NeuralFileManager, IG.Num.IAnalysisResults.NumConstraints, IG.Num.IAnalysisResults.NumObjectives, IG.Num.IAnalysisResults.Objective, IG.Num.IAnalysisResults.Parameters, IG.Num.IAnalysisResults.ReqObjective, and IG.Num.InputOutputElementDefinition.TargetValue.
InstallCommands_ijs_11_05()
static void IG.Neural.AnalysisFileServerNeuralStoreBase.InstallCommands_ijs_11_05 (ICommandLineApplicationInterpreter app) inline static
Installs Tadejcommands for neural networks on the applications's command interpreter.
References IG.Lib.ICommandLineApplicationInterpreter.AddCommand(), IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseClient_ijs_11_05(), and IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseServer_ijs_11_05().
Referenced by IG.Lib.MessyApplication.MessyApplication().
CmdAnalyseServer_ijs_11_05()
static string IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseServer_ijs_11_05 (CommandThread thread, string cmdName, string[] args) inline static
Command. Calculates approximation according to input parameters written in a file, and outputs resulting approximated values to a file.
Parameters
thread Interpreter thread on which commad is run.
cmdName Command name.
args Command arguments.
Returns
Null.
References IG.Neural.AnalysisFileServerNeuralStoreBase.AnalysisFileServerNeuralStoreBase(), IG.Num.OptFileManager.ClearAnBusy(), IG.Neural.NeuraApproximationFileManager.ClearNeuralBusy(), IG.Neural.ApproximationFileServerNeural.NeuralFileManager, IG.Neural.AnalysisFileServerNeural.OptimizationFileManager, IG.Neural.AnalysisFileServerNeural.ServerAnalyse(), IG.Num.OptFileManager.SetAnBusy(), IG.Num.OptFileManager.SetAnInputReady(), IG.Neural.NeuraApproximationFileManager.SetNeuralBusy(), and IG.Neural.NeuraApproximationFileManager.SetNeuralInputReady().
Referenced by IG.Neural.AnalysisFileServerNeuralStoreBase.InstallCommands_ijs_11_05().
CmdAnalyseClient_ijs_11_05()
static string IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseClient_ijs_11_05 (CommandThread thread, string cmdName, string[] args) inline static
Command. Sends request to a server to calculate an approximation.
Parameters
thread Interpreter thread on which commad is run.
cmdName Command name.
args Command arguments.
Returns
Null.
References IG.Neural.AnalysisFileServerNeuralStoreBase.AnalysisFileServerNeuralStoreBase(), IG.Neural.AnalysisFileServerNeural.ClientTestCalculateAnalysisResults(), and IG.Lib.UtilStr.ToBoolean().
Referenced by IG.Neural.AnalysisFileServerNeuralStoreBase.InstallCommands_ijs_11_05().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/ShellAppMess/servers/NeuralAnalysisFileServer_ijs_11_05.cs