Doc: IGLib EXTENDED: AForge.Math.Tools Class Reference
AForge.Math.Tools Class Reference
Set of tool functions.
Static Public Member Functions
static int Pow2 (int power)
Calculates power of 2.
static bool IsPowerOf2 (int x)
Checks if the specified integer is power of 2.
static int Log2 (int x)
Get base of binary logarithm.
Detailed Description
Set of tool functions.
The class contains different utility functions.
Member Function Documentation
Pow2()
static int AForge.Math.Tools.Pow2 (int power) inline static
Calculates power of 2.
Parameters
power Power to raise in.
Returns
Returns specified power of 2 in the case if power is in the range of [0, 30]. Otherwise returns 0.
Referenced by AForge.Math.FourierTransform.GetReversedBits().
IsPowerOf2()
static bool AForge.Math.Tools.IsPowerOf2 (int x) inline static
Checks if the specified integer is power of 2.
Parameters
x Integer number to check.
Returns
Returns true if the specified number is power of 2. Otherwise returns false.
Referenced by AForge.Math.FourierTransform.FFT2(), AForge.Imaging.ComplexImage.FromBitmap(), AForge.Math.Tests.ToolsTest.IsPowerOf2Test(), and AForge.Math.FourierTransform.ReorderData().
Log2()
static int AForge.Math.Tools.Log2 (int x) inline static
Get base of binary logarithm.
Parameters
x Source integer number.
Returns
Power of the number (base of binary logarithm).
Referenced by AForge.Math.FourierTransform.FFT(), and AForge.Math.FourierTransform.ReorderData().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Tools.cs