Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED1 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED1 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED1 (DCOPY dcopy, DLAED2 dlaed2, DLAED3 dlaed3, DLAMRG dlamrg, XERBLA xerbla)
DLAED1 ()
void Run (int N, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DCOPY _dcopy
DLAED2 _dlaed2
DLAED3 _dlaed3
DLAMRG _dlamrg
XERBLA _xerbla
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED1 computes the updated eigensystem of a diagonal matrix after modification by a rank-one symmetric matrix. This routine is used only for the eigenproblem which requires all eigenvalues and eigenvectors of a tridiagonal matrix. DLAED7 handles the case in which eigenvalues only or eigenvalues and eigenvectors of a full symmetric matrix (which was reduced to tridiagonal form) are desired.
T = Q(in) (D(in) + RHO * Z*Z') Q'(in) = Q(out) * D(out) * Q'(out)
where Z = Q'u, u is a vector of length N with ones in the CUTPNT and CUTPNT + 1 th elements and zeros elsewhere.
The eigenvectors of the original matrix are stored in Q, and the eigenvalues are in D. The algorithm consists of three stages:
The first stage consists of deflating the size of the problem when there are multiple eigenvalues or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLAED2.
The second stage consists of calculating the updated eigenvalues. This is done by finding the roots of the secular equation via the routine DLAED4 (as called by DLAED3). This routine also calculates the eigenvectors of the current problem.
The final stage consists of computing the updated eigenvectors directly using the updated eigenvalues. The eigenvectors for the current problem are multiplied with the eigenvectors from the overall problem.
/summary>
Constructor & Destructor Documentation
DLAED1() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED1.DLAED1 (DCOPY dcopy, DLAED2 dlaed2, DLAED3 dlaed3, DLAMRG dlamrg, XERBLA xerbla) inline
DLAED1() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED1.DLAED1 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run (int N, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLAED1 computes the updated eigensystem of a diagonal matrix after modification by a rank-one symmetric matrix. This routine is used only for the eigenproblem which requires all eigenvalues and eigenvectors of a tridiagonal matrix. DLAED7 handles the case in which eigenvalues only or eigenvalues and eigenvectors of a full symmetric matrix (which was reduced to tridiagonal form) are desired.
T = Q(in) (D(in) + RHO * Z*Z') Q'(in) = Q(out) * D(out) * Q'(out)
where Z = Q'u, u is a vector of length N with ones in the CUTPNT and CUTPNT + 1 th elements and zeros elsewhere.
The eigenvectors of the original matrix are stored in Q, and the eigenvalues are in D. The algorithm consists of three stages:
The first stage consists of deflating the size of the problem when there are multiple eigenvalues or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLAED2.
The second stage consists of calculating the updated eigenvalues. This is done by finding the roots of the secular equation via the routine DLAED4 (as called by DLAED3). This routine also calculates the eigenvectors of the current problem.
The final stage consists of computing the updated eigenvectors directly using the updated eigenvalues. The eigenvectors for the current problem are multiplied with the eigenvectors from the overall problem.
/summary>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the eigenvalues of the rank-1-perturbed matrix. On exit, the eigenvalues of the repaired matrix. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) On entry, the eigenvectors of the rank-1-perturbed matrix. On exit, the eigenvectors of the repaired tridiagonal matrix. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
INDXQ (input/output) INTEGER array, dimension (N) On entry, the permutation which separately sorts the two subproblems in D into ascending order. On exit, the permutation which will reintegrate the subproblems back into sorted order, i.e. D(INDXQ(I = 1, N)) will be in ascending order. /param>
Parameters
RHO (input) DOUBLE PRECISION The subdiagonal entry used to create the rank-1 modification. /param>
Parameters
CUTPNT (input) INTEGER The location of the last eigenvalue in the leading sub-matrix. min(1,N) .LE. CUTPNT .LE. N/2. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (4*N + N**2) /param>
Parameters
IWORK (workspace) INTEGER array, dimension (4*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an eigenvalue did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED1._dcopy private
_dlaed2
DLAED2 DotNumerics.LinearAlgebra.CSLapack.DLAED1._dlaed2 private
_dlaed3
DLAED3 DotNumerics.LinearAlgebra.CSLapack.DLAED1._dlaed3 private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLAED1._dlamrg private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED1._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed1.cs