Doc: IGLib EXTENDED: MotionDetectorSample.DefineRegionsControl Class Reference
MotionDetectorSample.DefineRegionsControl Class Reference
Public Member Functions
DefineRegionsControl ()
void RemoveAllRegions ()
Protected Member Functions
override void OnPaint (PaintEventArgs pe)
override void OnMouseDown (MouseEventArgs e)
override void OnMouseUp (MouseEventArgs e)
override void OnMouseMove (MouseEventArgs e)
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
new Bitmap BackgroundImage [get, set]
DrawingMode? DrawingMode [get, set]
Rectangle[] Rectangles [get, set]
Events
NewRectangleHandler OnNewRectangle
Private Member Functions
void DrawSelectionRectangle ()
void NormalizePoints (ref Point point1, ref Point point2)
void CheckPointsInClient (ref Point point)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Color borderColor = Color.Black
Color backColor = Color.FromArgb(96, 96, 96)
Color selectionColor = Color.Yellow
Color rectsColor = Color.FromArgb(0, 255, 0)
Bitmap backImage = null
List< Rectangle > rectangles = new List<Rectangle>()
DrawingMode drawingMode = DrawingMode.None
bool dragging = false
Point startPoint
Point endPoint
System.ComponentModel.IContainer components = null
Required designer variable.
Constructor & Destructor Documentation
DefineRegionsControl()
MotionDetectorSample.DefineRegionsControl.DefineRegionsControl () inline
References MotionDetectorSample.DefineRegionsControl.InitializeComponent().
Member Function Documentation
RemoveAllRegions()
void MotionDetectorSample.DefineRegionsControl.RemoveAllRegions () inline
References MotionDetectorSample.DefineRegionsControl.rectangles.
Referenced by MotionDetectorSample.MotionRegionsForm.clearButton_Click().
OnPaint()
override void MotionDetectorSample.DefineRegionsControl.OnPaint (PaintEventArgs pe) inline protected
References MotionDetectorSample.DefineRegionsControl.backColor, MotionDetectorSample.DefineRegionsControl.backImage, MotionDetectorSample.DefineRegionsControl.borderColor, MotionDetectorSample.DefineRegionsControl.rectangles, and MotionDetectorSample.DefineRegionsControl.rectsColor.
OnMouseDown()
override void MotionDetectorSample.DefineRegionsControl.OnMouseDown (MouseEventArgs e) inline protected
References MotionDetectorSample.DefineRegionsControl.dragging, MotionDetectorSample.DefineRegionsControl.drawingMode, MotionDetectorSample.DefineRegionsControl.endPoint, and MotionDetectorSample.DefineRegionsControl.startPoint.
OnMouseUp()
override void MotionDetectorSample.DefineRegionsControl.OnMouseUp (MouseEventArgs e) inline protected
References MotionDetectorSample.DefineRegionsControl.CheckPointsInClient(), MotionDetectorSample.DefineRegionsControl.dragging, MotionDetectorSample.DefineRegionsControl.drawingMode, MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), MotionDetectorSample.DefineRegionsControl.endPoint, MotionDetectorSample.DefineRegionsControl.NormalizePoints(), MotionDetectorSample.DefineRegionsControl.OnNewRectangle, MotionDetectorSample.DefineRegionsControl.rectangles, and MotionDetectorSample.DefineRegionsControl.startPoint.
OnMouseMove()
override void MotionDetectorSample.DefineRegionsControl.OnMouseMove (MouseEventArgs e) inline protected
References MotionDetectorSample.DefineRegionsControl.dragging, MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), and MotionDetectorSample.DefineRegionsControl.endPoint.
DrawSelectionRectangle()
void MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle () inline private
References MotionDetectorSample.DefineRegionsControl.CheckPointsInClient(), MotionDetectorSample.DefineRegionsControl.endPoint, MotionDetectorSample.DefineRegionsControl.NormalizePoints(), MotionDetectorSample.DefineRegionsControl.selectionColor, and MotionDetectorSample.DefineRegionsControl.startPoint.
Referenced by MotionDetectorSample.DefineRegionsControl.OnMouseMove(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
NormalizePoints()
void MotionDetectorSample.DefineRegionsControl.NormalizePoints (ref Point point1, ref Point point2) inline private
References AForge.Point.X.
Referenced by MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
CheckPointsInClient()
void MotionDetectorSample.DefineRegionsControl.CheckPointsInClient (ref Point point) inline private
Referenced by MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
Dispose()
override void MotionDetectorSample.DefineRegionsControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References MotionDetectorSample.DefineRegionsControl.components.
InitializeComponent()
void MotionDetectorSample.DefineRegionsControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References MotionDetectorSample.DefineRegionsControl.components.
Referenced by MotionDetectorSample.DefineRegionsControl.DefineRegionsControl().
Member Data Documentation
borderColor
Color MotionDetectorSample.DefineRegionsControl.borderColor = Color.Black private
Referenced by MotionDetectorSample.DefineRegionsControl.OnPaint().
backColor
Color MotionDetectorSample.DefineRegionsControl.backColor = Color.FromArgb(96, 96, 96) private
Referenced by MotionDetectorSample.DefineRegionsControl.OnPaint().
selectionColor
Color MotionDetectorSample.DefineRegionsControl.selectionColor = Color.Yellow private
Referenced by MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle().
rectsColor
Color MotionDetectorSample.DefineRegionsControl.rectsColor = Color.FromArgb(0, 255, 0) private
Referenced by MotionDetectorSample.DefineRegionsControl.OnPaint().
backImage
Bitmap MotionDetectorSample.DefineRegionsControl.backImage = null private
Referenced by MotionDetectorSample.DefineRegionsControl.OnPaint().
rectangles
List<Rectangle> MotionDetectorSample.DefineRegionsControl.rectangles = new List<Rectangle>() private
Referenced by MotionDetectorSample.DefineRegionsControl.OnMouseUp(), MotionDetectorSample.DefineRegionsControl.OnPaint(), and MotionDetectorSample.DefineRegionsControl.RemoveAllRegions().
drawingMode
DrawingMode MotionDetectorSample.DefineRegionsControl.drawingMode = DrawingMode.None private
Referenced by MotionDetectorSample.DefineRegionsControl.OnMouseDown(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
dragging
bool MotionDetectorSample.DefineRegionsControl.dragging = false private
Referenced by MotionDetectorSample.DefineRegionsControl.OnMouseDown(), MotionDetectorSample.DefineRegionsControl.OnMouseMove(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
startPoint
Point MotionDetectorSample.DefineRegionsControl.startPoint private
Referenced by MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), MotionDetectorSample.DefineRegionsControl.OnMouseDown(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
endPoint
Point MotionDetectorSample.DefineRegionsControl.endPoint private
Referenced by MotionDetectorSample.DefineRegionsControl.DrawSelectionRectangle(), MotionDetectorSample.DefineRegionsControl.OnMouseDown(), MotionDetectorSample.DefineRegionsControl.OnMouseMove(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
components
System.ComponentModel.IContainer MotionDetectorSample.DefineRegionsControl.components = null private
Required designer variable.
Referenced by MotionDetectorSample.DefineRegionsControl.Dispose(), and MotionDetectorSample.DefineRegionsControl.InitializeComponent().
Property Documentation
BackgroundImage
new Bitmap MotionDetectorSample.DefineRegionsControl.BackgroundImage get set
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent(), and MotionDetectorSample.MotionRegionsForm.OnLoad().
DrawingMode
DrawingMode? MotionDetectorSample.DefineRegionsControl.DrawingMode get set
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent(), and MotionDetectorSample.MotionRegionsForm.rectangleButton_Click().
Rectangles
Rectangle [] MotionDetectorSample.DefineRegionsControl.Rectangles get set
Event Documentation
OnNewRectangle
NewRectangleHandler MotionDetectorSample.DefineRegionsControl.OnNewRectangle
Referenced by MotionDetectorSample.MotionRegionsForm.MotionRegionsForm(), and MotionDetectorSample.DefineRegionsControl.OnMouseUp().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/DefineRegionsControl.cs
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/DefineRegionsControl.Designer.cs