Doc: IGLib EXTENDED: UsingConfigurationClass Class Reference
UsingConfigurationClass Class Reference
Classes
class ConfigurationMain
Static Private Member Functions
static void CreateConfigurationFile ()
static void GetCustomSection ()
static void SaveConfigurationFile ()
static void GetSections (string section)
static void GetConfigurationInformation ()
Member Function Documentation
CreateConfigurationFile()
static void UsingConfigurationClass.CreateConfigurationFile () inline static private
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
GetCustomSection()
static void UsingConfigurationClass.GetCustomSection () inline static private
References CustomSection.Name, CustomSection.Port, and CustomSection.Url.
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
SaveConfigurationFile()
static void UsingConfigurationClass.SaveConfigurationFile () inline static private
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
GetSections()
static void UsingConfigurationClass.GetSections (string section) inline static private
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
GetConfigurationInformation()
static void UsingConfigurationClass.GetConfigurationInformation () inline static private
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/Configuration.cs