Doc: IGLib EXTENDED: IG.Crypt.pfx_certificates Class Reference
IG.Crypt.pfx_certificates Class Reference
Public Member Functions
string GetEncryptedText (string PlainStringToEncrypt, string DigitalCertificateName)
Constructor Author : Ranajit Biswal Date : 24th May 2007 Pupose : Used to Encrypt and Decrypt string using Digital certificate which has a Private Key. Requirement : WSE 2.0 and .Net Framework 2.0
string GetDecryptedText (string EncryptedStringToDecrypt, string DigitalCertificateName)
To Decrypt clear text using RSACryptoServer Provider and Digital Certificate having Private Key.
Static Public Member Functions
static X509Certificate2 LoadCertificate (StoreName storeName, StoreLocation storeLocation, string certificateName)
static byte[] DecryptByCert (byte[] encryptedData, bool fOAEP, X509Certificate2 certificate)
static byte[] EncryptByCert (byte[] plainData, bool fOAEP, X509Certificate2 certificate)
static string GetXmlKeyPair (X509Certificate2 certificate)
static string GetPublicKey (X509Certificate2 certificate)
static void UseCertificateDemo ()
static string DecryptEncryptedData (string Base64EncryptedData, string PathToPrivateKeyFile)
Static Private Member Functions
static byte[] Sign (string text, string certSubject)
static bool Verify (string text, byte[] signature, string certPath)
static void CertSignTest ()
Member Function Documentation
LoadCertificate()
static X509Certificate2 IG.Crypt.pfx_certificates.LoadCertificate (StoreName storeName, StoreLocation storeLocation, string certificateName) inline static
Referenced by IG.Crypt.pfx_certificates.UseCertificateDemo().
DecryptByCert()
static byte [] IG.Crypt.pfx_certificates.DecryptByCert (byte[] encryptedData, bool fOAEP, X509Certificate2 certificate) inline static
References IG.Crypt.pfx_certificates.GetXmlKeyPair().
Referenced by IG.Crypt.pfx_certificates.UseCertificateDemo().
EncryptByCert()
static byte [] IG.Crypt.pfx_certificates.EncryptByCert (byte[] plainData, bool fOAEP, X509Certificate2 certificate) inline static
References IG.Crypt.pfx_certificates.GetPublicKey().
Referenced by IG.Crypt.pfx_certificates.UseCertificateDemo().
GetXmlKeyPair()
static string IG.Crypt.pfx_certificates.GetXmlKeyPair (X509Certificate2 certificate) inline static
Referenced by IG.Crypt.pfx_certificates.DecryptByCert().
GetPublicKey()
static string IG.Crypt.pfx_certificates.GetPublicKey (X509Certificate2 certificate) inline static
Referenced by IG.Crypt.pfx_certificates.EncryptByCert().
UseCertificateDemo()
static void IG.Crypt.pfx_certificates.UseCertificateDemo () inline static
References IG.Crypt.pfx_certificates.DecryptByCert(), IG.Crypt.pfx_certificates.EncryptByCert(), and IG.Crypt.pfx_certificates.LoadCertificate().
GetEncryptedText()
string IG.Crypt.pfx_certificates.GetEncryptedText (string PlainStringToEncrypt, string DigitalCertificateName) inline
Constructor Author : Ranajit Biswal Date : 24th May 2007 Pupose : Used to Encrypt and Decrypt string using Digital certificate which has a Private Key. Requirement : WSE 2.0 and .Net Framework 2.0
GetDecryptedText()
string IG.Crypt.pfx_certificates.GetDecryptedText (string EncryptedStringToDecrypt, string DigitalCertificateName) inline
To Decrypt clear text using RSACryptoServer Provider and Digital Certificate having Private Key.
Parameters
EncryptedStringToDecrypt
Returns
DecryptEncryptedData()
static string IG.Crypt.pfx_certificates.DecryptEncryptedData (string Base64EncryptedData, string PathToPrivateKeyFile) inline static
Sign()
static byte [] IG.Crypt.pfx_certificates.Sign (string text, string certSubject) inline static private
Referenced by IG.Crypt.pfx_certificates.CertSignTest().
Verify()
static bool IG.Crypt.pfx_certificates.Verify (string text, byte[] signature, string certPath) inline static private
Referenced by IG.Crypt.pfx_certificates.CertSignTest().
CertSignTest()
static void IG.Crypt.pfx_certificates.CertSignTest () inline static private
References IG.Crypt.pfx_certificates.Sign(), and IG.Crypt.pfx_certificates.Verify().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/encryption_test.cs