Doc: IGLib EXTENDED: IG.Forms.AssemblyInfoForm Class Reference
IG.Forms.AssemblyInfoForm Class Reference
Public Member Functions
AssemblyInfoForm ()
AssemblyInfoForm ()
AssemblyInfoForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
AssemblyInfoControl assemblyInfoControl1
Constructor & Destructor Documentation
AssemblyInfoForm() [1/3]
IG.Forms.AssemblyInfoForm.AssemblyInfoForm () inline
References IG.Forms.AssemblyInfoForm.InitializeComponent().
AssemblyInfoForm() [2/3]
IG.Forms.AssemblyInfoForm.AssemblyInfoForm () inline
References IG.Forms.AssemblyInfoForm.InitializeComponent().
AssemblyInfoForm() [3/3]
IG.Forms.AssemblyInfoForm.AssemblyInfoForm () inline
References IG.Forms.AssemblyInfoForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.AssemblyInfoForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AssemblyInfoForm.components.
InitializeComponent() [1/3]
void IG.Forms.AssemblyInfoForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AssemblyInfoForm.assemblyInfoControl1.
Referenced by IG.Forms.AssemblyInfoForm.AssemblyInfoForm().
Dispose() [2/3]
override void IG.Forms.AssemblyInfoForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AssemblyInfoForm.components.
InitializeComponent() [2/3]
void IG.Forms.AssemblyInfoForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AssemblyInfoForm.assemblyInfoControl1.
Dispose() [3/3]
override void IG.Forms.AssemblyInfoForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AssemblyInfoForm.components.
InitializeComponent() [3/3]
void IG.Forms.AssemblyInfoForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AssemblyInfoForm.assemblyInfoControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.AssemblyInfoForm.components = null private
Required designer variable.
Referenced by IG.Forms.AssemblyInfoForm.Dispose().
assemblyInfoControl1
AssemblyInfoControl IG.Forms.AssemblyInfoForm.assemblyInfoControl1 private
Referenced by IG.Forms.AssemblyInfoForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/AssemblyInfoForm.cs
iglib/igforms/Utilities/Viewers/AssemblyInfoForm.Designer.cs