Doc: IGLib EXTENDED: NUnit.Framework.DirectoryAssert Class Reference
NUnit.Framework.DirectoryAssert Class Reference
Asserts on Directories
Static Public Member Functions
static new bool Equals (object a, object b)
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
static new void ReferenceEquals (object a, object b)
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
static void AreEqual (DirectoryInfo expected, DirectoryInfo actual, string message, params object[] args)
Verifies that two directories are equal. Two directories are considered equal if both are null, or if both point to the same directory. If they are not equal an AssertionException is thrown.
static void AreEqual (DirectoryInfo expected, DirectoryInfo actual)
Verifies that two directories are equal. Two directories are considered equal if both are null, or if both point to the same directory. If they are not equal an AssertionException is thrown.
static void AreNotEqual (DirectoryInfo expected, DirectoryInfo actual, string message, params object[] args)
Asserts that two directories are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (DirectoryInfo expected, DirectoryInfo actual)
Asserts that two directories are not equal. If they are equal an AssertionException is thrown.
static void Exists (DirectoryInfo actual, string message, params object[] args)
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
static void Exists (DirectoryInfo actual)
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
static void Exists (string actual, string message, params object[] args)
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
static void Exists (string actual)
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
static void DoesNotExist (DirectoryInfo actual, string message, params object[] args)
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (DirectoryInfo actual)
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (string actual, string message, params object[] args)
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (string actual)
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
Detailed Description
Asserts on Directories
Member Function Documentation
Equals()
static new bool NUnit.Framework.DirectoryAssert.Equals (object a, object b) inline static
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
Parameters
a
b
ReferenceEquals()
static new void NUnit.Framework.DirectoryAssert.ReferenceEquals (object a, object b) inline static
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
Parameters
a
b
AreEqual() [1/2]
static void NUnit.Framework.DirectoryAssert.AreEqual (DirectoryInfo expected, DirectoryInfo actual, string message, params object[] args) inline static
Verifies that two directories are equal. Two directories are considered equal if both are null, or if both point to the same directory. If they are not equal an AssertionException is thrown.
Parameters
expected A directory containing the value that is expected
actual A directory containing the actual value
message The message to display if the directories are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.DirectoryAssert.AreEqual(), NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos(), and NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualPassesWithDirectoryInfos().
AreEqual() [2/2]
static void NUnit.Framework.DirectoryAssert.AreEqual (DirectoryInfo expected, DirectoryInfo actual) inline static
Verifies that two directories are equal. Two directories are considered equal if both are null, or if both point to the same directory. If they are not equal an AssertionException is thrown.
Parameters
expected A directory containing the value that is expected
actual A directory containing the actual value
References NUnit.Framework.DirectoryAssert.AreEqual().
AreNotEqual() [1/2]
static void NUnit.Framework.DirectoryAssert.AreNotEqual (DirectoryInfo expected, DirectoryInfo actual, string message, params object[] args) inline static
Asserts that two directories are not equal. If they are equal an AssertionException is thrown.
Parameters
expected A directory containing the value that is expected
actual A directory containing the actual value
message The message to display if directories are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.DirectoryAssert.AreNotEqual(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfActualIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfExpectedIsNull(), and NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesWithDirectoryInfos().
AreNotEqual() [2/2]
static void NUnit.Framework.DirectoryAssert.AreNotEqual (DirectoryInfo expected, DirectoryInfo actual) inline static
Asserts that two directories are not equal. If they are equal an AssertionException is thrown.
Parameters
expected A directory containing the value that is expected
actual A directory containing the actual value
References NUnit.Framework.DirectoryAssert.AreNotEqual().
Exists() [1/4]
static void NUnit.Framework.DirectoryAssert.Exists (DirectoryInfo actual, string message, params object[] args) inline static
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
Parameters
actual A directory containing the actual value
message The message to display if directories are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenDirectoryInfoExists(), and NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenStringExists().
Exists() [2/4]
static void NUnit.Framework.DirectoryAssert.Exists (DirectoryInfo actual) inline static
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
Parameters
actual A directory containing the actual value
References NUnit.Framework.DirectoryAssert.Exists().
Exists() [3/4]
static void NUnit.Framework.DirectoryAssert.Exists (string actual, string message, params object[] args) inline static
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
Parameters
actual The path to a directory containing the actual value
message The message to display if directories are not equal
args Arguments to be used in formatting the message
Exists() [4/4]
static void NUnit.Framework.DirectoryAssert.Exists (string actual) inline static
Asserts that the directory exists. If it does not exist an AssertionException is thrown.
Parameters
actual The path to a directory containing the actual value
References NUnit.Framework.DirectoryAssert.Exists().
DoesNotExist() [1/4]
static void NUnit.Framework.DirectoryAssert.DoesNotExist (DirectoryInfo actual, string message, params object[] args) inline static
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
Parameters
actual A directory containing the actual value
message The message to display if directories are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistPassesWhenDirectoryInfoDoesNotExist(), and NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistPassesWhenStringDoesNotExist().
DoesNotExist() [2/4]
static void NUnit.Framework.DirectoryAssert.DoesNotExist (DirectoryInfo actual) inline static
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
Parameters
actual A directory containing the actual value
References NUnit.Framework.DirectoryAssert.DoesNotExist().
DoesNotExist() [3/4]
static void NUnit.Framework.DirectoryAssert.DoesNotExist (string actual, string message, params object[] args) inline static
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
Parameters
actual The path to a directory containing the actual value
message The message to display if directories are not equal
args Arguments to be used in formatting the message
DoesNotExist() [4/4]
static void NUnit.Framework.DirectoryAssert.DoesNotExist (string actual) inline static
Asserts that the directory does not exist. If it does exist an AssertionException is thrown.
Parameters
actual The path to a directory containing the actual value
References NUnit.Framework.DirectoryAssert.DoesNotExist().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/DirectoryAssert.cs