Doc: IGLib EXTENDED: alglib.corr Class Reference
alglib.corr Class Reference
Static Public Member Functions
static void corrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void corrc1dcircular (complex[] signal, int m, complex[] pattern, int n, ref complex[] c)
static void corrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void corrr1dcircular (double[] signal, int m, double[] pattern, int n, ref double[] c)
static void corrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void corrc1dcircular (complex[] signal, int m, complex[] pattern, int n, ref complex[] c)
static void corrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void corrr1dcircular (double[] signal, int m, double[] pattern, int n, ref double[] c)
Member Function Documentation
corrc1d() [1/2]
static void alglib.corr.corrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static
References alglib.ap.assert(), alglib.math.conj(), and alglib.conv.convc1d().
Referenced by alglib.corrc1d(), and alglib.testcorrunit.testcorr().
corrc1dcircular() [1/2]
static void alglib.corr.corrc1dcircular (complex[] signal, int m, complex[] pattern, int n, ref complex[] c) inline static
References alglib.ap.assert(), alglib.math.conj(), and alglib.conv.convc1dcircular().
Referenced by alglib.corrc1dcircular(), alglib.corr.corrc1dcircular(), and alglib.testcorrunit.testcorr().
corrr1d() [1/2]
static void alglib.corr.corrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static
References alglib.ap.assert(), and alglib.conv.convr1d().
Referenced by alglib.corrr1d(), and alglib.testcorrunit.testcorr().
corrr1dcircular() [1/2]
static void alglib.corr.corrr1dcircular (double[] signal, int m, double[] pattern, int n, ref double[] c) inline static
References alglib.ap.assert(), and alglib.conv.convr1dcircular().
Referenced by alglib.corrr1dcircular(), alglib.corr.corrr1dcircular(), and alglib.testcorrunit.testcorr().
corrc1d() [2/2]
static void alglib.corr.corrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static
References alglib.ap.assert(), alglib.math.conj(), and alglib.conv.convc1d().
corrc1dcircular() [2/2]
static void alglib.corr.corrc1dcircular (complex[] signal, int m, complex[] pattern, int n, ref complex[] c) inline static
References alglib.ap.assert(), alglib.math.conj(), alglib.conv.convc1dcircular(), and alglib.corr.corrc1dcircular().
corrr1d() [2/2]
static void alglib.corr.corrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static
References alglib.ap.assert(), and alglib.conv.convr1d().
corrr1dcircular() [2/2]
static void alglib.corr.corrr1dcircular (double[] signal, int m, double[] pattern, int n, ref double[] c) inline static
References alglib.ap.assert(), alglib.conv.convr1dcircular(), and alglib.corr.corrr1dcircular().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/fasttransforms.cs