Doc: IGLib EXTENDED: NUnit.Framework.Internal.StringUtil Class Reference
NUnit.Framework.Internal.StringUtil Class Reference
Provides methods to support legacy string comparison methods.
Static Public Member Functions
static int Compare (string strA, string strB, bool ignoreCase)
Compares two strings for equality, ignoring case if requested.
static bool StringsEqual (string strA, string strB, bool ignoreCase)
Compares two strings for equality, ignoring case if requested.
Detailed Description
Provides methods to support legacy string comparison methods.
Member Function Documentation
Compare()
static int NUnit.Framework.Internal.StringUtil.Compare (string strA, string strB, bool ignoreCase) inline static
Compares two strings for equality, ignoring case if requested.
Parameters
strA The first string.
strB The second string..
ignoreCase if set to true, the case of the letters in the strings is ignored.
Returns
Zero if the strings are equivalent, a negative number if strA is sorted first, a positive number if strB is sorted first
Referenced by NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentHonorsUsing(), NUnit.Framework.Internal.StringUtil.StringsEqual(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_StringArgs(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.UsingIsHonored(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.UsingIsHonored(), and NUnit.Framework.Constraints.CollectionContainsConstraintTests.UsingIsHonored().
StringsEqual()
static bool NUnit.Framework.Internal.StringUtil.StringsEqual (string strA, string strB, bool ignoreCase) inline static
Compares two strings for equality, ignoring case if requested.
Parameters
strA The first string.
strB The second string..
ignoreCase if set to true, the case of the letters in the strings is ignored.
Returns
True if the strings are equivalent, false if not.
References NUnit.Framework.Internal.StringUtil.Compare().
Referenced by NUnit.Framework.Constraints.PathConstraint.IsSubPath(), NUnit.Framework.Constraints.SamePathOrUnderConstraint.Matches(), and NUnit.Framework.Constraints.SamePathConstraint.Matches().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/StringUtil.cs