Doc: IGLib EXTENDED: AForge.Robotics.Lego.NXTBrick Class Reference
AForge.Robotics.Lego.NXTBrick Class Reference
Manipulation of Lego Mindstorms NXT device.
Classes
class MotorState
Class describing motor's state.
class SensorValues
Class describing sensor's values received from NXT brick's sensor port.
Public Types
enum Sensor { Sensor.First, Sensor.Second, Sensor.Third, Sensor.Fourth }
Enumeration of NXT brick sensor ports.
enum SensorType {
SensorType.NoSensor = 0x00, SensorType.Switch = 0x01, SensorType.Temperature = 0x02, SensorType.Reflection = 0x03,
SensorType.Angle = 0x04, SensorType.LightActive = 0x05, SensorType.LightInactive = 0x06, SensorType.SoundDB = 0x07,
SensorType.SoundDBA = 0x08, SensorType.Custom = 0x09, SensorType.Lowspeed = 0x0A, SensorType.Lowspeed9V = 0x0B,
SensorType.Highspeed = 0x0C, SensorType.ColorFull = 0x0D, SensorType.ColorRed = 0x0E, SensorType.ColorGreen = 0x0F,
SensorType.ColorBlue = 0x10, SensorType.ColorNone = 0x11, SensorType.ColorExit = 0x12
}
Enumeration of NXT brick sensor types.
enum SensorMode {
SensorMode.Raw = 0x00, SensorMode.Boolean = 0x20, SensorMode.TransitionCounter = 0x40, SensorMode.PeriodicCounter = 0x60,
SensorMode.PCTFullScale = 0x80, SensorMode.Celsius = 0xA0, SensorMode.Fahrenheit = 0xC0, SensorMode.AngleSteps = 0xE0
}
Enumeration of NXT brick sensor modes.
enum Motor { Motor.A = 0x00, Motor.B = 0x01, Motor.C = 0x02, Motor.All = 0xFF }
Enumeration of NXT brick motor ports.
enum MotorMode { MotorMode.None = 0x00, MotorMode.On = 0x01, MotorMode.Brake = 0x02, MotorMode.Regulated = 0x04 }
Enumeration of supported motor modes.
enum MotorRegulationMode { MotorRegulationMode.Idle = 0x00, MotorRegulationMode.Speed = 0x01, MotorRegulationMode.Sync = 0x02 }
Enumeration of motor regulation modes.
enum MotorRunState { MotorRunState.Idle = 0x00, MotorRunState.RampUp = 0x10, MotorRunState.Running = 0x20, MotorRunState.RampDown = 0x40 }
Enumeration of motor run states.
Public Member Functions
NXTBrick ()
Initializes a new instance of the NXTBrick class.
bool Connect (string portName)
Connect to NXT brick.
void Disconnect ()
Disconnect from Lego NXT brick.
bool IsAlive ()
Check if the NXT brick is alive and responds to messages.
bool PlayTone (short frequency, short duration)
Play tone of specified frequency.
bool PlayTone (short frequency, short duration, bool waitReply)
Play tone of specified frequency.
bool GetVersion (out string protocolVersion, out string firmwareVersion)
Get firmware version of NXT brick.
bool GetDeviceInformation (out string deviceName, out byte[] btAddress, out int btSignalStrength, out int freeUserFlash)
Get information about NXT device.
bool GetBatteryPower (out int power)
Get battery power of NXT brick.
bool SetBrickName (string deviceName)
Set name of NXT device.
bool ResetMotorPosition (Motor motor, bool relative)
Reset motor's position.
bool ResetMotorPosition (Motor motor, bool relative, bool waitReply)
Reset motor's position.
bool SetMotorState (Motor motor, MotorState state)
Set motor state.
bool SetMotorState (Motor motor, MotorState state, bool waitReply)
Set motor state.
bool GetMotorState (Motor motor, out MotorState state)
Get motor state.
bool SetSensorMode (Sensor sensor, SensorType type, SensorMode mode)
Set sensor's type and mode.
bool SetSensorMode (Sensor sensor, SensorType type, SensorMode mode, bool waitReply)
Set sensor's type and mode.
bool GetSensorValue (Sensor sensor, out SensorValues sensorValues)
Get sensor's values.
bool ClearSensor (Sensor sensor)
Clear sensor's scaled value.
bool ClearSensor (Sensor sensor, bool waitReply)
Clear sensor's scaled value.
bool LsGetStatus (Sensor sensor, out int readyBytes)
Get status of Low Speed bus.
bool LsWrite (Sensor sensor, byte[] data, int expectedBytes)
Write to Low Speed bus.
bool LsWrite (Sensor sensor, byte[] data, int expectedBytes, bool waitReply)
Write to Low Speed bus.
bool LsRead (Sensor sensor, byte[] readValues, out int bytesRead)
Read data from Low Speed bus.
bool GetUltrasonicSensorsValue (Sensor sensor, out int value)
Read value of ultrasonic distance sensor.
bool SendCommand (byte[] command, byte[] reply)
Send command to Lego NXT brick and read reply.
bool ReadHiTechnicColorSensor (NXTBrick.Sensor sensor, ref int colorNumber, ref int redValue, ref int greenValue, ref int blueValue)
Read data from HiTechnic color sensor (also color sensor v2).
bool ReadHiTechnicCompassSensor (NXTBrick.Sensor sensor, ref int angle)
Read data from HiTechnic compass sensor.
bool ReadHiTechnicAccelerationTiltSensor (NXTBrick.Sensor sensor, ref int xAceeleration, ref int yAceeleration, ref int zAceeleration)
Read data from HiTechnic acceleration/tilt sensor. The HiTechnic accelerometer/tilt sensor measures acceleration in three axes. It measures also tilt along each axis. Using the sensor, you can measure the acceleration of your robot in the range of -2g to 2g.
Properties
bool IsConnected [get]
Check if connection to NXT brick is established.
Events
MessageTransferHandler MessageSent
The event is raised every time a command is sent successfully.
MessageTransferHandler MessageRead
The event is raised every time a command is read successfully.
Private Member Functions
~NXTBrick ()
Destroys the instance of the NXTBrick class.
Private Attributes
INXTCommunicationInterface communicationInterface
object sync = new object()
Detailed Description
Manipulation of Lego Mindstorms NXT device.
The class allows to manipulate with Lego Mindstorms NXT device, setting/getting its motors' state, getting information about sensors' values and retrieving generic information about the NXT brick.
<note>Only communication through Bluetooth (virtual serial port) is supported at this point.</note>
Sample usage:
// create an instance of NXT brick
NXTBrick nxt = new NXTBrick();
// connect to the device
if (nxt.Connect("COM8"))
{
    // run motor A
    NXTBrick.MotorState motorState = new NXTBrick.MotorState( );
    motorState.Power      = 70;
    motorState.TurnRatio  = 50;
    motorState.Mode       = NXTBrick.MotorMode.On;
    motorState.Regulation = NXTBrick.MotorRegulationMode.Idle;
    motorState.RunState   = NXTBrick.MotorRunState.Running;
    motorState.TachoLimit = 1000;
    nxt.SetMotorState( NXTBrick.Motor.A, motorState );
    // get input value from the first sensor
    NXTBrick.SensorValues sensorValues;
    if ( nxt.GetSensorValue( NXTBrick.Sensor.First, out sensorValues ) )
    {
        // ...
    }
    // ...
}
Member Enumeration Documentation
Sensor
enum AForge.Robotics.Lego.NXTBrick.Sensor strong
Enumeration of NXT brick sensor ports.
Enumerator
First
First sensor.
Second
Second sensor.
Third
Third sensor.
Fourth
Fourth sensor.
SensorType
enum AForge.Robotics.Lego.NXTBrick.SensorType strong
Enumeration of NXT brick sensor types.
Enumerator
NoSensor
No sensor.
Switch
NXT or Legacy touch sensor.
Temperature
Legacy temperature sensor.
Reflection
Legacy light sensor.
Angle
Legacy rotation sensor.
LightActive
NXT light sensor with floodlight enabled.
LightInactive
NXT light sensor with floodlight disabled.
SoundDB
NXT sound sensor (dB scaling).
SoundDBA
NXT sound sensor (dBA scaling).
Custom
Unused
Lowspeed
I2C digital sensor.
Lowspeed9V
I2C digital sensor (9V power).
Highspeed
Unused.
ColorFull
NXT 2.0 color sensor in color detector mode.
ColorRed
NXT 2.0 color sensor in light sensor mode with red light on.
ColorGreen
NXT 2.0 color sensor in light sensor mode with green light on.
ColorBlue
NXT 2.0 color sensor in light sensor mode with blue light on.
ColorNone
NXT 2.0 color sensor in light sensor mode without light.
ColorExit
NXT 2.0 color sensor internal state (no functionality known yet).
SensorMode
enum AForge.Robotics.Lego.NXTBrick.SensorMode strong
Enumeration of NXT brick sensor modes.
Enumerator
Raw
Raw mode.
Boolean
Boolean mode. Report scaled value as 1 (TRUE) or 0 (FALSE). The firmware uses inverse Boolean logic to match the physical characteristics of NXT sensors. Readings are FALSE if raw value exceeds 55% of total range; reading are TRUE if raw value is less than 45% of total range.
TransitionCounter
Report scaled value as number of transition between TRUE and FALSE.
PeriodicCounter
Report scaled value as number of transitions from FALSE to TRUE, then back to FALSE.
PCTFullScale
Report scaled value as percentage of full scale reading for configured sensor type.
Celsius
Scale terperature reading to degrees Celsius.
Fahrenheit
Scale terperature reading to degrees Fahrenheit.
AngleSteps
Report scaled value as count of ticks on RCX-style rotation sensor.
Motor
enum AForge.Robotics.Lego.NXTBrick.Motor strong
Enumeration of NXT brick motor ports.
Enumerator
A
Motor A.
B
Motor B.
C
Motor C.
All
All motors (A, B and C).
MotorMode
enum AForge.Robotics.Lego.NXTBrick.MotorMode strong
Enumeration of supported motor modes.
Motor mode is a bit field, so several modes can be combined.
Enumerator
None
Mode is not set.
On
Turn on the motor.
Brake
Brake.
Regulated
Turn on regulated mode.
MotorRegulationMode
enum AForge.Robotics.Lego.NXTBrick.MotorRegulationMode strong
Enumeration of motor regulation modes.
Enumerator
Idle
No regulation will be enabled.
Speed
Power control will be enabled on specified motor.
Sync
Synchronization will be enabled.
<note>Synchronization need to be enabled on two motors.</note>
MotorRunState
enum AForge.Robotics.Lego.NXTBrick.MotorRunState strong
Enumeration of motor run states.
Enumerator
Idle
Motor will be idle.
RampUp
Motor will ramp-up.
Running
Motor will be running.
RampDown
Motor will ramp-down.
Constructor & Destructor Documentation
NXTBrick()
AForge.Robotics.Lego.NXTBrick.NXTBrick () inline
Initializes a new instance of the NXTBrick class.
~NXTBrick()
AForge.Robotics.Lego.NXTBrick.~NXTBrick () inline private
Destroys the instance of the NXTBrick class.
References AForge.Robotics.Lego.NXTBrick.Disconnect().
Member Function Documentation
Connect()
bool AForge.Robotics.Lego.NXTBrick.Connect (string portName) inline
Connect to NXT brick.
Parameters
portName Serial port name to use for communication, for example COM1.
Returns
Returns true on successful connection or false otherwise.
If connection to NXT brick was established before the call, existing connection will be reused. If it is required to force reconnection, then Disconnect method should be called before.
References AForge.Robotics.Lego.NXTBrick.communicationInterface, AForge.Robotics.Lego.NXTBrick.Disconnect(), AForge.Robotics.Lego.NXTBrick.IsAlive(), and AForge.Robotics.Lego.NXTBrick.sync.
Referenced by NXTTest.MainForm.connectButton_Click().
Disconnect()
void AForge.Robotics.Lego.NXTBrick.Disconnect () inline
Disconnect from Lego NXT brick.
References AForge.Robotics.Lego.NXTBrick.communicationInterface, and AForge.Robotics.Lego.NXTBrick.sync.
Referenced by AForge.Robotics.Lego.NXTBrick.Connect(), NXTTest.MainForm.disconnectButton_Click(), and AForge.Robotics.Lego.NXTBrick.~NXTBrick().
IsAlive()
bool AForge.Robotics.Lego.NXTBrick.IsAlive () inline
Check if the NXT brick is alive and responds to messages.
Returns
Returns true if device is alive or false otherwise.
The command also keeps NXT brick alive preventing it from sleep.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by AForge.Robotics.Lego.NXTBrick.Connect().
PlayTone() [1/2]
bool AForge.Robotics.Lego.NXTBrick.PlayTone (short frequency, short duration) inline
Play tone of specified frequency.
Parameters
frequency Tone frequency in Hz.
duration Tone duration in milliseconds.
Returns
Returns true if device is alive or false otherwise.
Referenced by NXTTest.MainForm.connectButton_Click().
PlayTone() [2/2]
bool AForge.Robotics.Lego.NXTBrick.PlayTone (short frequency, short duration, bool waitReply) inline
Play tone of specified frequency.
Parameters
frequency Tone frequency in Hz.
duration Tone duration in milliseconds.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if device is alive or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
GetVersion()
bool AForge.Robotics.Lego.NXTBrick.GetVersion (out string protocolVersion, out string firmwareVersion) inline
Get firmware version of NXT brick.
Parameters
protocolVersion Protocol version number.
firmwareVersion Firmware version number.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by NXTTest.MainForm.CollectInformation().
GetDeviceInformation()
bool AForge.Robotics.Lego.NXTBrick.GetDeviceInformation (out string deviceName, out byte[] btAddress, out int btSignalStrength, out int freeUserFlash) inline
Get information about NXT device.
Parameters
deviceName Device name.
btAddress Bluetooth address.
btSignalStrength Bluetooth signal strength.
freeUserFlash Free user Flash.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by NXTTest.MainForm.CollectInformation().
GetBatteryPower()
bool AForge.Robotics.Lego.NXTBrick.GetBatteryPower (out int power) inline
Get battery power of NXT brick.
Parameters
power NXT brick's battery power in millivolts.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by NXTTest.MainForm.CollectInformation().
SetBrickName()
bool AForge.Robotics.Lego.NXTBrick.SetBrickName (string deviceName) inline
Set name of NXT device.
Parameters
deviceName Device name to set for the brick.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
ResetMotorPosition() [1/2]
bool AForge.Robotics.Lego.NXTBrick.ResetMotorPosition (Motor motor, bool relative) inline
Reset motor's position.
Parameters
motor Motor to reset.
relative Specifies if relative (to last movement) or absolute motor's position should reset.
Returns
Returns true if command was executed successfully or false otherwise.
Referenced by NXTTest.MainForm.resetMotorButton_Click().
ResetMotorPosition() [2/2]
bool AForge.Robotics.Lego.NXTBrick.ResetMotorPosition (Motor motor, bool relative, bool waitReply) inline
Reset motor's position.
Parameters
motor Motor to reset.
relative Specifies if relative (to last movement) or absolute motor's position should reset.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
SetMotorState() [1/2]
bool AForge.Robotics.Lego.NXTBrick.SetMotorState (Motor motor, MotorState state) inline
Set motor state.
Parameters
motor Motor to set state for.
state Motor's state to set.
Returns
Returns true if command was executed successfully or false otherwise.
Referenced by NXTTest.MainForm.setMotorStateButton_Click().
SetMotorState() [2/2]
bool AForge.Robotics.Lego.NXTBrick.SetMotorState (Motor motor, MotorState state, bool waitReply) inline
Set motor state.
Parameters
motor Motor to set state for.
state Motor's state to set.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.MotorState.Mode, AForge.Robotics.Lego.NXTBrick.MotorState.Power, AForge.Robotics.Lego.NXTBrick.MotorState.Regulation, AForge.Robotics.Lego.NXTBrick.MotorState.RunState, AForge.Robotics.Lego.NXTBrick.SendCommand(), AForge.Robotics.Lego.NXTBrick.MotorState.TachoLimit, and AForge.Robotics.Lego.NXTBrick.MotorState.TurnRatio.
GetMotorState()
bool AForge.Robotics.Lego.NXTBrick.GetMotorState (Motor motor, out MotorState state) inline
Get motor state.
Parameters
motor Motor to get state for.
state Motor's state.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by NXTTest.MainForm.getMotorStateButton_Click().
SetSensorMode() [1/2]
bool AForge.Robotics.Lego.NXTBrick.SetSensorMode (Sensor sensor, SensorType type, SensorMode mode) inline
Set sensor's type and mode.
Parameters
sensor Sensor to set type of.
type Sensor's type.
mode Sensor's mode.
Returns
Returns true if command was executed successfully or false otherwise.
Referenced by NXTTest.MainForm.setInputModeButton_Click().
SetSensorMode() [2/2]
bool AForge.Robotics.Lego.NXTBrick.SetSensorMode (Sensor sensor, SensorType type, SensorMode mode, bool waitReply) inline
Set sensor's type and mode.
Parameters
sensor Sensor to set type of.
type Sensor's type.
mode Sensor's mode.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
GetSensorValue()
bool AForge.Robotics.Lego.NXTBrick.GetSensorValue (Sensor sensor, out SensorValues sensorValues) inline
Get sensor's values.
Parameters
sensor Sensor to get values of.
sensorValues etrieved sensor's values.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by NXTTest.MainForm.getInputButton_Click().
ClearSensor() [1/2]
bool AForge.Robotics.Lego.NXTBrick.ClearSensor (Sensor sensor) inline
Clear sensor's scaled value.
Parameters
sensor Sensor to clear value of.
Returns
Returns true if command was executed successfully or false otherwise.
ClearSensor() [2/2]
bool AForge.Robotics.Lego.NXTBrick.ClearSensor (Sensor sensor, bool waitReply) inline
Clear sensor's scaled value.
Parameters
sensor Sensor to clear value of.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
LsGetStatus()
bool AForge.Robotics.Lego.NXTBrick.LsGetStatus (Sensor sensor, out int readyBytes) inline
Get status of Low Speed bus.
Parameters
sensor Sensor to get the status from.
readyBytes Number of bytes that are ready to be read from the bus.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by AForge.Robotics.Lego.NXTBrick.GetUltrasonicSensorsValue(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicAccelerationTiltSensor(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicColorSensor(), and AForge.Robotics.Lego.NXTBrick.ReadHiTechnicCompassSensor().
LsWrite() [1/2]
bool AForge.Robotics.Lego.NXTBrick.LsWrite (Sensor sensor, byte[] data, int expectedBytes) inline
Write to Low Speed bus.
Parameters
sensor Sensor to write to.
data Data to send to the I2C device.
expectedBytes Number of bytes expected from device on reply, [0..16]. Can be set to zero if I2C command does not suppose any reply.
Returns
Returns true if command was executed successfully or false otherwise.
Exceptions
ArgumentException Data length must be in the [1..16] range.
Referenced by AForge.Robotics.Lego.NXTBrick.GetUltrasonicSensorsValue(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicAccelerationTiltSensor(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicColorSensor(), and AForge.Robotics.Lego.NXTBrick.ReadHiTechnicCompassSensor().
LsWrite() [2/2]
bool AForge.Robotics.Lego.NXTBrick.LsWrite (Sensor sensor, byte[] data, int expectedBytes, bool waitReply) inline
Write to Low Speed bus.
Parameters
sensor Sensor to write to.
data Data to send to the I2C device.
expectedBytes Number of bytes expected from device on reply, [0..16]. Can be set to zero if I2C command does not suppose any reply.
waitReply Wait reply from NXT (safer option) or not (faster option).
Returns
Returns true if command was executed successfully or false otherwise.
Exceptions
ArgumentException Data length must be in the [1..16] range.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
LsRead()
bool AForge.Robotics.Lego.NXTBrick.LsRead (Sensor sensor, byte[] readValues, out int bytesRead) inline
Read data from Low Speed bus.
Parameters
sensor Sensor to read data from.
readValues Array to read data to.
bytesRead Bytes actually read from I2C device.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.NXTBrick.SendCommand().
Referenced by AForge.Robotics.Lego.NXTBrick.GetUltrasonicSensorsValue(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicAccelerationTiltSensor(), AForge.Robotics.Lego.NXTBrick.ReadHiTechnicColorSensor(), and AForge.Robotics.Lego.NXTBrick.ReadHiTechnicCompassSensor().
GetUltrasonicSensorsValue()
bool AForge.Robotics.Lego.NXTBrick.GetUltrasonicSensorsValue (Sensor sensor, out int value) inline
Read value of ultrasonic distance sensor.
Parameters
sensor Sensor to read value from.
value Distance value obtained from ultrasonic sensor, [0..255] cm.
Returns
Returns true if command was executed successfully or false otherwise.
The method retrieves value of ultrasonic distance sensor by communicating with I2C device (writing to and reading from low speed bus). The method first sends { 0x02, 0x42 } command to the specified device using LsWrite(Sensor, byte[], int) method. Then it waits until there is something available to read using LsGetStatus method. Finally it reads sensor's value using LsRead device. See this page for details.
<note>Before using this method it is required to use SetSensorMode(Sensor, SensorType, SensorMode, bool) method to set sensor's type to SensorType.Lowspeed9V mode. It should be done once after NXT brick is powered on. If sensor's type is not set properly, the method will generate an exception. Also after setting sensor's type application may need to wait a bit to give device some time to initialize.</note>
References AForge.Robotics.Lego.NXTBrick.LsGetStatus(), AForge.Robotics.Lego.NXTBrick.LsRead(), and AForge.Robotics.Lego.NXTBrick.LsWrite().
SendCommand()
bool AForge.Robotics.Lego.NXTBrick.SendCommand (byte[] command, byte[] reply) inline
Send command to Lego NXT brick and read reply.
Parameters
command Command to send.
reply Buffer to receive reply into.
Returns
Returns true if the command was sent successfully and reply was received, otherwise false.
Exceptions
NullReferenceException Communication can not be performed, because connection with NXT brick was not established yet.
ArgumentException Reply buffer size is smaller than the reply data size.
ApplicationException Reply does not correspond to command (second byte of reply should be equal to second byte of command).
ApplicationException Error occurred on NXT brick side.
References AForge.Robotics.Lego.NXTBrick.communicationInterface, AForge.Robotics.Lego.NXTBrick.MessageRead, AForge.Robotics.Lego.NXTBrick.MessageSent, and AForge.Robotics.Lego.NXTBrick.sync.
Referenced by AForge.Robotics.Lego.NXTBrick.ClearSensor(), AForge.Robotics.Lego.NXTBrick.GetBatteryPower(), AForge.Robotics.Lego.NXTBrick.GetDeviceInformation(), AForge.Robotics.Lego.NXTBrick.GetMotorState(), AForge.Robotics.Lego.NXTBrick.GetSensorValue(), AForge.Robotics.Lego.NXTBrick.GetVersion(), AForge.Robotics.Lego.NXTBrick.IsAlive(), AForge.Robotics.Lego.NXTBrick.LsGetStatus(), AForge.Robotics.Lego.NXTBrick.LsRead(), AForge.Robotics.Lego.NXTBrick.LsWrite(), AForge.Robotics.Lego.NXTBrick.PlayTone(), AForge.Robotics.Lego.NXTBrick.ResetMotorPosition(), AForge.Robotics.Lego.NXTBrick.SetBrickName(), AForge.Robotics.Lego.NXTBrick.SetMotorState(), and AForge.Robotics.Lego.NXTBrick.SetSensorMode().
ReadHiTechnicColorSensor()
bool AForge.Robotics.Lego.NXTBrick.ReadHiTechnicColorSensor (NXTBrick.Sensor sensor, ref int colorNumber, ref int redValue, ref int greenValue, ref int blueValue) inline
Read data from HiTechnic color sensor (also color sensor v2).
Parameters
sensor Sensor to read from.
colorNumber Found color number.
redValue Found red value.
greenValue Found green value.
blueValue Found blue value.
Returns
Returns true if the command was sent successfully and reply was received, otherwise false.
The method retrieves the color valuse of a HiTechnic color sensor by communicating with I2C device (writing to and reading from low speed bus). The method first sends { 0x02, 0x42 } command to the specified device using LsWrite(Sensor, byte[], int) method. Then it waits until there is something available to read using LsGetStatus method. Finally it reads sensor's value using LsRead device. See this page for details.
<note>Before using this method it is required to use SetSensorMode(Sensor, SensorType, SensorMode, bool) method to set sensor's type to SensorType.Lowspeed mode. It should be done once after NXT brick is powered on. If sensor's type is not set properly, the method will generate an exception. Also after setting sensor's type application may need to wait a bit to give device some time to initialize.</note>
<note>NXT Firmware version 1.24 must be loaded in the NXT for the HiTechnic color sensor to operate correctly. You can check the firmware version using the GetVersion method.</note>
<note>The color sensor V2 must be configured to match the mains electricity frequency for your country. Details on how to configure the Color Sensor V2 can be found at </note>
References AForge.Robotics.Lego.NXTBrick.LsGetStatus(), AForge.Robotics.Lego.NXTBrick.LsRead(), and AForge.Robotics.Lego.NXTBrick.LsWrite().
ReadHiTechnicCompassSensor()
bool AForge.Robotics.Lego.NXTBrick.ReadHiTechnicCompassSensor (NXTBrick.Sensor sensor, ref int angle) inline
Read data from HiTechnic compass sensor.
Parameters
sensor Sensor to read from.
angle The magnetic heading, [0, 359] degrees.
Returns
Returns true if the command was sent successfully and reply was received, otherwise false.
The method retrieves the angle of a HiTechnic compass sensor by communicating with I2C device (writing to and reading from low speed bus). The method first sends { 0x02, 0x42 } command to the specified device using LsWrite(Sensor, byte[], int) method. Then it waits until there is something available to read using LsGetStatus method. Finally it reads sensor's value using LsRead device. See this page for details.
<note>Before using this method it is required to use SetSensorMode(Sensor, SensorType, SensorMode, bool) method to set sensor's type to SensorType.Lowspeed mode. It should be done once after NXT brick is powered on. If sensor's type is not set properly, the method will generate an exception. Also after setting sensor's type application may need to wait a bit to give device some time to initialize.</note>
<note>The HiTechnic compass sensor will only operate correctly in a horizontal plane so you must keep the compass level for it to read correctly. This is very important so remember this when you build it into your robot. It is highly desirable to mount the compass at least 6 inches (15cm) away from the motors and 4 inches (10cm) away from the NXT brick itself. Try to make sure it is firmly mounted, if it bounces around, the readings may bounce around too. </note>
<note>NXT Firmware version 1.03 must be loaded in the NXT for the compass to operate correctly. You can check the firmware version using the GetVersion method.</note>
References AForge.Robotics.Lego.NXTBrick.LsGetStatus(), AForge.Robotics.Lego.NXTBrick.LsRead(), and AForge.Robotics.Lego.NXTBrick.LsWrite().
ReadHiTechnicAccelerationTiltSensor()
bool AForge.Robotics.Lego.NXTBrick.ReadHiTechnicAccelerationTiltSensor (NXTBrick.Sensor sensor, ref int xAceeleration, ref int yAceeleration, ref int zAceeleration) inline
Read data from HiTechnic acceleration/tilt sensor. The HiTechnic accelerometer/tilt sensor measures acceleration in three axes. It measures also tilt along each axis. Using the sensor, you can measure the acceleration of your robot in the range of -2g to 2g.
Parameters
sensor Sensor to read from.
xAceeleration Acceleration in X direction, with a scaling of approximately 200 counts per g.
yAceeleration Acceleration in Y direction, with a scaling of approximately 200 counts per g.
zAceeleration Acceleration in Z direction, with a scaling of approximately 200 counts per g.
Returns
Returns true if the command was sent successfully and reply was received, otherwise false.
The method retrieves the acceleration in three directions of a HiTechnic acceleration/tilt sensor by communicating with I2C device (writing to and reading from low speed bus). The method first sends { 0x02, 0x42 } command to the specified device using LsWrite(Sensor, byte[], int) method. Then it waits until there is something available to read using LsGetStatus method. Finally it reads sensor's value using LsRead device. See this page for details.
<note>Before using this method it is required to use SetSensorMode(Sensor, SensorType, SensorMode, bool) method to set sensor's type to SensorType.Lowspeed mode. It should be done once after NXT brick is powered onq If sensor's type is not set properly, the method will generate an exception. Also after setting sensor's type application may need to wait a bit to give device some time to initialize.</note>
The acceleration sensor can also be used to measure tilt in three axes This is possible because gravity is perceived as acceleration. When the sensor is stationary and in the normal horizontal position, the x and y axis will be near zero, because they are horizontal, while the z axis will be near 200, which represents g. If you tilt the sensor then gravity will also be detected on the other axis and the value for the z axis will go down. Since gravity is distributed among the three component vectors, the tilt of the sensor can be determined.
<note>NXT Firmware version 1.05 or later must be loaded in the NXT for the acceleration/tilt sensor and other digital I2C sensors to operate correctly. You can check the firmware version using the GetVersion method.</note>
References AForge.Robotics.Lego.NXTBrick.LsGetStatus(), AForge.Robotics.Lego.NXTBrick.LsRead(), and AForge.Robotics.Lego.NXTBrick.LsWrite().
Member Data Documentation
communicationInterface
INXTCommunicationInterface AForge.Robotics.Lego.NXTBrick.communicationInterface private
Referenced by AForge.Robotics.Lego.NXTBrick.Connect(), AForge.Robotics.Lego.NXTBrick.Disconnect(), and AForge.Robotics.Lego.NXTBrick.SendCommand().
sync
object AForge.Robotics.Lego.NXTBrick.sync = new object() private
Referenced by AForge.Robotics.Lego.NXTBrick.Connect(), AForge.Robotics.Lego.NXTBrick.Disconnect(), and AForge.Robotics.Lego.NXTBrick.SendCommand().
Property Documentation
IsConnected
bool AForge.Robotics.Lego.NXTBrick.IsConnected get
Check if connection to NXT brick is established.
Event Documentation
MessageSent
MessageTransferHandler AForge.Robotics.Lego.NXTBrick.MessageSent
The event is raised every time a command is sent successfully.
Referenced by NXTTest.MainForm.MainForm(), and AForge.Robotics.Lego.NXTBrick.SendCommand().
MessageRead
MessageTransferHandler AForge.Robotics.Lego.NXTBrick.MessageRead
The event is raised every time a command is read successfully.
Referenced by NXTTest.MainForm.MainForm(), and AForge.Robotics.Lego.NXTBrick.SendCommand().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.Lego/NXTBrick.cs