Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASSQ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASSQ Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASSQ ()
void Run (int N, double[] X, int offset_x, int INCX, ref double SCALE, ref double SUMSQ)
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASSQ returns the values scl and smsq such that
(scl**2)*smsq = x(1)**2 +...+ x(n)**2 + (scale**2)*sumsq,
where x(i) = X(1 + (i - 1)*INCX). The value of sumsq is assumed to be non-negative and scl returns the value
scl = max(scale, abs(x(i))).
scale and sumsq must be supplied in SCALE and SUMSQ and scl and smsq are overwritten on SCALE and SUMSQ respectively.
The routine makes only one pass through the vector x.
/summary>
Constructor & Destructor Documentation
DLASSQ()
DotNumerics.LinearAlgebra.CSLapack.DLASSQ.DLASSQ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run (int N, double[] X, int offset_x, int INCX, ref double SCALE, ref double SUMSQ) inline
Purpose
DLASSQ returns the values scl and smsq such that
(scl**2)*smsq = x(1)**2 +...+ x(n)**2 + (scale**2)*sumsq,
where x(i) = X(1 + (i - 1)*INCX). The value of sumsq is assumed to be non-negative and scl returns the value
scl = max(scale, abs(x(i))).
scale and sumsq must be supplied in SCALE and SUMSQ and scl and smsq are overwritten on SCALE and SUMSQ respectively.
The routine makes only one pass through the vector x.
/summary>
Parameters
N (input) INTEGER The number of elements to be used from the vector X. /param>
Parameters
X (input) DOUBLE PRECISION array, dimension (N) The vector for which a scaled sum of squares is computed. x(i) = X(1 + (i - 1)*INCX), 1 .LE. i .LE. n. /param>
Parameters
INCX (input) INTEGER The increment between successive values of the vector X. INCX .GT. 0. /param>
Parameters
SCALE and sumsq must be supplied in SCALE and SUMSQ and /param>
Parameters
SUMSQ (input/output) DOUBLE PRECISION On entry, the value sumsq in the equation above. On exit, SUMSQ is overwritten with smsq , the basic sum of squares from which scl has been factored out. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASSQ.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run().
Member Data Documentation
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASSQ.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlassq.cs