Doc: IGLib EXTENDED: alglib.chisquaredistr Class Reference
alglib.chisquaredistr Class Reference
Static Public Member Functions
static double chisquaredistribution (double v, double x)
static double chisquarecdistribution (double v, double x)
static double invchisquaredistribution (double v, double y)
static double chisquaredistribution (double v, double x)
static double chisquarecdistribution (double v, double x)
static double invchisquaredistribution (double v, double y)
Member Function Documentation
chisquaredistribution() [1/2]
static double alglib.chisquaredistr.chisquaredistribution (double v, double x) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegamma().
Referenced by alglib.chisquaredistribution(), and alglib.variancetests.onesamplevariancetest().
chisquarecdistribution() [1/2]
static double alglib.chisquaredistr.chisquarecdistribution (double v, double x) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegammac().
Referenced by alglib.chisquarecdistribution().
invchisquaredistribution() [1/2]
static double alglib.chisquaredistr.invchisquaredistribution (double v, double y) inline static
References alglib.ap.assert(), and alglib.igammaf.invincompletegammac().
Referenced by alglib.invchisquaredistribution().
chisquaredistribution() [2/2]
static double alglib.chisquaredistr.chisquaredistribution (double v, double x) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegamma().
chisquarecdistribution() [2/2]
static double alglib.chisquaredistr.chisquarecdistribution (double v, double x) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegammac().
invchisquaredistribution() [2/2]
static double alglib.chisquaredistr.invchisquaredistribution (double v, double y) inline static
References alglib.ap.assert(), and alglib.igammaf.invincompletegammac().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs